### ISSUE TITLE
[Bug] RayCluster creation with bad name fails with no actionable error message

### ISSUE THREAD

**Issue by davidxia** [ray-project/kuberay#1009]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I created a RayCluster with a `.` in the name like `dxia.test` with `kubectl apply -f path/to/file.yaml`. `kubectl` exited with 0, but then listing the cluster shows it has `STATUS` of `failed`.

```
kubectl get rayclusters

NAME         DESIRED WORKERS   AVAILABLE WORKERS   STATUS   AGE
dxia.test                                          failed   3m18s
```

`kubectl describe` doesn't show actionable error message.

```
kubectl describe rayclusters dxia.test

Name:         dxia.test
API Version:  ray.io/v1alpha1
Kind:         RayCluster

...

Status:
  Head:
  State:  failed
Events:
  Type    Reason   Age   From  Message
  ----    ------   ----  ----  -------
  Normal  Logging  52s   kopf  Timer 'resource_garbage_collection' succeeded.
  Normal  Logging  45s   kopf  Timer 'annotate_estimated_costs' succeeded.
```

I expect `kubectl` to fail early or at the very least an actionable error message.

### Reproduction script

`kubectl apply -f` any RayCluster YAML file [like this example](https://github.com/ray-project/ray/blob/e6dad0b961b5e962f6dc4986947ccac2d2e032cd/python/ray/autoscaler/kuberay/ray-cluster.complete.yaml) where the `name` includes a `.`.

### Anything else

kuberay-operator logs show root error. This should be surfaced to user.

`2023-04-04T21:46:42.823Z	ERROR	controller.raycluster-controller	Reconciler error	{"reconciler group": "ray.io", "reconciler kind": "RayCluster", "name": "dxia.test2", "namespace": "hyperkube", "error": "Service \"dxia.test2-head-svc\" is invalid: metadata.name: Invalid value: \"dxia.test2-head-svc\": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')"}`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Is it possible to report error before creating the RayCluster? This [doc](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema) seems to be helpful.

**Comment by davidxia** [comment]
@kevin85421 thanks. The `.metadata.name` is [inlined in the `RayCluster` struct here](https://github.com/davidxia/kuberay/blob/f6a172f3d7e44d4ee22bd058f2c33a69601c39c2/ray-operator/apis/ray/v1alpha1/raycluster_types.go#L166). Is it possible to add validation rules to inlined fields with `// +kubebuilder:validation:Pattern=...`? I wonder how code generation would know which inlined field to apply the validation to.

```
	// +kubebuilder:validation:Pattern="[a-z]([-a-z0-9]*[a-z0-9])?""
	metav1.ObjectMeta `json:"metadata,omitempty"`
```

**Comment by davidxia** [comment]
@kevin85421 I'm not sure `+kubebuilder:validation` will work on the inlined `metav1.ObjectMeta` field in the `RayCluster` struct. Maybe name validation is better handled by a [potential validating webhook](https://github.com/ray-project/kuberay/pull/1584)? cc @DmitriGekhtman if you have any thoughts

**Comment by davidxia** [comment]
I'm thinking of fixing this with validating webhook now that it's supported https://github.com/ray-project/kuberay/pull/1584
