### ISSUE TITLE
[Docs] Improve metrics/grafana docs to include info on how to utilize the new Ray dashboard features.

### ISSUE THREAD

**Issue by alanwguo** [ray-project/kuberay#1020]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

The current grafana / prometheus docs works well for folks using grafana UI directly. However, in ray 2.2 and above there are metrics features embedded into the Ray Dashboard UI and those features should work with kube-ray's grafana deployment.

### Reproduction script

None. Just launch a cluster and check the ray dashboar.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by dcela** [comment]
Related Slack discussion: https://ray-distributed.slack.com/archives/CP950VC76/p1689179832076669
Also willing to submit a PR once I have time to figure it out myself :)
