### ISSUE TITLE
[Feature] KubeRay website improvement

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1021]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

* https://ray-project.github.io/kuberay/
  * Add a link to "Getting Started"
  * Update the introduction of KubeRay &#9989; ([#1042](https://github.com/ray-project/kuberay/pull/1042))
  * Add a section of "Engineering Blogs"
  * Add some links (e.g. RayCluster) in the introduction section when the related documents are ready.

* https://ray-project.github.io/kuberay/deploy/installation/
  * Add instructions for ARM chip 
* https://ray-project.github.io/kuberay/guidance/ingress/
  <details>
    <summary>layout &#9989; (#1042)</summary>
    
    ![Screen Shot 2023-04-07 at 11 05 51 AM](https://user-images.githubusercontent.com/20109646/230656393-0804a724-1434-4840-87bf-2e3cef8008bc.png)
  </details>

* https://ray-project.github.io/kuberay/deploy/helm-cluster/
  <details>
    <summary>layout &#9989; (#1042)</summary>
    
   ![Screen Shot 2023-04-07 at 11 11 45 AM](https://user-images.githubusercontent.com/20109646/230657125-bedd0efc-eb34-4bc4-9343-34ca1016419b.png)
  </details>
  
* Add a diagram to the [autoscaler](https://ray-project.github.io/kuberay/guidance/autoscaler/) document.
  * https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/configuring-autoscaling.html 

* https://ray-project.github.io/kuberay/components/operator/
  * Add Python client to this page.

* https://github.com/ray-project/kuberay/blob/master/ray-operator/README.md
  * Rewrite this document, and add an overview for all RayCluster features (e.g. autoscaler, fault tolerance)   

### New documents

* Logging: https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/logging.html
  * A YAML example for logging

* GPU document: https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/gpu.html
* GPU example: https://docs.ray.io/en/latest/cluster/kubernetes/examples/gpu-training-example.html
* GCS FT example

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by nicklausbrown** [comment]
Reading through the bullets, does this mean there is a way currently to support ARM chips?
