### ISSUE TITLE
[Feature] reproduce all deployment configuration options in the rayservice yaml file

### ISSUE THREAD

**Issue by brosand** [ray-project/kuberay#1027]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

The current implementation of the @ray.deployment decorator allows users to specify various deployment options such as the number of replicas, resources, and environment variables. However, these options can only be specified in the Python code, which can make it difficult to manage and modify the deployment configuration.

This feature request aims to add all the deployment options from the @ray.deployment decorator to the rayservice YAML file, allowing users to specify the deployment configuration in a separate file. For example -- right now the user can only specify autoscaling options in the python code, requiring images to be rebuilt for any changes.

### Use case

Consider a use case where a user wants to deploy a Ray service that requires autoscaling to handle variable workloads. Currently, the user has to specify the deployment options in the Python code, which can make it difficult to modify and manage the deployment configuration. With the proposed feature, the user can specify the deployment configuration, including the autoscaling options, in the YAML file. This will enable the user to modify the deployment configuration without touching the Python code, making it easier to manage and maintain the deployment.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by brosand** [comment]
Looking closer at https://docs.ray.io/en/master/serve/production-guide/config.html#serve-in-production-config-file -- it seems like this feature already exists  -- if someone from ray wants to confirm we can close this

**Comment by akshay-anyscale** [comment]
Yes that's right, the deployment options can all be specified in the yaml file
