### ISSUE TITLE
[Bug]  There are some error of kuberay document

### ISSUE THREAD

**Issue by xubo245** [ray-project/kuberay#1045]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator, Others

### What happened + What you expected to happen

1.The bug:
When I open the link of [ray-cluster.autoscaler.large.yaml](https://ray-project.github.io/kuberay/components/config/samples/ray-cluster.autoscaler.yaml). of https://ray-project.github.io/kuberay/components/operator/, it will show https://ray-project.github.io/kuberay/components/config/samples/ray-cluster.autoscaler.yaml, which is not ray-cluster.autoscaler.large.yaml.

2.  expected behavior
it should return the detail of cluster.autoscaler.large.yaml
4.  useful information
error link

### Reproduction script

document error 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Thank you for pointing this out! Would you mind opening a PR?

**Comment by kevin85421** [comment]
Closed by #1046
