### ISSUE TITLE
[Bug] Job's logs are lost when head node is restarted

### ISSUE THREAD

**Issue by lrivela** [ray-project/kuberay#1047]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Hello,

I am using KubeRay on a Google Kubernetes Engine cluster.
* GKE: 1.25.7-gke.1000
* KubeRay Operator: 0.5.0
* Ray Library: 2.3.1

Configuration:
I am using the following example that enables the GCS Fault Tolerance with Redis: 
* https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.external-redis.yaml

Description:
 I'm facing a problem when I submit a Tune Job via the Job CLI / Python SDK and I want to check the logs in the Dashboard.
While the job is running and when the job finishes (and the worker pod is removed from GKE) I can still check the job logs through the dashboard, but if the head node is restarted for any reason, I'm no longer able to retrieve those logs:

![image](https://user-images.githubusercontent.com/14956339/234397261-0c1dc040-d424-465f-80c7-be1fc387fa8d.png)

Expected Behavior:
To be able to retrieve the logs.

Useful information:
I assume this is happening because the head node pod restarts and is initialized with a different IP within the cluster, and somehow Ray uses the old IP to retrieve the logs:

![request](https://user-images.githubusercontent.com/14956339/234399549-84a4606b-55a5-4d10-99d3-9fba6d3f6457.png)

![response](https://user-images.githubusercontent.com/14956339/234399572-87cac0a9-06bc-44db-9e47-499d6609fb4d.png)

I am not sure if I am missing any configuration or this is a know limitation from the platform, I'd appreciate any help you could provide.

Thanks!
Lucas

### Reproduction script

- Deploy a Ray Cluster within Kubernetes as in the mentioned example
- Submit a Tune Job via the Jobs CLI
- Restart the head node
- Check the Dashboard and try to retrieve the job's logs.

### Anything else

This problem occurs when the head node is restarted within the GKE cluster.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scottsun94** [comment]
Slack thread: https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1682522893195049

**Comment by lrivela** [comment]
Related issue: https://github.com/ray-project/ray/issues/35131

**Comment by kevin85421** [comment]
1. We only recommend users using GCS fault tolerance with Ray Serve.
2. For log persistence, you may use FluentBit / Vector + CloudWatch. See [this doc](https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/logging.html#kuberay-logging) for more details.

Close this issue in favor of https://github.com/ray-project/ray/issues/35131.
