### ISSUE TITLE
[Discussion] Whether to remove init_image parameter in Python client module 

### ISSUE THREAD

**Issue by jasoonn** [ray-project/kuberay#1072]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

The parameter `init_image`  in the function [build_worker()](https://github.com/ray-project/kuberay/blob/795db0dc9e09702caf23b936a86f77b0a3c5215b/clients/python-client/python_client/utils/kuberay_cluster_builder.py#LL118C9-L118C21) is originally used to set the image in [init container](https://github.com/ray-project/kuberay/blob/a9d29281eea07824dbc01c7c16b26d5a91fdd226/ray-operator/config/samples/ray-cluster.complete.yaml#L107-L113) in worker group spec. However, after https://github.com/ray-project/kuberay/pull/973, the init container is no longer needed for worker group spec, and the code snippet relevant to init container in Python-client are removed in https://github.com/ray-project/kuberay/pull/1006. Hence, the `init_image` became a redundant parameter.

On the other hand, because  `build_worker()` is a user-facing, removing `init_image` will break backward compatibility.
Hence, I am wondering whether it is a good idea to remove `init_image` from `build_worker()`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
We learned several lessons in these two months, which underscore the importance of keeping the init image configurable.
