### ISSUE TITLE
[Bug] No option to disable Default Init Container in workers 

### ISSUE THREAD

**Issue by Sharathmk99** [ray-project/kuberay#1076]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

In version `0.5.0` from PR #973 added default init container to check the readiness of the GCS, init container image is same as worker image. In our usecase we don't have `ray` package installed by default in docker image itself, we install ray python package on the fly to support multiple ray version for our users.
As the initi container is using `ray` CLI to check the status of the GCS, it's failing as `ray` package is not installed.
Please provide flag to disable this behaviour or allow to override `cmd` and `args` fields. This is a blocker for us to upgrade KubeRay to 0.5.0.

### Reproduction script

Use docker image which doesn't have `ray` python package installed as worker image.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Hi @Sharathmk99, thank you for opening this issue! After #1069 is merged, you can use the nightly KubeRay operator Docker image.
