### ISSUE TITLE
[Bug] Environment variable to select Ray container is lower case sensitive.

### ISSUE THREAD

**Issue by enozcan** [ray-project/kuberay#1078]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

RAY=true environment variable to identify Ray container does not seem to be working properly due to the check here:

https://github.com/ray-project/kuberay/blob/2019b4b0ab0ac7b70d9c059148cc639b7dd9b556/ray-operator/controllers/ray/common/pod.go#L495

where the check does not match with the command a few lines below:

https://github.com/ray-project/kuberay/blob/2019b4b0ab0ac7b70d9c059148cc639b7dd9b556/ray-operator/controllers/ray/common/pod.go#L496

It actually checks for `ray=true` env variable in a **case sensitive** manner.

### Reproduction script

--

### Anything else

It must align with the logged statement for `RAY=true` format. Also not sure if that is still valid as I have not seen that within the docs but in the source.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Good catch! Would you mind opening a PR to fix it?

**Comment by Yicheng-Lu-llll** [comment]
In my understanding, It is better to still set the ray container to be the first container (containers[0]).  There are segments of code that do not utilize the getRayContainerIndex method. For instance:


https://github.com/ray-project/kuberay/blob/2019b4b0ab0ac7b70d9c059148cc639b7dd9b556/ray-operator/controllers/ray/common/pod.go#L127

https://github.com/ray-project/kuberay/blob/2019b4b0ab0ac7b70d9c059148cc639b7dd9b556/ray-operator/controllers/ray/common/pod.go#L139

**Comment by enozcan** [comment]
> Would you mind opening a PR to fix it?

@kevin85421 Sure, just let me know if the final decision is to allowed options, e.g. case sensitive or not, both for key and value. 

> It is better to still set the ray container to be the first container (containers[0])

@Yicheng-Lu-llll That is a strict restriction, and from user point of view having this env var option (and documenting it clearly) would be a better alternative.

**Comment by kevin85421** [comment]
* I noticed that there is a public function that is similar to `getRayContainerIndex`. Maybe we can consider removing `getRayContainerIndex` and using `FindRayContainerIndex` instead.

  https://github.com/ray-project/kuberay/blob/b0649c43bbae3a0ac4917f94d80cbde466bb4f88/ray-operator/controllers/ray/utils/util.go#L190

* What's the current behavior if Ray container is not the first one? Will it always fail?

**Comment by enozcan** [comment]
> What's the current behavior if Ray container is not the first one? Will it always fail?

I believe it silently causes unexpected behavior.  Say I define 2 containers, linkerd and main respectively. Operator will check for linkerd container as it’s the first one, override its command and args (via merging the original one with ray start) - since linkerd command does not have “ray start”. In that case the other container which is supposed to be Ray worker will be useless. Consider the case where linkerd container resources are relatively small compared to the main one, or pre-installed libraries do not exist in the linkerd but main container, etc. So I don’t think it always causes failure, but causes other problems that are going to be visible only when pod is inspected through describe, operator annotations, etc.
