### ISSUE TITLE
Run pods using a specific service account

### ISSUE THREAD

**Issue by blublinsky** [ray-project/kuberay#1088]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, both head and worker pods are running using the default server account. As explained here https://loft.sh/blog/kubernetes-service-account-what-it-is-and-how-to-use-it/, CI/CD access to the cluster, pods-to-pods communication, or pods to Kubernetes API authentication all typically require a service account. The service account is also quite important for security reasons.

### Use case

if you want your pod to actually be able to talk to the Kubernetes API and do something, you have two options. You either need to assign some permissions to the default service account, or you need to create a new service account. The first option is not recommended. In fact, you shouldn’t use the default service account for anything. Another common use case is running KubeRay on OpenShift, which allows giving pods additional permissions based on service accounts

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Close this issue because #1138 is closed.
