### ISSUE TITLE
Use context passed to the reconciler for operations instead of creating a new one using context.TODO() every time

### ISSUE THREAD

**Issue by blublinsky** [ray-project/kuberay#1089]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

In the current implementation of the operator, reconciler method a new context is created for every operation. According to https://www.makeuseof.com/go-contexts/ context.TODO() should be used as a placeholder when you need a context but no parent contexts are suitable. In the case of a reconciler, one is already provided, so it should be used instead of creating a new one every time.

### Use case

This might be useful for additional things that context supports, including parameters passing, context timeouts and deadlines

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by anishasthana** [comment]
I'm happy to pick this issue up.
