### ISSUE TITLE
[Feature] Add labels to Kuberay apiserver services in helm chart

### ISSUE THREAD

**Issue by Sharathmk99** [ray-project/kuberay#1093]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently helm chart doesn't have any labels for `apiserver` service manifest. This is useful when we create `prometheus` `servicemonitor` CRD. Currently it's not possible to create as it doesn't have labels.

### Use case

Monitoring using `prometheus` `servicemonitor` for apiserver

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
@blublinsky has identified that this KubeRay API server issue can be closed.
