### ISSUE TITLE
[Bug] Ray autoscaler spawns hundreds of pods

### ISSUE THREAD

**Issue by peterghaddad** [ray-project/kuberay#1108]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Ray's autoscaler continues to create pods on unhealthy nodes, the pods become stuck in pending, the autoscaler retries, and then a large amount of pods are stuck in pending. Seeing over 100s of pods stuck in this pending state.

Similar to this issue:
https://github.com/ray-project/kuberay/pull/662/files

@DmitriGekhtman I know you submitted the above fix, if you have thoughts around where in the code might be causing this I am happy to submit a PR.

### Reproduction script

Submit a Ray job that is forced to schedule onto an unhealthy GPU node.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
That's quite odd.
Pending pods are supposed to contribute to non_terminated_nodes count in the autoscaler.
KuberayNodeProvider is the place to look.

I probably don't have time to help debug this unfortunately -- cc @kevin85421

**Comment by nvtkaszpir** [comment]
You can mitigate it with [node-problem-detector](https://github.com/kubernetes/node-problem-detector) and custom scripts to detect if GPU/node is faulty.

Not sure if this should be handled by ray autoscaler?

**Comment by DmitriGekhtman** [comment]
> Not sure if this should be handled by ray autoscaler?

Autoscaler and operator shouldn't keep creating pods in an infinite loop when there are node problems.

**Comment by nvtkaszpir** [comment]
well, I guess autoscaler just sends request to kubernetes api to create pod and waits if replica count is as expected.
If it is not it will try to request additional pods.
The fact that pods die due to node issue because kubernetes schedules them on the broken node should not be a concern of autoscaler.

**Comment by DmitriGekhtman** [comment]
I see where you're coming from, but it seems that the issue is

> a large amount of pods are stuck in pending

not that 

> pods die due to node issue

The expected behavior from the operator/autoscaler system is to observe the count of pending pods and cease creating pods when the count exceeds the user-specified limit.

**Comment by DmitriGekhtman** [comment]
More succinctly, pending pods are supposed to count towards the specified replica count.

**Comment by nvtkaszpir** [comment]
shouldn;t it actually care about pods in running state (which means healthchecks are working), because you can have some pending pods which are pending forever due to the fact they are not possbile to be scheduled on any nodes due to taints/tolerations etc?

**Comment by DmitriGekhtman** [comment]
> shouldn;t it actually care about pods in running state (which means healthchecks are working), because you can have some pending pods which are pending forever due to the fact they are not possbile to be scheduled on any nodes due to taints/tolerations etc?

It's unfortunately in the nature of Kubernetes that you can't know if something is Pending because it needs some time or because it's permanently stuck.

**Comment by nvtkaszpir** [comment]
I think i managed to get that bug as well.
I know that it was not happening with kuberay v0.5.0, but is surely
happening with kuberay on commit f6a172f

**Comment by nvtkaszpir** [comment]
ok my issue was different (autoscaler not scaling down) and looks like it is solved in ray [83179a](https://github.com/ray-project/ray/commit/83179ab1db0929ad02c561a774d6e8868c79def8)

**Comment by kevin85421** [comment]
Hi @peterghaddad, could you please provide more details on how to reproduce this issue? I followed the given instructions, but I haven't been able to observe the issue.

* Gist1: [RayCluster with autoscaling](https://gist.github.com/kevin85421/88db05a767ff134122763dbdbc5c7b5a)
  * 1 * head Pod: 1 CPU
  * 1 * worker Pod: 1 CPU, 1 GPU

```sh
# Step 0: Create a Kubernetes cluster
kind create cluster --image=kindest/node:v1.23.0

# Step 1: Install a KubeRay operator
helm install kuberay-operator kuberay/kuberay-operator --version 0.5.0

# Step 2: Create a RayCluster with autoscaling enabled. The status of the worker Pod
# will be "Pending" because there are no GPUs available in the Kind cluster.
kubectl apply -f Gist1

# Step 3: Log in to the head Pod
export HEAD_POD=$(kubectl get pods --selector=ray.io/node-type=head -o custom-columns=POD:metadata.name --no-headers)
kubectl exec -it $HEAD_POD -- bash

# Step 4: Create a Python file gpu.py in the head Pod

"""
import ray

@ray.remote(num_gpus=1)
def hello_world():
    print("hello world!")

references = [
    hello_world.remote() for _ in range(5)
]

ray.get(references)
"""

# Step 5: Execute the Python script in the head Pod.
python3 gpu.py

# Step 6: gpu.py will request 5 GPUs, so the remaining 4 workers will be created. However, the Kind cluster does not have
# any GPU available, so all 5 workers will be pending.
```

For this issue, I expected that multiple workers would be created and remain in a "Pending" status. However, I haven't observed this behavior. You can see the following screenshot for more details.

<img width="1437" alt="Screen Shot 2023-06-13 at 3 18 20 PM" src="https://github.com/ray-project/kuberay/assets/20109646/b7872242-7c21-416e-b8a0-5ab6f1509e81">

**Comment by kevin85421** [comment]
Hi @peterghaddad, would you mind taking a look at https://github.com/ray-project/kuberay/issues/1108#issuecomment-1590143890? Thanks!

**Comment by peterghaddad** [comment]
Hey @kevin85421 what do you have for max_replicas for the worker type?

Let's assume you have it set to 10, what happens if you have the code spawn 15 worker pods? If there are more pending workers then max_replicas, then I think this will have reproduced the issue.
```
hello_world.remote() for _ in range(15)
```

I appreciate you testing this, and let me know if any additional information will help.

**Comment by kevin85421** [comment]
Hi @peterghaddad, thank you for your reply! 

> what do you have for max_replicas for the worker type?

I used Gist1 mentioned in [this thread](https://github.com/ray-project/kuberay/issues/1108#issuecomment-1590143890). The value of `maxReplica` is 10 ([code](https://gist.github.com/kevin85421/88db05a767ff134122763dbdbc5c7b5a#file-autoscaler-yaml-L103)).

> Let's assume you have it set to 10, what happens if you have the code spawn 15 worker pods? Is pending worker pods > max_replicas?

I updated gpu.py from `hello_world.remote() for _ in range(5)` to `hello_world.remote() for _ in range(15)`. This change will create an additional 9 workers, resulting in a total of 10 workers, matching the value of `maxReplica`. I still cannot reproduce this issue.

```python
import ray

@ray.remote(num_gpus=1)
def hello_world():
    print("hello world!")

references = [
    hello_world.remote() for _ in range(15)
]

ray.get(references)
```



<img width="1435" alt="Screen Shot 2023-06-14 at 5 24 11 PM" src="https://github.com/ray-project/kuberay/assets/20109646/73fed92c-7c5a-42bb-8c46-1a67f8877220">


Q: Which version of KubeRay or Ray are you using? Do you have any reproduction script that I can use to reproduce locally or on EKS/GKE? Thanks!

**Comment by peterghaddad** [comment]
Hi @kevin85421! Thank you for looking into reproducing. I will be away this weekend, but will try and reproduce again on a kind cluster Sunday or Monday. I was using kuberay 0.5.0 and Ray 2.5.0

**Comment by kevin85421** [comment]
Hi @peterghaddad, sorry to bother you. Is there any update on https://github.com/ray-project/kuberay/issues/1108#issuecomment-1594000923? Thanks!

**Comment by kevin85421** [comment]
Hi @peterghaddad, does this issue still happen with KubeRay v0.5.2? Thanks!

**Comment by peterghaddad** [comment]
Hey @kevin85421 had a family emergency and had to leave the country. Still haven't had a chance to test, but will report back and reopen if needed. Thank you

**Comment by kevin85421** [comment]
I'm sorry to hear about it. I hope everything goes well for you and your family. Take care.
