### ISSUE TITLE
[Bug] Please rebuild nightly container

### ISSUE THREAD

**Issue by iconix** [ray-project/kuberay#111]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

The example cluster configs that use `--block` do not work with the current `nightly` operator build. 

Applying e.g., https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.complete.yaml results in an error:
```
Error: Option '--block' does not take a value.
```
and a `CrashLoopBackOff` on the pod.

I believe it is because https://github.com/ray-project/kuberay/pull/77 has not been built into the `nightly` container on Docker Hub. https://github.com/ray-project/kuberay/pull/77 merged on December 1, but the `nightly` container hasn't been pushed since October 16 (https://hub.docker.com/r/kuberay/operator/tags).

### Reproduction script

```
λ kubectl apply -k "github.com/ray-project/kuberay/ray-operator/config/default"
λ kubectl create -f config/samples/ray-cluster.complete.yaml
λ kubectl get pods
NAME                          READY   STATUS             RESTARTS      AGE
raycluster-complete-head-srv2f   0/1     CrashLoopBackOff   7 (95s ago)   12m
λ kubectl logs raycluster-complete-head-srv2f
Error: Option '--block' does not take a value.

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
Hi @iconix Thanks. I will build it and update the image. This process is not built into the CI and that's something we will do soon.

**Comment by iconix** [comment]
@Jeffwan any ETA on the manual build? was hoping this might be a quick task for you but let me know!

**Comment by Jeffwan** [comment]
@iconix sorry for the late response. I update the latest tag now and I am working on a story to push nightly tag for every merge.
