### ISSUE TITLE
[Bug][CI] Add tests to ensure that the `zz_generated.deepcopy.go` is up-to-date.

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1111]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen

When you update the CRD struct in `ray*_types.go` (e.g., `raycluster_types.go`), you should update the CRD YAML files and the generated code by executing `make build`. We have several [consistency checks in CI](https://github.com/ray-project/kuberay/blob/master/ray-operator/DEVELOPMENT.md#consistency-check), but we do not check `zz_generated.deepcopy.go`.

### Reproduction script

https://github.com/ray-project/kuberay/pull/1110/files#r1204973842

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by varungup90** [comment]
@kevin85421 Please re-assign the task and review PR [1127](https://github.com/ray-project/kuberay/pull/1127)
