### ISSUE TITLE
[Feature] Update ray-operator MakeFile to support alternative container engines

### ISSUE THREAD

**Issue by anishasthana** [ray-project/kuberay#1116]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

The existing Makefile at https://github.com/ray-project/kuberay/blob/master/ray-operator/Makefile#L84 has hardcoded references to Docker. Not all users have docker installed. I'm proposing parametrization of the MakeFIle to allow users to pick the container enginer to be used. I've raised a PR similar to this in the past to a different project[1].

[1] https://github.com/kserve/modelmesh-serving/pull/266

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
It makes sense. I start to use podman in my dev machine now and we should make this configurable.

**Comment by kevin85421** [comment]
+1 This makes sense to me.

**Comment by anishasthana** [comment]
@kevin85421 feel free to assign it to me! I'll raise a PR shortly.
