### ISSUE TITLE
[Feature] Documentation how to pin the head node to specific host type. 

### ISSUE THREAD

**Issue by sihanwang41** [ray-project/kuberay#1122]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

No documentation how to set up the head node to a specific host type.

### Use case

i want avoid to have head node to gpu host type.  My workload needs to run on the gpu host, it is a little bit waste of resources to use GPU host as head node.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
https://github.com/ray-project/kuberay/blob/master/docs/guidance/aws-eks-gpu-cluster.md => This doc has the instructions for setting up taints on Kubernetes nodes.
