### ISSUE TITLE
[Poll] Naming convention for RayService Serve config

### ISSUE THREAD

**Issue by zcin** [ray-project/kuberay#1137]
Multi-application support in Ray Serve was officially introduced in Ray 2.4. Thus, we are adding a new field `serveConfigV2` to the RayService spec in addition to the existing `serveConfig` field. This new field will take on the schema matching the Serve multi-application config schema: see the Ray Serve docs for the [guide](https://docs.ray.io/en/latest/serve/multi-app.html) and [schema](https://docs.ray.io/en/latest/serve/api/doc/ray.serve.schema.ServeDeploySchema.html). 
(The existing field `serveConfig` matches the Serve single-application config [schema](https://docs.ray.io/en/latest/serve/api/doc/ray.serve.schema.ServeApplicationSchema.html))

Since we are already defining a new schema for `serveConfigV2`, we are planning to use snake case for `serveConfigV2`. (For context, the existing field `serveConfig` is defined with camel case). The reasons are:
* Ray Serve natively uses snake case. The JSON request sent to the Serve API is in snake case, and Serve configs generated by `serve build` are also snake case by default.
* Since currently `serveConfig` in RayService is defined in camel case, users have to convert Ray Serve configs (snake case) to the camel case accepted by RayService CRs. There have been many issues caused by this back-and-forth converting:
  * https://github.com/ray-project/ray/issues/35741
  * https://github.com/ray-project/ray/issues/32197
* Fields like `runtimeEnv` and `userConfig` require subfields to be snake case anyways (so there already exists some mix and match of snake case and camel case)

Note that the current version of `serveConfig` may be deprecated in future releases of Kuberay, as the Serve single-application config schema will be deprecated in future releases of Ray.

**Comment by kevin85421** [comment]
It seems that there is no opposition to this. Let's proceed with it.
