### ISSUE TITLE
Frequent update to Raycluster headpod's annotation  "ray.io/autoscaler-update-timestamp" causing reconciliation by argocd

### ISSUE THREAD

**Issue by msumitjain** [ray-project/kuberay#1182]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

We are using ArgoCD for managing RayService. ArgoCD is detecting changes in resource for 
1. RayCluster -> `status.lastUpdateTime`
2. Head pod for RayCluster ->  metadata.annotation for `ray.io/autoscaler-update-timestamp`.

The concern is with the frequent reconciliation from ArgoCD and K8s API Server. The expected behaviour is, the reconciliation should only happen when there are actual changes in the resource and not some status. 

<Add more details>
@anshulomar

### Reproduction script

The steps are given below - 

1. Setup a test cluster.
2. Install the Kuberay operator on the cluster in a namespace called namespace-1.
3. Create a repository and add a sample RayService manifests to that repository.
4. Create an app in ArgoCD with the repo having RayService manifest to a different namespace called namespace-2.
5. ArgoCD should create the a bunch of resources and after a few minutes you should start seeing that pulsing animation.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by msumitjain** [comment]
@kevin85421 Could you help with this issue ?

**Comment by kevin85421** [comment]
Related issue: #442

**Comment by kevin85421** [comment]
Open a PR: https://github.com/ray-project/ray/pull/36886

**Comment by kevin85421** [comment]
Update: https://github.com/ray-project/ray/pull/36886 is merged.

**Comment by kevin85421** [comment]
> RayCluster -> status.lastUpdateTime

I have already opened a PR: https://github.com/ray-project/kuberay/pull/1211. The PR will be ready to review today.

**Comment by kevin85421** [comment]
I manually deployed a KubeRay operator using the image `kuberay/operator:nightly` and a RayCluster using `rayproject/ray:nightly`. The head Pod no longer has the annotation `ray.io/autoscaler-update-timestamp`, and as a result, the `status.lastUpdateTime` of the RayCluster will not be updated frequently. Close this issue.

Feel free to let me know if you still observe the issue. Thanks!
