### ISSUE TITLE
[Bug] ray worker stuck in init state

### ISSUE THREAD

**Issue by shadowcollecter** [ray-project/kuberay#1187]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator, Others

### What happened + What you expected to happen

When deploying Kuberay following the instructions in the documentation, the ray-worker remains in the init state and cannot start. The log indicates that the container "ray-worker" within the pod remains in the init state(for over  a hour). I am pretty sure that I have enough resource. However, I was able to successfully install it without using Kuberay (the  version with no autoscaling in the doc).

some information 
Events:
  Type    Reason     Age   From               Message

  Normal  Scheduled  82s   default-scheduler  Successfully assigned kuberay/raycluster-kuberay-worker-workergroup-r7rsn to node0

  Normal  Pulled     81s   kubelet            Container image "busybox:1.28" already present on machine

  Normal  Created    81s   kubelet            Created container init

  Normal  Started    81s   kubelet            Started container init

### Reproduction script

by the document ray version 2.5.1

helm repo add kuberay https://ray-project.github.io/kuberay-helm/ 

helm install kuberay-operator kuberay/kuberay-operator --version 0.5.0

helm install raycluster kuberay/ray-cluster --version 0.5.0

### Anything else

Ubuntu version 22.04 LTS
Kubernetes 1.25

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
What's your cluster domain? Kubernetes's default cluster domain is `cluster.local`.

**Comment by kevin85421** [comment]
For more details on how to change the cluster domain, you can refer to the following link: https://github.com/ray-project/kuberay/blob/master/docs/guidance/FAQ.md. Feel free to let me know if the question remains unresolved.
