### ISSUE TITLE
[Bug] Document on single namespace install should pin to a version instead of use nightly by default

### ISSUE THREAD

**Issue by wjzhou-ep** [ray-project/kuberay#1193]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

https://ray-project.github.io/kuberay/deploy/installation/

For the single namespace installation, it point to the main branch and get the nightly image. 

We should pin the version similar to the Method 2: Kustomize

### Reproduction script

N.A.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
SGTM. Would you mind opening a PR?
