### ISSUE TITLE
[Bug] unknown field serveConfigV2 in io.ray.v1alpha1.RayService.spec

### ISSUE THREAD

**Issue by Rowena2001** [ray-project/kuberay#1194]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I'm trying to add autoscaling for my ray deployments using the autoscaling_config field found in [ray-operator/config/samples/ray-service.autoscaler.yaml](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-service.autoscaler.yaml). 

However, when I try to apply my YAML file to my Kubernetes cluster, I encounter the error:

error: error validating "model_auto_config.yaml": error validating data: ValidationError(RayService.spec): unknown field "serveConfigV2" in io.ray.v1alpha1.RayService.spec; if you choose to ignore these errors, turn validation off with --validate=false

I included a text file of the contents inside my YAML file for reference.

### Reproduction script

[model_auto_config.txt](https://github.com/ray-project/kuberay/files/11886010/model_auto_config.txt)

### Anything else

I've tried using serveConfig (version 1?) and adding an autoscalingConfig field inside my deployment. When I tried applying the YAML file, I received a type error:

error: error validating "model_auto_config.yaml": error validating data: [ValidationError(RayService.spec.serveConfig.deployments[0].autoscalingConfig): invalid type for io.ray.v1alpha1.RayService.spec.serveConfig.deployments.autoscalingConfig: got "map", expected "string", ValidationError(RayService.spec.serveConfig.deployments[1].autoscalingConfig): invalid type for io.ray.v1alpha1.RayService.spec.serveConfig.deployments.autoscalingConfig: got "map", expected "string"]; if you choose to ignore these errors, turn validation off with --validate=false

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
`serveConfigV2` is a new field in the CRD and is only available in the KubeRay nightly image. Would you be interested in trying the nightly KubeRay? It includes numerous improvements in RayService compared to v0.5.0.

**Comment by Rowena2001** [comment]
Yes, I would be interested! How can I try KubeRay nightly?

**Comment by kevin85421** [comment]
> Yes, I would be interested! How can I try KubeRay nightly?

You can try

```sh
# Step0: Clone this repo
# Step1: Move to kuberay/helm-chart/kuberay-operator
helm install kuberay-operator . --set image.repository=kuberay/operator,image.tag=nightly
```

**Comment by Rowena2001** [comment]
Thank you for your help! Would I still use apiVersion: ray.io/v1alpha1 once I have the nightly kuberay image installed?

**Comment by kevin85421** [comment]
> Would I still use apiVersion: ray.io/v1alpha1 once I have the nightly kuberay image installed?

Yes, we have decided not to bump the version at this moment. We will instead bump the version to beta later (maybe the release after v0.6.0) and deprecate `serveConfig`.

**Comment by kevin85421** [comment]
Close this issue. Feel free to add comments on this issue or reach out to us on Slack if you still have questions.

**Comment by aviadshimoni** [comment]
@kevin85421 it worked!
thank you so much. appreciate the quick response 💯

**Comment by abhishekchopde** [comment]
@kevin85421 I am facing this issue too. I did what you suggested. Here are the steps:

1.  Uninstall old `kuberay-operator`
2. Installed the new one with `helm install kuberay-operator . --set image.repository=kuberay/operator,image.tag=nightly` from `kuberay/helm-chart/kuberay-operator` by cloning this repo. [Do i need to checkout to specific branch?]
3. Tried installing rayservice manifest using https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-service.autoscaler.yaml this example.

And it threw me the same error as above:

```
Error from server (BadRequest): error when creating "test_multiapp_rayservice.yaml": RayService in version "v1alpha1" cannot be handled as a RayService: strict decoding error: unknown field "spec.serveConfigV2"
```
`test_multiapp_rayservice.yaml` is same as the `ray-service.autoscaler.yaml`.

For reference, here is my newly installed kuberay-operator description:

```
Name:             kuberay-operator-9945549bf-h7d8m
Namespace:        default
Priority:         0
Service Account:  kuberay-operator
Node:             <server-name>/[172.16.18.200](http://172.16.18.200/)
Start Time:       Tue, 04 Jul 2023 00:05:43 +0530
Labels:           [app.kubernetes.io/component=kuberay-operator](http://app.kubernetes.io/component=kuberay-operator)
                  [app.kubernetes.io/instance=kuberay-operator-new](http://app.kubernetes.io/instance=kuberay-operator-new)
                  [app.kubernetes.io/name=kuberay-operator](http://app.kubernetes.io/name=kuberay-operator)
                  pod-template-hash=9945549bf
Annotations:      [cni.projectcalico.org/containerID](http://cni.projectcalico.org/containerID): fc0f768ab6813790b9c558e7f587345fb29b6e3546b15d8fe5a3e23404df5b66
                  [cni.projectcalico.org/podIP](http://cni.projectcalico.org/podIP): [172.22.112.63/32](http://172.22.112.63/32)
                  [cni.projectcalico.org/podIPs](http://cni.projectcalico.org/podIPs): [172.22.112.63/32](http://172.22.112.63/32)
Status:           Running
IP:               <some-ip>
IPs:

  IP:           <some-ip>

Controlled By:  ReplicaSet/kuberay-operator-9945549bf

Containers:

  kuberay-operator:

    Container ID:  containerd://52dc0dc0908d5a02ac4b0046ce6c68fdeb8ee012399abffa4480155667b2f930

    Image:         kuberay/operator:nightly

    Image ID:  docker.io/kuberay/operator@sha256:6cda8b6ece2425146df2d800c6494f948310310dd8160aa300c01e3f95530378
    Port:          8080/TCP
    Host Port:     0/TCP
    Command:
      /manager
    State:          Running
      Started:      Tue, 04 Jul 2023 00:05:44 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  512Mi
    Requests:
      cpu:        100m
      memory:     512Mi
    Liveness:     http-get http://:http/metrics delay=10s timeout=1s period=5s #success=1 #failure=5
    Readiness:    http-get http://:http/metrics delay=10s timeout=1s period=5s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /var/run/secrets/[kubernetes.io/serviceaccount](http://kubernetes.io/serviceaccount) from kube-api-access-b7vpb (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True

Volumes:
  kube-api-access-b7vpb:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true

QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 [node.kubernetes.io/not-ready:NoExecute](http://node.kubernetes.io/not-ready:NoExecute) op=Exists for 300s

                             [node.kubernetes.io/unreachable:NoExecute](http://node.kubernetes.io/unreachable:NoExecute) op=Exists for 300s

Events:

  Type    Reason     Age    From               Message

  ----    ------     ----   ----               -------

  Normal  Scheduled  5m29s  default-scheduler  Successfully assigned default/kuberay-operator-9945549bf-h7d8m to bd-mum-gpu15

  Normal  Pulled     5m28s  kubelet            Container image "kuberay/operator:nightly" already present on machine

  Normal  Created    5m28s  kubelet            Created container kuberay-operator

  Normal  Started    5m28s  kubelet            Started container kuberay-operator
```

Can you please help debug this? Somehow I feel that CRDs or operator is being taken from older version itself, but my operator fetched `nightly` image only as you can see from the output.
