### ISSUE TITLE
[RayJob] Add testing for `shutdownAfterJobFinishes`

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/kuberay#1200]
The option `shutdownAfterJobFinishes` in the `RayJob` spec is currently not tested in CI.  We should add unit tests and an end-to-end test for this.

**Comment by dizhouwu** [comment]
Is `shutdownAfterJobFinishes` even working right now?

**Comment by architkulkarni** [comment]
@dizhouwu It should be working, but it has only been tested manually so far.

**Comment by dizhouwu** [comment]
@architkulkarni I don't see it working myself - I am using kuberay 0.5.2 with Ray 2.6.1. By the way, I don't see a documentation for the intended behavior - does Failed also count as Finished? What statuses are counted as "Finished"? Thanks

**Comment by dizhouwu** [comment]
Unfortunately I only have a ray cluster on cloud k8s. Set to true for sure. I guess it must be issue on my side IF this is added to the regression test - so I can happily wait for that work is done. Thanks again!
