### ISSUE TITLE
[CI] Install New Agents in Buildkite for KubeRay CI

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/kuberay#1202]
As part of our effort to move KubeRay CI from GitHub Actions to Buildkite due to resource limitations, we need to install new agents in Buildkite. We anticipate requiring larger VM instances (8 cores and 16 GB of RAM) for existing tests.

Tasks:

- [ ] Launch new agents as per instructions provided in the [Buildkite documentation](https://buildkite.com/docs/tutorials/getting-started#install-and-run-your-first-agent).
- [ ] Determine the required number of agents for our use case.

**Comment by kevin85421** [comment]
@architkulkarni Is it OK to close this issue?
