### ISSUE TITLE
[CI] Create New Pipelines in Buildkite

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/kuberay#1204]
To fully transition KubeRay CI from GitHub Actions to Buildkite, we need to create new pipelines in Buildkite.

- [ ] Create new pipelines via [Buildkite Web UI](https://buildkite.com/ray-project).
- [ ] Define .buildkite/pipeline.yml in the KubeRay repository.
- [ ] Upload and use pipeline.yml through "buildkite-agent pipeline upload" on the Steps screen.
- [ ] Determine the required number of pipelines for our use case.

**Comment by kevin85421** [comment]
@architkulkarni Is it OK to close this issue?
