### ISSUE TITLE
[CI] Migrate GitHub Actions Workflows to Buildkite CI

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/kuberay#1205]
The final step in our transition from GitHub Actions to Buildkite involves migrating our workflows. We intend to leave smaller tests on GitHub Actions while moving larger tests to Buildkite.

- [ ] Identify the smaller tests that will continue to run on GitHub Actions.
- [ ] Identify the larger tests to be moved to Buildkite. (e.g. sample YAML e2e tests)
- [ ] Transplant .github/ (GitHub Actions workflows) to .buildkite/pipeline.yml.

**Comment by kevin85421** [comment]
@architkulkarni Is it OK to close this issue?
