### ISSUE TITLE
[Umbrella] KubeRay benchmark plan

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1208]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

* Memory benchmark: Benchmark the memory usage for KubeRay with different numbers of Pods and custom resources. I believe that RayService has a memory leak issue [#1156(comment)](https://github.com/ray-project/kuberay/pull/1156#discussion_r1226087651) at this moment.

* Scalability benchmark: The memory benchmark is one of the important factors for scalability. However, we also need to determine if there are any other scalability bottlenecks in KubeRay. KubeRay should be able to support scalability for at least 95% of users' use cases. We need to understand the scale that we target on.

* Kubernetes API Server: We need to benchmark the number of requests that the KubeRay operator sends to the Kubernetes API Server ([#1062](https://github.com/ray-project/kuberay/pull/1062)).

* Ray Autoscaler: The KubeRay node provider directly fetches information from the Kubernetes API Server instead of using an informer cache. I am unsure whether this approach will cause any scalability issues.

* RayService
  * QPS: We should get a similar result as this [benchmark](https://docs.ray.io/en/latest/serve/advanced-guides/performance.html#performance-and-known-benchmarks).
  * High availability / Zero downtime: Maybe we should have chaos testing for it.
    * How many queries will be lost in the chaos environment?
  * Fault tolerance: Ray Serve seems not to be well-supported by GCS fault tolerance ([#1058](https://github.com/ray-project/kuberay/issues/1058)).

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by anishasthana** [comment]
@kpouget This may be interesting to you as well.

**Comment by tedhtchang** [comment]
>QPS: We should get a similar result as this [benchmark](https://docs.ray.io/en/latest/serve/performance.html#performance-and-known-benchmarks).

@kevin85421 The benchmark link returns 404 Not Found

**Comment by kevin85421** [comment]
Memory & scalability benchmarks: #1324.

**Comment by Jeffwan** [comment]
We need to measure the scalability as one of the criterion in our product. Benchmark on the reconcile metrics need to be measured for scalability and I will try to come up a plan if I get some bandwidth this week.

**Comment by kevin85421** [comment]
Close this one, and use #2069 instead.
