### ISSUE TITLE
[Bug] fix RayActorOptionSpec.items.spec.serveConfig.deployments.rayActorOptions.memory int32 data type

### ISSUE THREAD

**Issue by TsykunovDmitriy** [ray-project/kuberay#1212]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

1. Amount of serve deployment's memory expected in bytes. Data type for memory expected in int32 for RayActorOptionSpec.items.spec.serveConfig.deployments.rayActorOptions.memory ([link](https://github.com/ray-project/kuberay/blob/master/ray-operator/apis/ray/v1alpha1/rayservice_types.go#L90) to source code). In my case, I cannot specify amount of memory equal to 3.5Gb (logs from kuberay-operator in 3 section).
2. Expected behavior - kuberay-operator supports uint64 data type (or int64).
3. Logs from kuberay-operator:
```
W0628 20:13:46.926544       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: failed to list *v1alpha1.RayService: json: cannot unmarshal number 3758096384 into Go struct field RayActorOptionSpec.items.spec.serveConfig.deployments.rayActorOptions.memory of type int32
E0628 20:13:46.926578       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1alpha1.RayService: failed to list *v1alpha1.RayService: json: cannot unmarshal number 3758096384 into Go struct field RayActorOptionSpec.items.spec.serveConfig.deployments.rayActorOptions.memory of type int32
```

### Reproduction script

Just create random serve deployment with memory requests over than 2Gb. In my case next deployment raise error from above log.
```{python}
from ray import serve

@serve.deployment(
    ray_actor_options={"memory": 3.5 * 1024 * 1024 * 1024}
)
class DummyApp:
    pass

app = DummyApp.bind()
```

### Anything else

[Thread](https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1687983560918979) in ray slack.
Ping: @kevin85421

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
I found something interesting: the `memory` field in the Ray Serve schema is specified as type `float`, and it is measured in `bytes`. Let me figure this out.

https://sourcegraph.com/github.com/ray-project/ray@ac2230f/-/blob/python/ray/serve/schema.py?L43-L49

**Comment by kevin85421** [comment]
[Update]

> I found something interesting: the memory field in the Ray Serve schema is specified as type float, and it is measured in bytes.

The `memory` field is used to specify logical memory rather than physical memory. That is why it is of type float. It is very confusing.

I have already opened a PR #1120 to fix this issue. However, if you are comfortable with the nightly KubeRay, I will strongly recommend you use `serveConfigV2` rather than `serveConfig`. `serveConfig` will be deprecated in the future.
