### ISSUE TITLE
[Bug][Autoscaler] KubeRay autoscaler downscales the Ray cluster while the node is running

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1238]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

https://github.com/ray-project/ray/issues/34019

### Reproduction script

https://github.com/ray-project/ray/issues/34019

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by wjzhou-ep** [comment]
just a FYI,

that v5.0.2 bug maybe the same root case as this: (pod double killed, with half of them heathy node)
https://github.com/ray-project/kuberay/issues/1192

**Comment by kevin85421** [comment]
# Update

At first, [our assumption](https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1680204618061789?thread_ts=1680138897.065469&cid=C01DLHZHRBJ) for this issue is:

* Case 1:
   * Autoscaler sends a request to GCS to terminate the raylet process on the worker Pod.
   * The worker Pod restarts if the Pod’s `restartPolicy` is not `Never`. It is still the same Pod after it restarts, but the Pod IP will be different. Therefore, for Ray, it is considered a different node.
   * Ray schedules tasks/actors on the “new” Ray node.
   * KubeRay deletes the Pod.
* Case 2: KubeRay deletes the Pod before Autoscaler drains the Ray node.

## Case 1 discussion

Case 1 is a more reasonable reason for me. However, when I tried to reproduce it, I found the following facts:

* The `restartPolicy` will not be triggered when the `raylet` is killed. That is, the Pod's status will still be "Running". The `restartPolicy` will be triggered only when the `ray start` process is killed.
* The other possibility to trigger the `restartPolicy` is setting healthiness/readiness probes. However, the user does not set the values.

Hence, Case 1 is almost impossible.

## Case 2 discussion

Case 2 seems to be impossible because Autoscaler will only send the patch to update the RayCluster CR after it drains the Ray node (i.e. [kill the `raylet` process](https://github.com/ray-project/ray/blob/ef1a490896d24ab68f12d54e2269a1eb000868a3/python/ray/autoscaler/_private/autoscaler.py#L615)). cc @rickyyx @DmitriGekhtman to confirm.

## Some edge cases that I can think of

* Case 3: Similar to Case 1, the only difference is that certain accidents occur, leading to the termination of the ray start process. Subsequently, the Pod restarts, and Ray schedules new tasks/actors before being terminated by KubeRay.

* Case 4: A Pod crashes accidentally and restarts. We assume that there is a Pod status transition (e.g. `Running` -> `Failed` -> `Running`) between the accident and restart (This is my assumption. I have not observed this behavior.).
There's a slim chance that KubeRay could catch the `Failed` status and, as a result, create a new Pod. However, when the original Pod returns to a `Running` status, this will result in one more Pod than expected. To rectify this, KubeRay will randomly delete one of the Pods.

In my view, both Case 3 and Case 4 are highly unlikely events. My current thoughts are:

(1) Users can set their `restartPolicy` to `Never` if they enable Autoscaler in their RayClusters.
(2) In a RayCluster with autoscaling enabled, we will forgo the random Pod deletions and allow the Autoscaler to make all Pod deletion decisions.

**Comment by rickyyx** [comment]
Hmm so if Case 1 never triggers, then `restartPolicy` will not help? 

Seems we still don't know the root cause? 

> the restartPolicy will be triggered only when the ray start process is killed.

Wdym by this? Does kuberay do `ray start --block`?

**Comment by kevin85421** [comment]
> Hmm so if Case 1 never triggers, then restartPolicy will not help?

Setting `restartPolicy` to `Never` can still be beneficial for Case 3, although I anticipate that Case 3 is a rare occurrence.

> Seems we still don't know the root cause?

Yes, the information provided by users isn't sufficient to determine whether this issue is related to Autoscaler or KubeRay. As a result, I will draft a PR to ensure Autoscaler is the sole decision-maker for Pod deletion, and disable KubeRay's random Pod deletion mechanism, which is unfavorable from any perspective and ask users to set the `restartPolicy` to `Never`. If we can still observe the issue, we may need to check whether it is related to Autoscaler or Ray scheduler or not.

> Wdym by this?

<img width="1440" alt="Screen Shot 2023-07-19 at 5 03 36 PM" src="https://github.com/ray-project/kuberay/assets/20109646/94cab298-7dd2-4336-ab68-5bdf33be521e">


> Does kuberay do ray start --block?

Yes. The following screenshot is the command and args of a worker's Ray container.

<img width="1440" alt="Screen Shot 2023-07-19 at 5 00 45 PM" src="https://github.com/ray-project/kuberay/assets/20109646/9d171336-76fd-4a18-b8a2-155486405e33">

**Comment by rickyyx** [comment]
> I will draft a PR to ensure Autoscaler is the sole decision-maker for Pod deletion, and disable KubeRay's random Pod deletion mechanism, which is unfavorable from any perspective and ask users to set the restartPolicy to Never. If we can still observe the issue, we may need to check whether it is related to Autoscaler or Ray scheduler or not.

This sounds good to me!

**Comment by kevin85421** [comment]
Close this issue because there have been no complaints about it in the last 5 months.
