### ISSUE TITLE
Move the samples directory to the root directory

### ISSUE THREAD

**Issue by pingsutw** [ray-project/kuberay#1240]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

It's hard to find the rayJob / rayCluster examples. Could we move https://github.com/ray-project/kuberay/tree/master/ray-operator/config/samples to the root directory (`kuberay/`)?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
This may be difficult because many different sources link to that location. Close this issue.
