### ISSUE TITLE
[RayService][Benchmark] High availability / Zero downtime 

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1245]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

* High availability / Zero downtime 
  * How many queries will be lost if the head Pod is killed?
  * How many queries will be lost if zero-downtime upgrade is performed?

### Related issues

#1208 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sihanwang41** [comment]
Zero down time: 0 request failures.
Chaos tests: matching the Anyscale service Success Rate.
