### ISSUE TITLE
[Bug] "RuntimeError: Client Ray installation incompatible with server: client is 2022-12-06, server is 2023-06-27"

### ISSUE THREAD

**Issue by chc-celonis** [ray-project/kuberay#1265]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

Note: In this [documentation](https://ray-project.github.io/kuberay/troubleshooting/), this problem is mentioned. The solution is "In above cases, you will need to check if the client ray version is compatible with the images version in the ray cluster's configuration." However, I'm not able to solve the issue. Please see the description below.

### KubeRay Component

Others

### What happened + What you expected to happen

I am trying to connect to a ray cluster from a pod in the same cluster.

However, the default ray cluster is on Python 3.7 and ray 2.3.0.
My client pod, on the other hand, uses Python 3.9 and ray 2.5.1 (My client application requires the Python version to be above 3.9)
I tried to deploy a ray cluster using a different image, but I couldn't manage to find a [Ray image](https://hub.docker.com/r/rayproject/ray/) that is compatible with Python 3.9 and ray 2.5.1.
Two problems I had:
- There are too many images to choose from. It is not clear which image uses Python 3.9 and ray 2.5.1.
- Image pull failed when trying to pull older images.

Could you please help me with this? Thank you so much!

### Reproduction script

To deploy the ray cluster, I followed the instructions on the [quickstart](https://docs.ray.io/en/latest/cluster/kubernetes/getting-started.html#kuberay-quickstart) documentation by executing the following commands:
```
! helm install raycluster kuberay/ray-cluster --version 0.5.0
! helm repo add kuberay https://ray-project.github.io/kuberay-helm/ 
! helm install kuberay-operator kuberay/kuberay-operator --version 0.5.0 
! helm install raycluster kuberay/ray-cluster --version 0.5.0 
```

I also tried 
`
helm install raycluster kuberay/ray-cluster --version 0.5.1 --set image.tag=6a8d0f-py39-cu117
`

In the client pod:
```
#Python 3.9
import ray
ray.init(address="ray://<IP_HEAD_POD>:10001")
```

However, I got this error when trying to connect to the ray cluster. 
"RuntimeError: Client Ray installation incompatible with server: client is 2022-12-06, server is 2023-06-27".

**Comment by kevin85421** [comment]
Hi, Ray client is currently not actively maintained by the Ray community. I strongly recommend you using `ray job submit` instead.

**Comment by chc-celonis** [comment]
Are you saying the Python SDK is not actively maintained? From the [documentation](https://docs.ray.io/en/latest/cluster/running-applications/job-submission/ray-client.html), it seems to be actively maintained though. 
We need to use the @ray.remote decorator for our project.

**Comment by chc-celonis** [comment]
I tried 
`ray job submit -- python script.py ` , but got the following error:
ERROR utils.py:1403 -- Internal KV Get failed

**Comment by Tongyuang** [comment]
Same question. Has this been solved?

**Comment by chris-aeviator** [comment]
what I find **really** confusing is that the error doesnt output the version but a date, which itself does not have a release on github nor PyPI

**Comment by kevin85421** [comment]
Hi @Tongyuang @chris-aeviator, as I mentioned https://github.com/ray-project/kuberay/issues/1265#issuecomment-1646165782, Ray client is not actively maintained by the Ray community. Please use `ray job submit` instead. Thanks!

**Comment by chris-aeviator** [comment]
Ray submit is not at all a replacement for the ray client. How can one utilize ray inside a running python job (e.g. in spark) in a way similar to how the client works with @remote

**Comment by kevin85421** [comment]
@chris-aeviator If you have any related feedback about the Ray client and `ray job submit`, you can open an issue in the Ray repository. Thanks!
