### ISSUE TITLE
[Feature] [RayJob] Support `entrypoint_num_cpus`, `gpus`, `resources` arguments

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/kuberay#1266]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

https://docs.ray.io/en/latest/cluster/running-applications/job-submission/sdk.html#specifying-cpu-and-gpu-resources

The Ray Job API supports specifying resources, but these options are not exposed as fields in the KubeRay RayJob spec.  We should add them.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by shubhscoder** [comment]
Apolgies for the delay, I was stuck with some unforseen circumstances! I have started working on this issue and raised a PR (WIP) right now. I expect to complete it today EOD. Thanks for all the help!
