### ISSUE TITLE
[Feature] Kuberay operator custom labels

### ISSUE THREAD

**Issue by mariusp** [ray-project/kuberay#1275]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Hi, 

  Our custom K8S cluster requires certain labels & annotations on pods.
This PR (https://github.com/ray-project/kuberay/pull/1276) should add the required attributes.

Thank you,
Marius.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Close by #1276
