### ISSUE TITLE
Allow E2E tests to run with arbitrary Kubernetes cluster

### ISSUE THREAD

**Issue by jiripetrlik** [ray-project/kuberay#1284]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently E2E tests run only with Kind cluster. The goal of this issue is to make these tests more configurable and allow it to run with any Kubernetes cluster.

### Use case

It will allow to run E2E tests on various kinds of clusters like Minikube, Openshift or any other Kubernetes distribution.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jiripetrlik** [comment]
@kevin85421 
Hello can you please check this issue if it makes sense to you? Can you please assign it to me?

**Comment by kevin85421** [comment]
Great! It makes sense to me.
