### ISSUE TITLE
[Bug] Incorrect payload doc for creating ray jobs in apiserver

### ISSUE THREAD

**Issue by js8544** [ray-project/kuberay#1290]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

apiserver

### What happened + What you expected to happen

https://github.com/ray-project/kuberay/tree/master/apiserver#create-ray-job-in-a-given-namespace
https://ray-project.github.io/kuberay/components/apiserver/#create-ray-job-in-a-given-namespace

I believe the documented payload for creating ray jobs is actually the response for getting ray jobs.

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @blublinsky @anishasthana

**Comment by z103cb** [comment]
@kevin85421 can you also assign this ticket to me also ?
