### ISSUE TITLE
[Feature] Allow RayCluster Helm chart to specify different images for different worker groups

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1291]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1690936864376519

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @darren221 are you interested in this issue?

**Comment by Darren221** [comment]
Yes sure!

**Comment by kevin85421** [comment]
Same as #200
