### ISSUE TITLE
[Feature] Allow setting the RayClusterName in the job specification to have determinitic service head

### ISSUE THREAD

**Issue by mmourafiq** [ray-project/kuberay#1294]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently in order to expose the service to the end user, we need to look for the service name which contains a random number.

For instance of the user has already a unique RayJob: `job-22f1d24aff9a4c7fbe5ab9707decbcb0` the cluster name would something like this `job-22f1d24aff9a4c7fbe5ab9707decbcb0-raycluster-7ct2d` and subsequently the service head would be `22ff9a4c7fbe5ab9707decbcb0-raycluster-7ct2d-head-svc`.

It would be nice to allow the user to set the value and only generate them if not specified.

### Use case

I understand the logic to prevent crashing the creation of the cluster, unfortunately this make using the operator very hard.

I think the specification should allow setting the RayClusterName similar to the JobId to allow building on top of this operator.

**Note**: I already tried to set the name of the service and head via `metadata.name` unfortunately some env vars are auto generated and the ray params and using the env var to resolve the service name.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @architkulkarni

**Comment by mmourafiq** [comment]
@architkulkarni Happy to make a PR. 
I will start with changes that I can test on a local cluster and then we can discuss in case I miss anything after opening a PR draft.

**Comment by architkulkarni** [comment]
@mmourafiq that sounds great, thanks for the contribution!
