### ISSUE TITLE
[Feature] KubeRay API Server + Prometheus metrics documentation

### ISSUE THREAD

**Issue by z103cb** [ray-project/kuberay#1311]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

As user of the API Server I would like to know how to setup the KubeRay API Server and Prometheus integration so that the metrics already exposed by the service can be used to monitor the KubeRay API Server.

### Use case

KubeRay API Server seems to have a lot of potential in allowing users to create and run Kuberay clusters and jobs, and having the necessary documentation to properly monitor the service in a production settings is a feature that would be beneficials to all of the users.

### Related issues

None.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by blublinsky** [comment]
@kevin85421 please assign this to me
