### ISSUE TITLE
[apiserver] Method Not Allowed on /apis/v1alpha2/namespaces/ray/jobs

### ISSUE THREAD

**Issue by 23ewrdtf** [ray-project/kuberay#1316]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

apiserver

### What happened + What you expected to happen

I'm following this guide to create RayJob: https://ray-project.github.io/kuberay/components/apiserver/#create-ray-job-in-a-given-namespace

It doesn't matter if I provide JSON or not. The error is the same.

```
curl -X POST kuberay-apiserver-service.ray.svc.cluster.local:8888/apis/v1alpha2/namespaces/ray/jobs
{"code":12, "message":"Method Not Allowed"}
```

The correct endpoint is: `/apis/v1alpha2/jobs`

```
curl -X POST 'kuberay-apiserver-service.ray.svc.cluster.local:8888/apis/v1alpha2/jobs'
{"code":3, "message":"Namespace is empty. Please specify a valid value.: Validate job request failed.: Invalid input error: Namespace is empty. Please specify a valid value."}
```

### Reproduction script

```
curl -X POST kuberay-apiserver-service.ray.svc.cluster.local:8888/apis/v1alpha2/namespaces/ray/jobs
{"code":12, "message":"Method Not Allowed"}
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by z103cb** [comment]
@kevin85421 we should probably close this ticket as the api was changed by #1447. 
@23ewrdtf you might want to retest, with the latest nightly build.
