### ISSUE TITLE
ForcedClusterUpgrade feature do not work as expected?

### ISSUE THREAD

**Issue by oshep** [ray-project/kuberay#1317]
Hi folks!
I'm going to upgrade the RayCluster.
I found that in order to update RayHead pod by rayoperator we should specify --forced-cluster-upgrade arg in ray-operator manager.
Now it become try to update RayHead pod but it stuck in ininfinite reconcile loop, because the head pod contains several containers [ray-head, autoscaler].
the next line of code return true every time when we try to compare autoscaler container, because this container not listed in HeadGroupSpec.Template.Spec.Containers. autoscaler container generated by autoscaler options by RayCluster.
https://github.com/ray-project/kuberay/blob/197fcc225a5507d944fee270ffe671f8d9b9d8ce/ray-operator/controllers/ray/utils/util.go#L395
Since the number of containers in template and actual pod will be allways different it lead to infinite loop delete head pod -> create new -> compare -> delete head pod.
Is it a bug or such upgrade operation should be covered in some other way?
What workaround can i use?
Thanks in advance!

**Comment by kevin85421** [comment]
Thank you for reporting this issue! I will recommend you not use `ForcedClusterUpgrade`. This feature is totally maintained by the Ray maintainers and is fully maintained by the community. The Ray does not natively support rolling upgrades, and it must have a lot of friction between Ray and `ForcedClusterUpgrade`.

If you require no downtime in your cluster, consider checking out RayService, which supports zero-downtime upgrades for serving, and RayJob for other workloads.

**Comment by kevin85421** [comment]
Deprecate ForcedClusterUpgrade. We should use `suspend` instead.

https://github.com/ray-project/kuberay/pull/2075
