### ISSUE TITLE
[Bug] Forced-cluster-upgrade argument flag is not working as expected, causing in endless loop.

### ISSUE THREAD

**Issue by sip-aravind-g** [ray-project/kuberay#1318]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Hello Team,

while planning to update the kuberay and Ray Cluster version into 2.6.1, I have investigated and found the following information "--forced-cluster-upgrade". 

To update ray head node the kuberay-operator we can specify the **--forced-cluster-upgrade** arg in kuberay-operator deployment templates. 

After update now we became to trigger from the operator to update the ray head node, but it stuck in infinite loop, its keep on terminating and trying to recreate the pods.

could you please elaborate the right approach so that I can follow the guidelines, and upgrade the cluster.

### Reproduction script

if you visit the following path and add "- --forced-cluster-upgrade" as an argument, we are facing above mentioned issue. 

**File path:** 
kuberay-operator/templates/deployment.yaml

### Anything else

NOTE:: could you please elaborate the right approach so that I can follow the guidelines, and upgrade the cluster.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Thank you for reporting this issue! I will recommend you not use `ForcedClusterUpgrade`. This feature is totally maintained by the Ray maintainers and is fully maintained by the community. The Ray does not natively support rolling upgrades, and it must have a lot of friction between Ray and `ForcedClusterUpgrade`.

If you require no downtime in your cluster, consider checking out RayService, which supports zero-downtime upgrades for serving, and RayJob for other workloads.
