### ISSUE TITLE
Update MCAD/CodeFlare documentation to improve usability

### ISSUE THREAD

**Issue by anishasthana** [ray-project/kuberay#1327]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

The MCAD documentation for usage alongside KubeRay[1] is quite old and hard to follow. We should update this document to make it easier to follow and bring it up to date with the latest in the CodeFlare ecosystem.

[1] https://github.com/ray-project/kuberay/blob/master/docs/guidance/kuberay-with-MCAD.md

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by anishasthana** [comment]
cc @kevin85421 can you assign this to me?

**Comment by tedhtchang** [comment]
@anishasthana Could you also take a look this [comment](https://github.com/project-codeflare/multi-cluster-app-dispatcher/pull/298#issuecomment-1490863280) to see if it can be addressed here.
