### ISSUE TITLE
Update doc / base image for Go 1.19

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1329]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

* https://github.com/ray-project/kuberay/blob/master/apiserver/DEVELOPMENT.md => The requirement of this doc is still Go 1.17. We should update it to Go 1.19.

* Some Dockerfiles, as seen in this [example](https://github.com/ray-project/kuberay/blob/master/proto/Dockerfile#L2C2-L2C33), are still using `golang:X.Y.Z`. It would be better for us to use UBI instead. Refer to #1213 for more details.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @tedhtchang are you interested in this issue? Thx!

**Comment by tedhtchang** [comment]
@kevin85421 please assign to me.
