### ISSUE TITLE
[Feature] Libraries versions

### ISSUE THREAD

**Issue by blublinsky** [ray-project/kuberay#1337]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Although the Go version was updated - many thanks to @kevin85421, it is still using quite old libraries, some of which rely on the older Go versions, for example, the volcano library is quite old -`volcano.sh/apis v1.6.0-alpha.0.0.20221012070524-685db38b4fae` and uses go 1.16. As a result, although `go.mod` specifies GO 1.19, usage of this library downgrades the compiler to 1.16. The current version is 1.17
Another set of libraries is:
```
	k8s.io/api v0.23.0
	k8s.io/apiextensions-apiserver v0.23.0
	k8s.io/apimachinery v0.23.0
	k8s.io/apiserver v0.23.0
	k8s.io/client-go v0.23.0
	k8s.io/code-generator v0.23.0
```
The current version is 0.27
Finally it is using `sigs.k8s.io/controller-runtime v0.11.1` while the current version is 0.15.1

Unfortunately, all of these upgrades are the breaking ones. 

### Use case

It is to do upgrades - one at a time starting from Volcano, then APIs, etc, and finally controller runtime

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
@astefanutti will take this issue.

**Comment by astefanutti** [comment]
@kevin85421 could you please assign this to me?
