### ISSUE TITLE
[Feature] Add CLI support for Kuberay

### ISSUE THREAD

**Issue by wolfsniper2388** [ray-project/kuberay#134]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Command Line Interface (CLI) support is desired to be added to Kuberay as it provides users with ability to interact with ray clusters in Kubernetes through command line. 

### Use case

 - Users can manage kuberay resources (cluster, compute templates etc) through command line.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
Thanks for @wolfsniper2388's help on the KubeRay CLI! Since the initial version is working, let's close this PR.
