### ISSUE TITLE
[Apiserver] Kuberay apiserver security 

### ISSUE THREAD

**Issue by tedhtchang** [ray-project/kuberay#1376]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently the API cluster URL is wide open. We do need security on the access API server access.

For more detail please look at the apiserver improvement [doc](https://docs.google.com/document/d/1OmffquncLh1V8K5ZJ2M8OD0YD8gBBhJoUVKozUWS9us/edit)
See or comment on the [proposed implementation](https://docs.google.com/document/d/1niF4qaZyudclWouFC7Qg-sdZNeY1P_NqexGfmgGeDBo/edit). 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by tedhtchang** [comment]
@blublinsky @richardsliu @z103cb @anishasthana

**Comment by blublinsky** [comment]
It will make sense to define an overall security approach that will cover both API server and Ray cluster Ingress.
The options on the table are to either use service mesh, for example, Istio or DAPR for this, but this seems to be rather heavy and introduces dependency on a rather large additional software
An alternative is to use the Authorization sidecar for accessing both API server and Ray cluster itself. This approach is extremely flexible and allow users to plug sidecar implementation, that adheres to their security requirements, which can differ significantly across multiple organizations.
One of the options is to use a community https://github.com/oauth2-proxy/oauth2-proxy. If this does not work, an organization can roll out its own - this project https://github.com/blublinsky/auth-reverse-proxy shows some of the options.
One thing to consider is that although most APIs are used programmatically, some of them, for example, Ray dashboard are accessed via a browser. This means that security implementation should be applicable for both use cases. 
As an example, oauth2-proxy requires explicit login using a specialized screen, which makes it difficult to use it in the APIs. On another hand, reverse proxy requiring a specific security header will be hard to use in the browser, and will require browser extensions https://kishorsharma69.wordpress.com/2022/05/20/adding-request-headers-in-browser/ to use it
