### ISSUE TITLE
[Bug] workers failed to connect to head node

### ISSUE THREAD

**Issue by asm582** [ray-project/kuberay#138]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I am trying to run command mentioned in documentation [here](https://github.com/ray-project/kuberay/tree/master/ray-operator).

The raycluster has been started but workers are unable to connect to ray head node:

```
[asmalvan@learn-ray-2 ray-operator]$ kubectl get rayclusters
NAME                       AGE
raycluster-heterogeneous   42s
(base) [asmalvan@learn-ray-2 ray-operator]$ kubectl get pods
NAME                                                 READY   STATUS    RESTARTS   AGE
raycluster-heterogeneous-head-m7qlk                  1/1     Running   0          50s
raycluster-heterogeneous-worker-medium-group-k92qt   1/1     Running   0          50s
raycluster-heterogeneous-worker-small-group-47gmf    1/1     Running   0          50s
raycluster-heterogeneous-worker-small-group-58lhs    1/1     Running   0          50s
raycluster-heterogeneous-worker-small-group-z5726    1/1     Running   0          50s
(base) [asmalvan@learn-ray-2 ray-operator]$ kubectl get services
NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                       AGE
kubernetes                          ClusterIP   10.96.0.1        <none>        443/TCP                       28h
raycluster-heterogeneous-head-svc   ClusterIP   10.101.194.233   <none>        6379/TCP,8265/TCP,10001/TCP   58s
(base) [asmalvan@learn-ray-2 ray-operator]$ kubectl logs raycluster-heterogeneous-head-m7qlk 
2022-01-26 09:01:10,683 INFO services.py:1272 -- View the Ray dashboard at http://172.17.0.4:8265
(base) [asmalvan@learn-ray-2 ray-operator]$ kubectl logs raycluster-heterogeneous-head-m7qlk 
2022-01-26 09:01:10,683 INFO services.py:1272 -- View the Ray dashboard at http://172.17.0.4:8265
(base) [asmalvan@learn-ray-2 ray-operator]$ kubectl logs raycluster-heterogeneous-worker-small-group-47gmf
[2022-01-26 09:01:11,820 W 8 8] global_state_accessor.cc:427: Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
```
minikube was started using the command:

`
 minikube start --cpus 16 --memory 32768
`

Can you please suggest any steps on how to get the sample deployment in the documentation running?

### Reproduction script

- Start minikube using command `minikube start --cpus 16 --memory 32768`
- Follow documentation mentioned [here](https://github.com/ray-project/kuberay/tree/master/ray-operator#deploy-the-operator) , please skip delete operator step

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
@asm582 Thanks for reporting the issue.  could you describe the worker pod and we can see your configurations? BTW, I would suggest you to update title to clearly describe the problem. Seems ray-operator  works fine on your side but the worker are not up.

**Comment by Jeffwan** [comment]
Could you do something like below to see if all nodes joined the cluster. I think the logs might be misleading and they should be already ready. 

`kubectl port-forward svc/raycluster-heterogeneous-head-svc 8265:8265`


I didn't use minikube but docker for desktop. The example works fine for me
![image](https://user-images.githubusercontent.com/4739316/151304261-a8ebd3d7-5ca2-4814-9727-d75c83550547.png)

**Comment by asm582** [comment]
Thanks, @Jeffwan I have changed the issue description, let me know if you think this is apt.

Please see the screenshot below, I can see the workers:
<img width="1628" alt="Screen Shot 2022-01-27 at 3 34 29 AM" src="https://user-images.githubusercontent.com/5898557/151322392-bdadfb35-e323-4bd8-aad4-b9e85eee7fea.png">



- Can you help in understanding why the head node has 100% CPU utilization?
- I think a test program is supposed to be running as defined in the config map but I am not sure if it ran on any of the worker nodes as there are no raylet logs, is that assumption correct?

**Comment by asm582** [comment]
FYI, Sharing a snippet of my log file, should we reduce the logging level on the head node, maybe we are logging status every 5 seconds which is consuming a lot of CPU?

<img width="935" alt="Screen Shot 2022-01-27 at 3 55 33 AM" src="https://user-images.githubusercontent.com/5898557/151325500-6622a2d2-501f-4fde-9359-b71c3c9ed2b2.png">

**Comment by Jeffwan** [comment]
> Can you help in understanding why the head node has 100% CPU utilization?

since head node runs monitor process and gcs etc, the usage is a little bit high. there's only 0.6 cpu allocated there. Seems your resource allocation is different from what I expected.  can you help describe one worker pod spec and share with us? 


> I think a test program is supposed to be running as defined in the config map but I am not sure if it ran on any of the worker nodes as there are no raylet logs, is that assumption correct?

If you use exact same one as this, I would say the code is not running. We remove startup entrypoint since we may deprecate this way and use job submission instead later. 

https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.heterogeneous.yaml

You can `kubectl exec -it headpod bash` and run this code snippet manually 

https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/config-map-ray-code.yaml

**Comment by Jeffwan** [comment]
> FYI, Sharing a snippet of my log file, should we reduce the logging level on the head node, maybe we are logging status every 5 seconds which is consuming a lot of CPU?

yeah, I think the major reason is monitor process keep running periodically which consumes CPU.  Using a large template would be helpful for head node

**Comment by asm582** [comment]
Closing this issue
