### ISSUE TITLE
[Bug] Missing Labels and Annotation on Kubernetes Job

### ISSUE THREAD

**Issue by LeHyperion** [ray-project/kuberay#1384]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

## Description:
I'm using Flyte to manage my workflows, which include Ray tasks that run on a Kubernetes cluster. I've set labels and annotations within a Flyte PodTemplate, but I noticed that these are not applied to the Kubernetes Job and Pods that are managed by Ray Cluster. The labels can be applied to the Ray head and worker pods, but they do not propagate to the Kubernetes Job or Pods.

## Root Cause:
Upon investigating, I found that within the createNewK8sJob function in rayjob_controller.go, both labels and annotations are not set in the ObjectMeta object.

Relevant Code Section: [rayjob_controller.go L381-L382](https://github.com/ray-project/kuberay/blob/cc2e144ca6446fcd38cff66b34be572380148b56/ray-operator/controllers/ray/rayjob_controller.go#L381-L382)

## Expected Behavior:
Labels and annotations set in the Flyte PodTemplate should be applied to the Kubernetes Job and Pods managed by Ray Cluster.

## Actual Behavior:
Labels and annotations are missing in the Kubernetes Job and Pods managed by Ray Cluster.

## Environment:
KubeRay version: 0.6.0
Flyte version: 1.9.1

## Steps to Reproduce:

- Create a Ray job custom resource.
- Observe the missing labels and annotations from the pod that is controlled by the Kubernetes Job (which is in turn controlled by RayCluster).

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by LeHyperion** [comment]
Hi @kevin85421, I'd like to highlight the issue linked below and offer my assistance in resolving it. I could use some guidance from the Ray team to proceed effectively.

On a related note, I'm currently unable to access the Ray Slack workspace. It seems it's restricted to Anyscale and Berkeley members.

Here's the GitHub issue for reference: [GitHub Issue Link](https://github.com/ray-project/kuberay/issues/1059)

Thank you!

**Comment by kevin85421** [comment]
> On a related note, I'm currently unable to access the Ray Slack workspace. It seems it's restricted to Anyscale and Berkeley members.

Let me check with my colleagues.

**Comment by LeHyperion** [comment]
Hi, @kevin85421 could we get assistance from the Ray team regarding the missing labels and annotation issue mentioned? We're eager to contribute and provide a PR, but some guidance would be invaluable. Proper labelling is essential for us to operate KubeRay in production in our organisation, as Kyverno, our K8 policy engine, mandates it. Your team's insights would be greatly appreciated. Thank you! :pray:

**Comment by kevin85421** [comment]
Does https://github.com/ray-project/kuberay/pull/1399#issuecomment-1709311405 make sense to you?

**Comment by metasyn** [comment]
I think this is still an issue - the comment in #1399 only affects the job submitter, not the actual head pod or worker pod. In particular, if you set annotations in the https://ray-project.github.io/kuberay/reference/api/#headgroupspec_1 template field, it does not get passed to the resulting pod's creation. Same thing for the https://ray-project.github.io/kuberay/reference/api/#workergroupspec_1

**Comment by metasyn** [comment]
@LeHyperion did you end up figuring out a work around?
