### ISSUE TITLE
[Bug] Alive worker nodes prevent faulty head node failure recovery

### ISSUE THREAD

**Issue by RuofanKong** [ray-project/kuberay#139]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

By using Kubernetes Ray with Ray Operator, there could be the case that the head node runs into the faulty state and needs a restart with the failure recovery. However, the behavior today is, the head node restarts while the worker nodes do not as they're healthy. The result is, once the head node restarted, the old worker nodes are alive that can't be used any more, while it also prevents new worker nodes to be launched. The expected behavior is, all worker nodes need to be restarted along with the head node by doing the failure recovery.r

### Reproduction script

```
import os
import random
import time

import ray


@ray.remote
class Worker:
    """
    Runs on the head node.
    """
    def sample(self) -> float:
        """
        Mock the way that each worker does the sampling
        job by generating a random number between 0-9.
        """
        return random.randint(0, 9)


class Head:
    """
    Runs on the head node.
    """
    def __init__(self):
        # Kick off 3 workers, with each worker runs a
        # separate worker node.
        self._workers = [Worker.remote() for _ in range(3)]

    def sample(self) -> None:
        """
        Mock the way that the head iteratively gathers samples
        from each worker, while after certain iterations, it
        dies due to some exceptions. Then Kubernetes restarts
        the head node by tracking the healthy state (exit code)
        of the head node.
        """
        # Mock the way that after iteration 5,
        # head node raises the exception.
        _iter_exception = 5
        _iter = 0
        # Kick off the initial worker sampling job.
        worker_jobs = [
            (worker, worker.sample.remote())
            for worker in self._workers
        ]
        try:
            while True:
                if _iter > _iter_exception:
                    raise RuntimeError("Head hits the exception!")
                _iter += 1
                worker, worker_job = worker_jobs.pop(0)
                sample_res = ray.get(worker_job)
                print(f"The sampling result is {sample_res}.")
                # Pause 2s before proceeding.
                time.sleep(2)
                # Schedule a new job on the worker node to do sampling.
                worker_jobs.append((worker, worker.sample.remote()))
        except RuntimeError:
            # Once the head catches the exception, it exits with the
            # code 1, for Kubenetes to restart the head node.
            print("Exception caught, restarting head node now.")
            os._exit(1)


def main() -> None:
    ray.init()
    head = Head()
    head.sample()


main()
```
In this code, the main process runs on the head node, and the ray actor "Worker" objects run on the worker nodes. After iteration 5, it mocks the way that the head node hits the run time exception and exit with the code 1, so Kubernetes restarts the head node. After being restarted, the worker nodes fail to restart as Kubernetes worker group complains the worker nodes already exist.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
@RuofanKong Hi, thanks for reporting the issue. This is exact issue we meet earlier. Please check solution https://github.com/ray-project/kuberay/issues/104#issuecomment-1009519947 and https://github.com/ray-project/kuberay/issues/104#issuecomment-1010699475

**Comment by RuofanKong** [comment]
Hi @Jeffwan Thanks for the suggestion! It looks that this issue is different wrt the expected behavior.  For our use case, we expect both head and worker nodes do the failure recovery, and we don't want the head node to reuse the worker nodes because the worker nodes have cached data and they shouldn't be shared across sessions when the head node restarts.

**Comment by chenk008** [comment]
Hi, @RuofanKonga  little confused with reproduction script:
1.  Should the `ray.init()` contains address?
2. After the `head` in this script exited, the Head node in ray don't restart, the script is only a job in ray.

**Comment by RuofanKong** [comment]
Hi @chenk008. Thanks for looking. I should have clarified more, but I'm not sure the best way to share the Kube details rather than code:)
1. Yes. ray.init() should contain addresses. I didn't put it in the code as it's more Kube ray cluster info and I'm not sure the best way to share it here. But to repro the issue locally, we need to config those addresses in ray.init() as you mentioned.
2. Yes. Again, not sure the best way to share Kube info, but Kubernetes will handle the head node to restart per our case.
Hope this addresses your confusion.

**Comment by AdityaGudimella** [comment]
I have a request please. Let me know if I should put this up as a separate issue. There are cases where the ray cluster is made up of multiple sub groups, each group containing its own set of worker groups. For example, if you want to run hyperparameter search with Ray RLLib, multiple trainers are launched. Each trainer is an actor that creates its own set of actors. Each actor is a worker node. If one of the nodes containing the trainer actor dies, then the actors created by that trainer are no longer valid and need to be deleted. This way, when kubernetes brings back the trainer node, it will also spawn a new set of worker nodes for that specific trainer. For this, the kuberay operator would need to add support to groups of worker groups.
