### ISSUE TITLE
[Feature] Parameterize Test_RunningPods_RayContainerTerminated

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1392]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

https://github.com/ray-project/kuberay/pull/1386#pullrequestreview-1611687999

Example: https://github.com/ray-project/kuberay/blob/4492fe289118e69a289ffbe9fcee8afcafebf0d3/ray-operator/controllers/ray/raycluster_controller_fake_test.go#L518-L607

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @evalaiyc98 are you interested in this issue?

**Comment by lowang-bh** [comment]
/assign
 I will work on this.
