### ISSUE TITLE
[enhancement] Install pre-push setup hooks for linter

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/kuberay#1394]
Currently a PR can fail the automatic lint check in CI if the developer forgets to run `golangci-lint` or `gofumpt` locally before pushing.  Example: https://github.com/ray-project/kuberay/actions/runs/6089064782/job/16521053989 This can slow down the development process.

To eliminate this issue, we can have developers install a pre-push hook that runs the locally automatically when `git push` is called.

- We can mimic the approach taken in the Ray repo for the setup hook script: https://github.com/ray-project/ray/blob/master/setup_hooks.sh
- We should also include instructions for installing the hook in [`DEVELOPMENT.md`.](https://github.com/ray-project/kuberay/blob/master/ray-operator/DEVELOPMENT.md) (See https://docs.ray.io/en/latest/ray-contribute/getting-involved.html#lint-and-formatting for an example, it just tells the developer to run `setup-hooks.sh` once to set up the hook.)

**Comment by evalaiyc98** [comment]
I am really interested about this. Could I take this issue?

**Comment by architkulkarni** [comment]
@evalaiyc98 Of course! I don't know the full details of which linters are run, but you should be able to dig around in the github actions https://github.com/ray-project/kuberay/blob/9382c1fb5778a18ab5330164267c61425da82837/.github/workflows/test-job.yaml

One requirement is that the hook should ideally only take a few seconds (so if there's some step that takes longer, we should  just let it continue to run in CI only and not include it in the hook)

**Comment by evalaiyc98** [comment]
Thanks! It's helpful for me.

**Comment by boddumanohar** [comment]
It seems like the changes in the issue are already addressed by PRs: 
https://github.com/ray-project/kuberay/pull/2127
https://github.com/ray-project/kuberay/pull/2140

@architkulkarni could you please have a look and see if anything else is pending to solve this issue.
