### ISSUE TITLE
Verify podName before attempting to create the pod

### ISSUE THREAD

**Issue by akanso** [ray-project/kuberay#14]
currently:`
podName := strings.ToLower(instance.Name + common.DashSymbol + string(rayiov1alpha1.HeadNode) + common.DashSymbol)
`

can yield in an invalid podName > 63 characters

We need to check that the names we are building are valid

**Comment by harryge00** [comment]
https://github.com/ray-project/kuberay/blob/master/ray-operator/controllers/utils/util.go#L28
I think it is solved now? @akanso
