### ISSUE TITLE
[Feature] e2e tests for RayService high-availability without GCS FT

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1421]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

#1420 

### Related issues

#1420 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by ravishtiwari** [comment]
@kevin85421  - since you are already working on the linked issue, shouldn't this be assigned to you as well? or is this issue still looking for contributions?
