### ISSUE TITLE
Abscent Unit tests[Feature] 

### ISSUE THREAD

**Issue by blublinsky** [ray-project/kuberay#1426]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Unit test coverage in the API server is incomplete. More specifically RayJob APIs have no unit test coverage, for example, apiserver/pkg/utils/job has no unit tests, apiserver/pkg/model/converter_test.go has no unit tests for Ray job code

### Use case

Increase unit test coverage for API server

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by lowang-bh** [comment]
Hi @kevin85421 , let me work on it. Thanks

**Comment by blublinsky** [comment]
@lowang-bh  I am nearly done with the implementation
