### ISSUE TITLE
[Feature] Any plan to make python_client into its own pypi/conda package?

### ISSUE THREAD

**Issue by dizhouwu** [ray-project/kuberay#1439]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Python client is a fully community-managed component not maintained by Ray maintainers. It has not been actively maintained for the last two quarters. We do not have a plan to publish it to Pypi and Conda if it is not stable enough.
