### ISSUE TITLE
[CI][Buildkite] Test RayCluster sample YAMLs (nightly operator) is stuck indefinitely

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1459]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen

https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/1742#018ad8ca-1dc6-44a5-b1be-6dd83d490bbe

### Reproduction script

The test is stuck indefinitely in every PR / commit.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
Do you happen to know roughly when this started to fail? If not no worries, I should be able to look through past commits

**Comment by architkulkarni** [comment]
The offending PR is likely https://github.com/ray-project/kuberay/pull/1412.

The prior 9 commits all passed this test, but it failed in this commit and the 15 next commits (except for the 6th commit out of these, which I assume is due to randomness)
