### ISSUE TITLE
[Feature] Enable KubeRay test against multiple upstream Ray versions

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#146]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

As we talked in the community meeting, we will firstly try to maintain compatibility with a range of older Ray versions in KubeRay. 

This can be done by enable tests against multiple ray versions in the presubmit and postsubmit  testing. 

### Testing strategy

Before each KubeRay release,  maintainers should make sure  [latest -2, latest] versions are in the test plans. 

### Testing flow

For each commit, 

1. Build nightly KubeRay operator images. Push it to upstream container registry. 
2. Start a kind cluster, override the latest tag and install the operator
3. Start three parallel tests, each one test against one ray version.  We would like to test if start up commands can be supported by corresponding versions. 
4. Check whether the cluster can be up successfully. (need to check both head and worker since they use different commands)
5. Run a real world ray program and see check results. 

I think above steps gave us some level of confidences that compatibility works for normal cases. 

/cc @wilsonwang371 @simon-mo

**Comment by wilsonwang371** [comment]
this sounds good.

**Comment by DmitriGekhtman** [comment]
@wilsonwang371 @Jeffwan do our current compatibility tests cover this?

**Comment by wilsonwang371** [comment]
> @wilsonwang371 @Jeffwan do our current compatibility tests cover this?

we did it already
