### ISSUE TITLE
[Bug] RayJob envtest is flaky

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1471]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

https://github.com/ray-project/kuberay/actions/runs/6437188474/job/17481908089

### Reproduction script

https://github.com/ray-project/kuberay/actions/runs/6437188474/job/17481908089

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
@rueian are you interested in this issue?

**Comment by rueian** [comment]
Sure. This is the failed test.

<img width="820" alt="image" src="https://github.com/ray-project/kuberay/assets/2727535/497c8df5-7d99-4c9b-a781-d0d7de44fb49">

**Comment by kevin85421** [comment]
> 1. Do not use *myRayCluster.Spec.WorkerGroupSpecs[0].Replicas++ at L313, but use *myRayCluster.Spec.WorkerGroupSpecs[0].Replicas = int(*myRayJob.Spec.RayClusterSpec.WorkerGroupSpecs[0].Replicas)+1, which guarantees it will always be 4.

Using an idempotent operation makes sense to me.
