### ISSUE TITLE
[Bug] Kuberay Dashboard agent not being exposed as a Kubernetes service

### ISSUE THREAD

**Issue by Spritekin** [ray-project/kuberay#1477]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

We are running Ray Cluster in Kubernetes EKS using Kuberay, I installed using the helm chart.
Recently a team member would like to deploy a Serve application so he would like to submit the application to the cluster so he is following this guide:
https://docs.ray.io/en/latest/serve/advanced-guides/deploy-vm.html?highlight=RAY_AGENT_ADDRESS#using-a-remote-cluster

The guide expects the port 52365 of the dashboard agent to be open. Indeed in his local tests the port is open and he can submit the application to that port. So he is asking me to create an ingress to the RayCluster head at port 52365 corresponding to the dashboard agent.

Now after exploring the cluster, I know port 52365 is open in the head pods (run some curl and got the proper response), however it is not available as a Kubernetes service resource. When I describe the xxx-head-svc service I can see:

```
Port:              client  10001/TCP
TargetPort:        10001/TCP
Endpoints:         10.22.108.85:10001
Port:              dashboard  8265/TCP
TargetPort:        8265/TCP
Endpoints:         10.22.108.85:8265
Port:              metrics  8080/TCP
TargetPort:        8080/TCP
Endpoints:         10.22.108.85:8080
Port:              redis  6379/TCP
TargetPort:        6379/TCP
Endpoints:         10.22.108.85:6379
Port:              serve  8000/TCP
TargetPort:        8000/TCP
Endpoints:         10.22.108.85:8000
```

So the dashboard UI is there at 8265 which is ok as we use the Ray UI just fine, but I can't see the port 52365 at all. Can this be configured using the helm chart?

After reading the code I tried enabling the agent in the helm chart like this:
```
    head:
      rayVersion: ${local.ray_base_version}
      enableInTreeAutoscaling: true
      annotations:
        ray.io/enableAgentService: "true"

      rayStartParams:
        dashboard-host: '0.0.0.0'
        dashboard-agent-listen-port: '52365'
```

I even dropped and restarted the RayCluster, the head starts with the proper annotation, but the service still has no reference.

### Reproduction script

a. Install the ray operator.
b. Create a cluster using the helm chart.
c. Connect to the cluster and run:
```
# kubectl describe svc kuberay-cluster-head-svc
Name:              kuberay-cluster-head-svc
Namespace:         analytics
Labels:            app.kubernetes.io/created-by=kuberay-operator
                   app.kubernetes.io/name=kuberay
                   ray.io/cluster=kuberay-cluster
                   ray.io/identifier=kuberay-cluster-head
                   ray.io/node-type=head
Annotations:       <none>
Selector:          app.kubernetes.io/created-by=kuberay-operator,app.kubernetes.io/name=kuberay,ray.io/cluster=kuberay-cluster,ray.io/identifier=kuberay-cluster-head,ray.io/node-type=head
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                172.20.7.185
IPs:               172.20.7.185
Port:              client  10001/TCP
TargetPort:        10001/TCP
Endpoints:         10.22.120.227:10001
Port:              dashboard  8265/TCP
TargetPort:        8265/TCP
Endpoints:         10.22.120.227:8265
Port:              metrics  8080/TCP
TargetPort:        8080/TCP
Endpoints:         10.22.120.227:8080
Port:              redis  6379/TCP
TargetPort:        6379/TCP
Endpoints:         10.22.120.227:6379
Port:              serve  8000/TCP
TargetPort:        8000/TCP
Endpoints:         10.22.120.227:8000
Session Affinity:  None
Events:            <none>
```

There is no reference to port 52365.

### Anything else

If there is any way to configure this in the helm chart please advise.

I don't know enough Golang to contribute, but I could try if someone points me to the place where the kubernetes Service resources are built in the operator.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Spritekin** [comment]
Additional note, I also explored the "service" section of the yaml but found the .Values.service is only being used to get the service Type (ClusterIP by default).
However it seems the chart is reading from an attribute .Values.head.headService but there is no documentation and I'm not sure how they interact.

**Comment by kevin85421** [comment]
Currently, KubeRay only supports using RayService to serve models. You can refer to https://docs.ray.io/en/latest/cluster/kubernetes/getting-started/rayservice-quick-start.html for more details.

**Comment by mfojtak** [comment]
@kevin85421 In the very same document you are referring to:

https://docs.ray.io/en/master/cluster/kubernetes/getting-started/rayservice-quick-start.html#step-4-verify-the-kubernetes-cluster-status

There is a call 
```bash
kubectl get services
```

In the output of this call you can see the dashboard agent is exposed:
```
# NAME                                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                   AGE
# ...
# rayservice-sample-head-svc                    ClusterIP   10.96.34.90     <none>        10001/TCP,8265/TCP,52365/TCP,6379/TCP,8080/TCP,8000/TCP   4m58s
# rayservice-sample-raycluster-6mj28-head-svc   ClusterIP   10.96.171.184   <none>        10001/TCP,8265/TCP,52365/TCP,6379/TCP,8080/TCP,8000/TCP   6m21s
# rayservice-sample-serve-svc                   ClusterIP   10.96.161.84    <none>        8000/TCP                                                  4m58s
```

You're saying the port is exposed when the cluster is created via RayService but not if created via RayCluster?
What is the logic here?

**Comment by kevin85421** [comment]
> You're saying the port is exposed when the cluster is created via RayService but not if created via RayCluster?

No. You can also expose the head Pod's dashboard agent port by the RayCluster CR's head service.

> Currently, KubeRay only supports using RayService to serve models.

In Ray Serve, each Ray node has an HTTPProxyActor. A request can be forwarded to any Ray node in the cluster, where the HTTPProxyActor will then direct it to the appropriate replica. However, at present, RayCluster only provides a Kubernetes service for the Ray head. As a result, all HTTP proxies on worker nodes remain idle, compromising high availability.

**Comment by mfojtak** [comment]
> > You're saying the port is exposed when the cluster is created via RayService but not if created via RayCluster?
> 
> No. You can also expose the head Pod's dashboard agent port by the RayCluster CR's head service.
> 

How could this be done? Could you please share yaml config snippet on how to do it? 
I tried via "ports" under "headGroupSpec" but that doesn't work.

**Comment by mfojtak** [comment]
This seems to be working:

```yaml
headGroupSpec:
    # Kubernetes Service Type, valid values are 'ClusterIP', 'NodePort' and 'LoadBalancer'
    serviceType: LoadBalancer
    headService:
      spec:
        ports:
          - name: agent
            protocol: TCP
            port: 52365
            targetPort: 52365
```

The question is why only this particular port is explicitly disabled by default.

**Comment by kevin85421** [comment]
> How could this be done? Could you please share yaml config snippet on how to do it?

A native approach is to add a port to the Ray container in the head Pod, and KubeRay will then expose this port through the head service. #1493 is not used to expose the dashboard agent port, but you can still refer to it to expose port 52365.

**Comment by kevin85421** [comment]
Close this issue. Feel free to reopen if this does not answer your question.
