### ISSUE TITLE
[Feature] split Ray Container for each component

### ISSUE THREAD

**Issue by Irvingwangjr** [ray-project/kuberay#1497]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Here is the concrete discussion from Slack.
https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1696920747471889

In short, I hope the KubeRay can split the components into containers. For instance, we can upgrade the Dashboard agent individually rather than upgrade the whole image.

### Use case

For instance, I can modify some codes on the dashboard agent, like implementing additional plugins without asking the end user to change their ray core image.
Besides, It can also be useful that we can give the sidecar container more privilege and let the main container that the user's process running on stay using minimum privilege.

### Related issues

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Yes, we plan to separate the Autoscaler into its own Pod, and I am pushing the Ray community to make the Ray dashboard an independent service. We have several issues (e.g. #1416) to track the progress. Close this one. Feel free to reopen this issue if you have any further question.

**Comment by Irvingwangjr** [comment]
Thx for your reply~. About Autoscaler, do you guys have released a related public design doc yet? Cause if AnyScale plan to do this, we hope we can follow the same page. (Currently, we have designed two ways to do this,one draft is to deploy a daemon set, and the daemon will look after ray cluster heads that running on this node. the other one is to have a deployment to deploy the monitor, and use a lock on RayCluster to indicate which monitor instance adopts the head of cluster).

**Comment by rickyyx** [comment]
> cc @rickyyx does Autoscaler V2 have a public design doc?

Not yet - but i am putting up one.
