### ISSUE TITLE
[Bug] goimports reports issues on generate file

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#150]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen

![image](https://user-images.githubusercontent.com/4739316/154200259-13a15293-6ed6-480d-b799-a7e1a74a1448.png)

Link: https://github.com/ray-project/kuberay/runs/5211421675?check_suite_focus=true

I can not reproduce this on my personal laptop even with same goimports version.
Looks like it reports import issue in file `ray-operator/api/raycluster/v1alpha1/zz_generated.deepcopy.go`? This is definitely unexpected..

/cc @wilsonwang371 

### Reproduction script

```
$(go env GOPATH)/bin/goimports -l apiserver/ ray-operator/ cli/ | tee goimports.out
cat goimports.out
``` 

or 

```
goimports -w . 
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
I check the PR and below line was removed due to newer go version.  From the above screenshot, we can see this is the only line changed.. However, goimports reports the error on this line.

```
//go:build !ignore_autogenerated
```

I manually revert this change (no effect) as a workaround but really like to know who goimports reports error on the change.

**Comment by wilsonwang371** [comment]
@Jeffwan is this still valid? shall we close this?
