### ISSUE TITLE
[Feature] Use RayService with existing RayCluster

### ISSUE THREAD

**Issue by mfojtak** [ray-project/kuberay#1542]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

When creating RayService, the new ray cluster will be created as specified in
```yaml
rayClusterConfig:
  rayVersion: '2.7.0'
  ...
```

It would be great to be able to specify existing RayCluster.
Also it would be beneficial to have multiple RayService instances utilizing the same RayCluster.

### Use case

This would lead to better separation of infrastructure(RayCluster) and apps(RayService).
And better resource utilization.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by FlyTOmeLight** [comment]
This scene matches my needs, and I also want to make application as a k8s svc. it's there any roadmap.
@ericl @jianyuan @pcmoritz @tekumara

**Comment by kevin85421** [comment]
To achieve high availability for RayService, the RayCluster also needs to be configured correctly. For example, readiness/healthiness probes and an external Redis are required.
