### ISSUE TITLE
[Feature] Release Go module by release CI

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1549]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

https://github.com/ray-project/kuberay/pull/1546#discussion_r1364785656

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by astefanutti** [comment]
@kevin85421 Could you please assign this to me?

**Comment by kevin85421** [comment]
@astefanutti Done. Thank you!
