### ISSUE TITLE
[Feature] Cluster force upgrade support

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#155]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

We've talked about cluster upgrade in https://github.com/ray-project/kuberay/issues/40. However, at that time, the head can not provide HA and this would be a strong dependency to achieve rolling upgrade.

Recently, our customer claims that some fields can not be updated like ray params, Image, Resources etc. At the early stage, we do make them "immutable" in the operator and controller won't react to any changes due to above limitations. What if user can tolerant the downtime? Do we want to support breaking cluster upgrades?

Ref: pods/service reconcile loop doesn't handle the spec changes. 
https://github.com/ray-project/kuberay/blob/ffa7e6096043d4da86a71cc1b60501d8f9cab978/ray-operator/controllers/raycluster_controller.go#L250

### Use case

It would be much easier for user to upgrade the cluster instead of creating new ones.

### Related issues

https://github.com/ray-project/kuberay/issues/40

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by chenk008** [comment]
Yeah, I think we need a rollout strategy

**Comment by wilsonwang371** [comment]
here is something we need to pay attention to: latest ray uses in-memory kv storage instead of original redis.

what we can do in the very beginning now is simply deleting old head & workers and create them again later.

**Comment by Jeffwan** [comment]
Initial upgrade force upgrade version is supported
