### ISSUE TITLE
[Feature] Add support for Python 3.11

### ISSUE THREAD

**Issue by consultant-xyz** [ray-project/kuberay#1553]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Please add support for python 3.11.

### Use case

Our project is built based on ray. We have upgraded our python from 3.9.x to 3.11.x couple months back. We want to use Kubernetes as our back end so we deploy KubeRay to our k8s network.When we try to connect the head node in the cluster, we got the following error:

**RuntimeError: Python minor versions differ between client and server: client is 3.11.4, server is 3.8.13**

How could we update the ray server in k8s version to support python 3.11.x?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
You should update your Docker images. For more details, refer to https://hub.docker.com/r/rayproject/ray/tags?page=1&name=py311. Images with the py311 suffix support Python 3.11. In my understanding, Python 3.11 support is still experimental. You can check [this slack thread](https://ray-distributed.slack.com/archives/CNCKBBRJL/p1697707213372609) for more details. You can also open an GitHub issue in the Ray repository to improve the visibility.

**Comment by consultant-xyz** [comment]
I'm referring [kuberay](https://github.com/ray-project/kuberay) to support python 3.11. I knew ray could run on python 3.11 which I am using now.
