### ISSUE TITLE
[Feature] [RayJob] support light-weight submitting job inner controller as a optional mode

### ISSUE THREAD

**Issue by Basasuya** [ray-project/kuberay#1558]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Reference to this design doc
https://docs.google.com/document/d/1G--fKMCqp-M3T0qDPQy5eOQJQKRmubr7SyZQ_ms6Py4
Kuberay creates a Kubernetes job to run the necessary ray job command in the new design.
After this modification, the Rayjob controller is no longer responsible for submitting jobs, instead, it only needs to get the status from the k8s job.

In the production environment, I think it has some problem
* The submission Pod needs additional quota, and it needs more configuration when using gang scheduling.
* need to maintain submission images for users and pulling this pod requires additional time in the job life cycle.
* unexpected termination of the job's log stream will cause `ray job submit` to end, I think this is one of the problems that needs to be handled
 
I hope to retain the old mode(submit by dashboard HTTP client) as a second choice in the job controller.
We are willing to contribute relevant code to solve the problems mentioned in the doc by adding a state machine, setting a unique submission-id and so on.
I think there are still users who want to use this light-weight mode of job submission

### Related issues

https://github.com/ray-project/kuberay/issues/756

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Basasuya** [comment]
\cc @kevin85421

**Comment by kevin85421** [comment]
Thank you for opening the issue! I will take this into consideration after I finish the v1.0.0 release process. 

> The submission Pod needs additional quota

This seems to be the main problem. Other points are addressable.

**Comment by hongchaodeng** [comment]
@Basasuya Thanks for putting things together.


> I hope to retain the old mode(submit by dashboard HTTP client) as a second choice in the job controller.

This is a major change even if it is an optional feature. For next step, I would recommend draft up a design doc first and share how you approach this problem in this way.

Please feel free to ask any questions and share any thoughts you have in mid way!

**Comment by Basasuya** [comment]
OK, I will give some details about how to solve the problem in the old mode mentioned in previous issues

**Comment by Basasuya** [comment]
Sorry for being a bit busy these two weeks. I'd like to briefly explain our solution for light-weight job submission. We define the state machine of the ray job to avoid the job being submitted more than one time, having status conflicts, and so on.

A key optimization is that we set the submission_id bound to a ray job(for example use ray job uid) in runtime_env to ensure the uniqueness of job submission. Even if the job is submitted repeatedly, the subsequent submissions will be set as failures by the ray dashboard.

Through the picture below, I introduce the details of state machine transfer.
<img width="595" alt="image" src="https://github.com/ray-project/kuberay/assets/20502868/747edef1-bd38-42b9-ac89-6df9079585a7">

## INIT
INIT -> PENDING: the controller would first create the ray cluster, and wait for the cluster to be ready.
we know a ray job can be submitted before all ray nodes are ready. We have added a config to support querying the number of existing nodes from the ray dashboard to determine whether the job can be submitted. if ray job is submitted, the state would transfer to PENDING.
INIT -> PENDING/RUNNING/SUCCESS/STOPPED/FAILED:
If the job submission fails, there is a situation where the job has been submitted in a previous round of reconciling. After submission fails, controller would just query the job status. If the job info result is a certain status, it will be directly transferred to this status.
INIT -> FAILED
If the cluster is not ready for a certain time, just transfer to FAILED

## PENDING
PENDING -> RUNNING/SUCCESS/STOPPED/FAILED:
get the job info from the ray dashboard, then transfer it to the new state
If fail to get the job info, try in next reconcile
PENDING -> FAILED
If the job info query fails for more than a certain number of times, it will be transferred to FAILED

## RUNNING
RUNNING -> SUCCESS/STOPPED/FAILED:
get the job info from Ray dashboard, then transfer it to the new state
if fail to get the job info, try in next reconcile
RUNNING -> FAILED
If the job info query fails for more than a certain number of times, it will be transferred to FAILED


## SUCCESS/STOPPED/FAILED
In the final state, ray job will clean up the cluster resources, or there are configs to set TTL for cleanup, just try again in the next reconcile

**Comment by Basasuya** [comment]
In addition, we found that JobDeploymentStatus also does not have a strict state machine. In fact, this is sometimes very important in our environment. We hope to do some design later.
