### ISSUE TITLE
[Feature] Support in-built Grafana for Ray Cluster

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#156]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Ray in-built dashboard is pretty helpful for most telemetry use case. Internally, we also like to leave an eye on control plane metrics like gcs, gc object etc.  These metrics are already exposed via prometheus and what we need to do is to build a ready to use dashboard for cluster admins to monitor the cluster.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scarlet25151** [comment]
I think we have put grafana config in the repos and we may close the story?

**Comment by Jeffwan** [comment]
PR https://github.com/ray-project/kuberay/pull/230 add the support and we can close this one.
