### ISSUE TITLE
[Feature] Expose generated `ray start` command for worker and head nodes.

### ISSUE THREAD

**Issue by kevingreer** [ray-project/kuberay#1560]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

KubeRay generates a `ray start` command to that is executed to start the cluster head node and cluster worker nodes. In a `RayService` Kubernetes config when specifying the head and worker pod templates, you can add a `command` field, and that command will be prepended to the generated `ray start` command, like `$CUSTOM_CMD && $GENERATED_CMD`. The code for this functionality is [here](https://github.com/ray-project/kuberay/blob/53cacd92b4bf9fcd00beee2d95c10dd40796abc4/ray-operator/controllers/ray/common/pod.go#L301).

This issue requests a feature that allows `$GENERATED_CMD` to be exposed to the custom command specified in the k8s config. After this feature is implemented, a person would be able to use the KubeRay generated `ray start` command within their custom command specified in their pod templates.

### Use case

I have a binary that wraps arbitrary shell commands. This binary provides some general functionality useful for all services at my company, such as piping logs to our various logging systems. It is run like so:
```sh
./wrapper-binary --command "$CMD"
``` 
where `$CMD` can be any arbitrary command. For the use case of this issue, I would like `$CMD` to be `ray start` command generated by KubeRay.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hongchaodeng** [comment]
@kevingreer Thanks for putting this together!

We are now in the final stage of releasing **v1.0**. Will get back on this once v1.0 is released!

**Comment by findmyway** [comment]
Any progress on this?

It seems the command is prepended to the `Args` field.

```
    Command:
      /bin/bash
      -lc
      --
    Args:
       /usr/local/bin/custom.sh  && ulimit -n 65536; ray start --head  --dashboard-host=0.0.0.0  --metrics-export-port=8080  --block  --num-cpus=1
```

We'd like to apply it to before the `ray start` command.

**Comment by kevin85421** [comment]
I will work on this issue this week.

**Comment by kevin85421** [comment]
> We'd like to apply it to before the ray start command.

@findmyway Do you mean `ulimit -n 65536; /usr/local/bin/custom.sh; ray start --head  --dashboard-host=0.0.0.0  --metrics-export-port=8080  --block  --num-cpus=1`? Thanks!

**Comment by findmyway** [comment]
> > We'd like to apply it to before the ray start command.
> 
> @findmyway Do you mean `ulimit -n 65536; /usr/local/bin/custom.sh; ray start --head --dashboard-host=0.0.0.0 --metrics-export-port=8080 --block --num-cpus=1`? Thanks!

For my case, I mean `ulimit -n 65536; /usr/local/bin/custom.sh ray start --head --dashboard-host=0.0.0.0 --metrics-export-port=8080 --block --num-cpus=1`

---

More details about my usage.

I'm using micromamba in a custom docker image. It has an `entrypoint.sh` to activate runtime environment [ref](https://micromamba-docker.readthedocs.io/en/latest/advanced_usage.html#details-about-automatic-activation).
