### ISSUE TITLE
[WIP][Discussion] RayJob roadmap after v1.0.0

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1567]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

# Submission

Before v0.6.0, the KubeRay operator submitted a Ray job to a RayCluster using an HTTP request when users utilized RayJob. Starting from v0.6.0, KubeRay uses a K8s Job for Ray job submissions.

* TODO: K8s Job & HTTP client comparison

# Cluster

* TODO: Comparison between an existing RayCluster (`clusterSelector`) or new RayCluster.

# Considerations (TODO)

* Log persistence
* Retry
* Timeout
* Avoid double creation

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by richardsliu** [comment]
How about creating a `KuberayJobSubmissionClient`? 

I was considering something similar to the Python JobSubmissionClient for Ray, exposing the following methods:
* submit_job
* stop_job
* delete_job
* list_job
* get_job_status

The value is that this client will talk to the k8s API server which is Kubernetes native and has built-in security and RBAC policies.

Then if possible, we can provide an option to override the instance of the JobSubmissionClient used [here](https://github.com/ray-project/ray/blob/master/dashboard/modules/job/cli.py#L23), which means users can use `ray job submit` to create Kuberay jobs.

WDYT?

**Comment by smit-kiri** [comment]
> How about creating a KuberayJobSubmissionClient?
+1 to this.

Right now, I'm creating a `RayCluster` through KubeRay and submitting jobs through the Ray `JobSubmissionClient` because Ray's client has a lot more features than KubeRay's `RayJob`. Like the `get_job_logs` is an important one. `RayJob` also has some great features like TTL, I'd love to have features from Ray's `JobSubmissionClient` and KubeRay's `RayJob`
