### ISSUE TITLE
[Feature] Install kuberay-operator in a dedicated namespace

### ISSUE THREAD

**Issue by andrewsykim** [ray-project/kuberay#1576]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

The current kuberay helm chart installs kuberay-operator in the default namespace. With the project approaching v1, I think it would be beneficial to install kuberay-operator in a dedicated namespace (e.g. ray-system or kuberay-system).

Using the default namespace is not ideal for a number of reasons and a dedicated namespace can tighten resource allocation and RBAC (amongst many other things). 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by andrewsykim** [comment]
I'm happy to help this work if we agree on the approach and namespace name. I personally like ray-system or kuberay-system

**Comment by andrewsykim** [comment]
@kevin85421 any thoughts on this?

**Comment by kevin85421** [comment]
Thanks for calling this out! If users want to install KubeRay in a dedicated namespace, users can install KubeRay in a different namespace by using the following command: 

```sh
kubectl create ns ${DEDICATED_NAMESPACE}
helm install ... -n ${DEDICATED_NAMESPACE}
```

Installing KubeRay in the `default` namespace by default allows users to follow KubeRay documentation and examples without needing to create a new namespace.

**Comment by andrewsykim** [comment]
Thanks Kevin!

> Installing KubeRay in the default namespace by default allows users to follow KubeRay documentation and examples without needing to create a new namespace.

Any reason we can't install in a dedicated namespace by default and update the documentation accordingly?

**Comment by kevin85421** [comment]
> Using the default namespace is not ideal for a number of reasons

Could you please provide more details on this?

Instead of modifying the default behavior, we could consider creating a new document for KubeRay best practices and incorporating your suggestion into that document. My primary goal is to ensure that users follow the documentation and examples successfully.

**Comment by andrewsykim** [comment]
Thanks @kevin85421 -- I'll close this for now since users can pass the namespace into the helm commands

**Comment by kevin85421** [comment]
@andrewsykim Would you mind sharing more insights about the benefits of installing in a dedicated namespace? We can add the points into a doc for best practices. Thanks!

**Comment by andrewsykim** [comment]
> Would you mind sharing more insights about the benefits of installing in a dedicated namespace?

There's a lot of references if you google it, but here's one from Google Cloud: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-organizing-with-namespaces.

There's a section titled "The “default” Namespace" which says:

```
There is absolutely nothing special about this Namespace, except that the Kubernetes tooling is set up out of the box to use this namespace and you can’t delete it. While it is great for getting started and for smaller production systems, I would recommend against using it in large production systems. This is because it is very easy for a team to accidentally overwrite or disrupt another service without even realizing it. Instead, create multiple namespaces and use them to segment your services into manageable chunks.
```

In general it is best practice for Kubernetes addons / services to be installed in their own namespaces, it's rare to see addons being run in the default namespace. It is much easier to manage RBAC, resource isolation and auditing this way. I recommend public docs avoid installing in the `default` namespace. It shouldn't impact ease of installation as long as the helm charts are also updated to create the namespace so the extra `kubectl create ns` step is not needed.
