### ISSUE TITLE
Handle batch scheduling for Ray Jobs and Kueue

### ISSUE THREAD

**Issue by peterghaddad** [ray-project/kuberay#1579]
Kueue is a project maintained by a Kubernetes Special Interest group. Kueue enables both native and custom resource definition job types to be gang and batch scheduled onto a kuberenetes cluster.

This issue will:

Add improvements to the Ray Operator to handle Ray Jobs managed by Kueue. This entails but is not limited to safety checks to reduce compute when jobs are in a pending state.

**Comment by kevin85421** [comment]
Done https://github.com/ray-project/kuberay/issues/1890
