### ISSUE TITLE
[RayJob] Respect shutdownAfterJobFinishes and TTL when JobStatus cannot be retrieved

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/kuberay#1586]
Currently the shutdown logic is only entered if the Ray JobStatus is SUCCEEDED or FAILED.  It is currently done by comparing a timestamp with JobInfo.end_time which is populated by Ray and retrieved via HTTP.  

However in the case where the JobStatus/JobInfo cannot be retrieved via HTTP, the reconciliation loop will return and requeue before getting to the shutdown logic.

In order to implement this, we will need some way to keep track of how long the JobStatus retrieval has been failing for.
        

_Originally posted by @architkulkarni in https://github.com/ray-project/kuberay/issues/1583#issuecomment-1786177790_

**Comment by kevin85421** [comment]
In #1833, RayJob transitions to `Complete` when the K8s Job fails.
