### ISSUE TITLE
[Bug] RBAC file can not be updated automatically 

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#164]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When I make some changes to kubebuilder rbac markers, after I enter `ray-operator` folder and run `make manifests`, I expect the clusterrole file can be updated automatically. However, it's not. 

https://github.com/ray-project/kuberay/blob/0ef786113439d777330a8d2067f8a6449502cc56/ray-operator/controllers/raycluster_controller.go#L62-L73

### Reproduction script

```
# 1. make kubebuilder rbac marker changes

2. `cd ray-operator`

3. `make manifests`

4. git diff -> not updates

```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Resolved by #577 and #576.
