### ISSUE TITLE
[Feature] Support suspending RayClusters

### ISSUE THREAD

**Issue by andrewsykim** [ray-project/kuberay#1667]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Similar to RayJobs, it would be nice if RayClusters can be suspended via field update. I haven't given much thought into the field name, but something like `spec.suspend = true|false` or `spec.active = true|false` might work. This is much cleaner than existing alternatives to scale all worker node groups to 0 to replicas similar behavior.

I am happy to prototype this to get early feedback on the approach. 

### Use case

1. A user wants to temporarily pause a RayCluster without deleting all the resources. This is especially useful if the original manifest to create the RayCluster is no longer available, or there were edits to the RayCluster that were not preserved.
2. Batch schedulers like [Kueue](https://github.com/kubernetes-sigs/kueue) or [Volcano](https://volcano.sh/en/) that support RayClusters need a way to evict and re-queue RayClusters. Currently the only way to "suspend" RayClusters is to scale all worker groups to 0. A field to suspend the cluster would be cleaner since we don't have to change worker group replicas to temporary stop RayClusters.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by andrewsykim** [comment]
Thoughts @kevin85421 on this? Happy to prototype this to see if it's feasible

**Comment by andrewsykim** [comment]
> I am not very familiar with the concept of suspend here.

Fwiw, the field does not necessarily have to be `suspend`. It can called `spec.active` or something else. 

> Does suspend mean to delete all worker Pods without updating the replicas to 0 for each worker group?

My initial thinking is yes, it will delete all worker pods without changing replicas. This is important because when the RayCluster is "resumed" we don't have to track what the previous replicas was. 

> Will the head Pod be deleted?

Yes I would think so

> Will this feature include any Kueue/Volcano-specific code leak?

No it wouldn't. The change is just introducing a new field in RayCluster to temporarily scale down all worker pods. Kueue/Volcano would just consume the new field as part of it's implementation. It's no different to how it uses `suspend` field for RayJobs todya.

**Comment by kevin85421** [comment]
@andrewsykim, thank you for the explanation! I think this feature makes sense and is lightweight. Out of curiosity, are there any users requesting this in the Kueue community?

**Comment by andrewsykim** [comment]
> thank you for the explanation! I think this feature makes sense and is lightweight. Out of curiosity, are there any users requesting this in the Kueue community?

Yes, we have some feedback from users that they would like support for RayClusters. There's some discussion in https://github.com/kubernetes-sigs/kueue/issues/1272
