### ISSUE TITLE
[Question] Ingress for HTTP and GRPC endpoints

### ISSUE THREAD

**Issue by ebr** [ray-project/kuberay#168]
This is not yet a feature request, but rather a question. We have internally developed a fairly simple, out-of-band method for adding Ingresses exposing the Ray head HTTP and GRPC endpoints, with both TLS and HTTP Basic Authentication. `ray-operator` can add a single Ingress to a cluster, but it does not yet have feature parity with our required Ingress configuration. Just trying to get a sense on prioritization of this work within the `kuberay` project. If this is not high priority at the moment, we are open to implementing it ourselves and opening a pull request.

**Comment by Jeffwan** [comment]
Hi @ebr 

I think a few users would love to use ingress to expose traffic to external. We add a feature (https://github.com/ray-project/kuberay/pull/38) early for this but this is still like an alpha version. Feel free to propose improvement or new features on this. 

If you can create an issue or design doc and get some feedbacks from community https://github.com/ray-project/kuberay/tree/master/docs/design , that would be great!

**Comment by ebr** [comment]
Sounds good. We may need to implement this soon, so in that case we will reference our implementation in the feedback gathering process. Looking at #38, we are thinking along the same lines, so that's good. I will open another issue as you suggested. Thanks!
