### ISSUE TITLE
[Feature] Should we upgrade envtest?

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1697]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

#1648 upgrades the version of `controller-runtime` to v0.16.3, but we use the script `setup-envtest.sh` in `controller-runtime` v0.7.2 to set up envtest. 

cc @astefanutti should we upgrade the version? Thanks!

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by astefanutti** [comment]
@kevin85421 absolutely, good catch. Feel free to assign this to me.
