### ISSUE TITLE
[Bug] Job Submitter pod gets stuck in a terminating state when rayjob is deleted

### ISSUE THREAD

**Issue by chatter92** [ray-project/kuberay#1723]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I followed the instructions provided here (https://raw.githubusercontent.com/ray-project/kuberay/master/ray-operator/config/samples/ray_v1alpha1_rayjob.yaml) to submit a Ray job. In the YAML configuration, I specifically set "shutdownAfterJobFinishes" to "true."

Upon successful completion of the Ray job, the underlying Ray cluster was automatically deleted as expected. However, when trying to delete the Ray job itself, I encountered an issue. The job submitter pod became stuck in a "terminating" state, even though the Ray job had been successfully deleted.

I tried a force delete on the pod, but unfortunately, this did not resolve the issue. 
Note: I faced this challenge whether I opted to submit the Ray job using my custom submitterPodTemplate or fallback to the default one that kuberay adds.

### Reproduction script

1. Submit the sample rayjob provided above (set shutdownAfterJobFinishes: true):
kubectl apply -f rayjob.yaml

2. Wait for the rayjob to finish, the raycluster to get deleted and the job submitter pod to transition to a completed state.

3. kubectl delete pod <job-submitter-pod-name> -n <namespace>

4. The pod gets stuck in a terminating state.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
I don't observe the issue. Which KubeRay version do you use?

```sh
helm install kuberay-operator kuberay/kuberay-operator --version 1.0.0
# Set "shutdownAfterJobFinishes" to "true"
kubectl apply -f ray_v1alpha1_rayjob.yaml

# The submitter Pod is created by a Kubernetes Job. The Pod has been successfully deleted.
kubectl delete pod rayjob-sample-l7fgh
```
<img width="669" alt="Screen Shot 2023-12-20 at 12 00 55 AM" src="https://github.com/ray-project/kuberay/assets/20109646/840fdbdf-a13d-48a5-b10d-45aad9a96a79">

**Comment by kevin85421** [comment]
You can also check more details by using `kubectl describe job ${YOUR_JOB}`. I am not certain about the behavior when deleting a Pod created by a Kubernetes Job.

**Comment by kevin85421** [comment]
Close this issue. If this issue still exists, feel free to reopen the issue.
