### ISSUE TITLE
[Bug] Redis Cleanup Job blocks deletion if GCS didn't start

### ISSUE THREAD

**Issue by smit-kiri** [ray-project/kuberay#1725]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When trying to delete a `RayService` where the head node hadn't spun up, the Redis Cleanup job runs into an error and the pod is stuck in an `Error` state. The `RayCluster` resource doesn't get deleted until the job finishes successfully.

I would expect the job to retry a few times with a backoff and still delete the resource if it doesn't succeed after a set number of retries.

### Reproduction script

Create a `RayService` resource and delete it while the head pod is still in `Pending` or `ContainerCreating` stage.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
It seems to be the right time to make the Redis cleanup a best-effort task (https://github.com/ray-project/kuberay/issues/1557#issuecomment-1788480539) cc @rueian

**Comment by smit-kiri** [comment]
FWIW, you can also let the user toggle between strict and best-effort with a flag

**Comment by rueian** [comment]
Hi @smit-kiri,

Could you let me know what error message you saw on the Redis Cleanup job? Or did it just exit with code 1 without any message?

**Comment by kevin85421** [comment]
@rueian 

I think it will fail immediately instead of retrying, as the key doesn't exist in Redis. You can see the details in the "Note" section of this PR description: https://github.com/ray-project/kuberay/pull/1592#issue-1973091979.

**Comment by rueian** [comment]
> @rueian
> 
> I think it will fail immediately instead of retrying, as the key doesn't exist in Redis. You can see the details in the "Note" section of this PR description: [#1592 (comment)](https://github.com/ray-project/kuberay/pull/1592#issue-1973091979).

Yeah, so I wonder could we have another option - treating key not found as succeed?

**Comment by smit-kiri** [comment]
> Yeah, so I wonder could we have another option - treating key not found as succeed?

That makes sense too! Although does the job re-try deleting if it fails the first time? The Redis instance might not be available when it tries first, but it might after a couple minutes

**Comment by rueian** [comment]
> > Yeah, so I wonder could we have another option - treating key not found as succeed?
> 
> That makes sense too! Although does the job re-try deleting if it fails the first time? The Redis instance might not be available when it tries first, but it might after a couple minutes

Yes, it will retry several times if your redis is not started yet. The detailed behavior is covered in the PR https://github.com/ray-project/kuberay/pull/1757 and the PR can solve your current issue.

@kevin85421 I will also open a PR to make the cleanup job, by default, work in a best-effort manner in any case later.

**Comment by kevin85421** [comment]
Close by #1766
