### ISSUE TITLE
[Bug] Volcano batch scheduler marks pods unschedulable when the ray cluster has multiple workerGroups

### ISSUE THREAD

**Issue by Tongruizhe** [ray-project/kuberay#1752]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Currently when the volcano batch scheduler is enabled, ray-operator will create a podgroup for the ray cluster. 

In volcano's concepts, a podgroup futher consists of multiple taskGroups. The API for taskGroups is the [volcano.sh/task-spec](https://github.com/volcano-sh/apis/blob/64d2f7ccad0bd3498fd7d88754e4a0c85a86455c/pkg/apis/batch/v1alpha1/labels.go#L21C2-L21C14)  annotation on the pod, with the value of the taskGroup name.

Each task groups consists of multiple task replicas, and each task replica has a 1-to-1 mapping of a pod. When doing scheduling, the volcano scheduler caches scheduling results for a task groups: if the first replica in the task group can not fit in a node, this node is skipped for all other replicas in the same task group, because volcano scheduleer assumes that the replicas in a task group has the same pod spec.

However, ray-operator does not apply this annotation to pods, which causes the volcano scheduler to treat all pods of a ray cluster as a whole task group, and assumes all pods have the same spec. It's obviously not desirable because different workerGroups have different pod specs.  

One issue I found is that the volcano scheduler failed to schedule pods even when there is enough resources. In comparison the k8s default scheduler can scheduler these pods normally.

### Reproduction script

1. Set a k8s cluster with two nodes and ray-operator enabled. The first node have label "node-type: A", and the second has "node-type: B"
2. Create a ray cluster with two worker groups. The first has the node selector "node-type A",  the second has the node selector "node-type B"
3. The pods will fail to be scheduled with enable-batch-scheduler, but can be scheduler wehn batch scheduler is disable.

The reason is when the volcano scheduler caches the result that node-type A can not fit worker group 2. When it schedules pods for worker group B, it simply reuses the cache results and decide that node-type B can NOT also fit pods in worker group B, because they are in the same task groups.

The fix is to add task groups spec annotations to ray pods.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rt849122** [comment]
Versions:
Kuberay v1.0.0
Volcano 1.8
