### ISSUE TITLE
[Feature] Specify ray-operator User-agent

### ISSUE THREAD

**Issue by chenk008** [ray-project/kuberay#1817]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Ray-operator uses controller-runtime to run it's reconcile . The user-agent is generated by `DefaultKubernetesUserAgent`, it is confused.

We should set user-agent explicitly.

### Use case

The user-agent is useful in kube-apiserver's access log and audit log

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Closed by #1982
