### ISSUE TITLE
[Feature] Add Helm Chart Checker in CI

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#184]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

This is requested from @chenk008 in https://github.com/ray-project/kuberay/pull/175#issuecomment-1061655294.

We maintain both the kustomize and helm manifests. Currently, we do use kustomize to deploy the control plane and validate cluster creations etc in CI. However, we lack of tests to validate helm chart changes. This can be improved by adding helm chart checker in CI.

/cc @ebr @chenk

### Use case

Validate helm manifest changes make sure it's working 

### Related issues

https://github.com/ray-project/kuberay/pull/175

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
It's partially covered by https://github.com/ray-project/kuberay/pull/554.

What remains to be done is to add KinD CI integration tests that validate that the charts work end-to-end.

**Comment by DmitriGekhtman** [comment]
> What remains to be done is to add KinD CI integration tests that validate that the charts work end-to-end.

A basic e2e sanity check that we can use Helm to deploy a 1-head and 1-worker Ray cluster with the latest Ray version would be sufficient.

**Comment by DmitriGekhtman** [comment]
We can use existing compatibility test code as a starting point for this.

**Comment by DmitriGekhtman** [comment]
@kevin85421 for the KubeRay 0.4.0 release we should add a e2e CI test that validates that at least the default values.yaml works

**Comment by DmitriGekhtman** [comment]
Again, not a hard blocker for the 0.4.0 release, but we do need to at least do some manual testing.
