### ISSUE TITLE
[Feature][RayJob] Redefine RayJobStatus.EndTime

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1849]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, KubeRay sets the value of `EndTime` based on the job information retrieved from the Ray head ([code](https://github.com/ray-project/kuberay/blob/33f29f61d6be0809662df2a58bbc605e7256a114/ray-operator/controllers/ray/rayjob_controller.go#L196-L218)). Then, `EndTime` is used to determine when the TTL is reached ([code](https://github.com/ray-project/kuberay/blob/33f29f61d6be0809662df2a58bbc605e7256a114/ray-operator/controllers/ray/rayjob_controller.go#L263-L279)). However, if the RayCluster or the submitter K8s Job are unhealthy, KubeRay can't get any job information from the Ray head. See #1833 as an example. In that case, the definition of `EndTime` is the time when KubeRay detects the failure of the submitter Kubernetes Job ([code](https://github.com/ray-project/kuberay/blob/33f29f61d6be0809662df2a58bbc605e7256a114/ray-operator/controllers/ray/rayjob_controller.go#L621)). There are multiple definitions of `EndTime` at this moment.

If the RayJob transitions to the status `Complete`, the `EndTime` must be set to determine when the TTL is reached. If it is not set, the KubeRay will throw a nil pointer dereference exception ([code](https://github.com/ray-project/kuberay/blob/33f29f61d6be0809662df2a58bbc605e7256a114/ray-operator/controllers/ray/rayjob_controller.go#L263)). We can redefine the `EndTime` to the time that the RayJob enters the `Complete` status. After that, we only have 1 definition of `EndTime` and we can avoid the nil pointer dereference error when we forget to set `EndTime` before transitioning to the `Complete` status in the future.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @andrewsykim Would you mind commenting on this issue? Without your comment, I am unable to assign the issue to you. Thanks!

**Comment by andrewsykim** [comment]
+1 I can work on this

**Comment by andrewsykim** [comment]
Oops, this should have been closed with https://github.com/ray-project/kuberay/pull/1872
