### ISSUE TITLE
[Feature][RayJob] Set the environment variable `FQ_RAY_IP` for the submitter Kubernetes Job

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1850]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

KubeRay injects the variable `FQ_RAY_IP` into all Ray worker Pods. `FQ_RAY_IP` represents the fully qualified domain name of the Kubernetes service for the Ray head, typically resembling something like `rayjob-sample-raycluster-2jmwq-head-svc.default.svc.cluster.local`.

For the submitter Kubernetes Job in RayJob, we expose the [submitterPodTemplate](https://github.com/ray-project/kuberay/blob/33f29f61d6be0809662df2a58bbc605e7256a114/ray-operator/config/samples/ray_v1alpha1_rayjob.yaml#L97-L105) in the RayJob CRD, allowing users to customize their submitter Kubernetes Job. However, if users wish to customize the `command`, they will find that they don't know the submission address, as the generated name of the RayCluster is unknown prior to creating the RayJob. To address that, we can inject the environment variable `FQ_RAY_IP` for the submitter Kubernetes Job. The value of `RayJobStatus.DashboardURL` in the RayJob is the same as the value of `FQ_RAY_IP` in the worker Pods.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @andrewsykim Would you mind commenting on this issue? Without your comment, I am unable to assign the issue to you. Thanks!

**Comment by andrewsykim** [comment]
+1 happy to work on this

**Comment by andrewsykim** [comment]
https://github.com/ray-project/kuberay/pull/1852
