### ISSUE TITLE
[Feature] serve run and serve deploy question

### ISSUE THREAD

**Issue by echzhai** [ray-project/kuberay#1853]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

should have doc introduce how should use kuberay  if you have several team.
"serve run" command will first delete all existing model and then deploy your model. this behaviour is not user friendly if there are several people share the same ray cluster. i do not understand? i think it is good to have a raycluster can be shared.

"serve deploy" command will not be able to deploy model in exist raycluster. since you can not ues --working-dir to ask ray upload the script to remote raycluster. why?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
> "serve run" command will first delete all existing model and then deploy your model. this behaviour is not user friendly if there are several people share the same ray cluster.

I agree. This is not a user-friendly behavior. Would you mind posting in the Ray repository since this is a Ray Serve issue? You can cc me and I can ping Ray Serve maintainers to take a look. Thanks!

**Comment by echzhai** [comment]
I create this issue in ray project: https://github.com/ray-project/ray/issues/42622 
@kevin85421
