### ISSUE TITLE
[CI] [Bug] e2e sample YAML test pipeline is broken with Docker image hash mismatch

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/kuberay#1859]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen
CI started failing on Friday Jan 19.  `kind` fails to load the Ray image. (Update: We removed the `kind load $RAY_IMAGE` command in #1863 as it was unnecessary. However, we do still see the same error sometimes with `kind load $KUBERAY_OPERATOR_IMAGE`, but with less frequency: https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/3028#018d3397-cd40-4ecc-ac10-e1f3e88f1595/251-522  )

One of the latest passing builds: https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/2996 (Created Friday Jan 19, 3:37pm PST)

One of the earliest failing builds: https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/3000 (Created Friday Jan 19, 4:32pm PST)

It seems to be consistently failing after this time.

Example 1 (Ray 2.9.1): https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/3014#018d324f-f339-48d1-aaac-3d1b7c5840ba/252-532
```
2024-01-22:18:00:28,42 INFO     [utils.py:358] Execute command: kind load docker-image rayproject/ray:2.9.1
--
  | Image: "rayproject/ray:2.9.1" with ID "sha256:1b80f2dd7cb3daaafc5fc33a17ad46fe68c02e2fffd6601c7b3b68c86101d394" not yet present on node "kind-control-plane", loading...
  | ERROR: failed to load image: command "docker exec --privileged -i kind-control-plane ctr --namespace=k8s.io images import -" failed with error: exit status 1
  | Command Output: unpacking docker.io/rayproject/ray:2.9.1 (sha256:485e2ab3b1a7388c0ba26444bd6dc0d762d14c78ccde4912cb39e3af075a2003)...time="2024-01-22T18:01:37Z" level=info msg="apply failure, attempting cleanup" error="wrong diff id calculated on extraction \"sha256:22a4c9947a252dd9f3c19c63cb7e18e820b9fa63b8fb85a4fe0ef8f6b61d3027\"" key="extract-20169242-twgx sha256:3a03f09d212915b240e9d216069aba5652ed4765c7e4b098c65e71860d47b8e1"
  | ctr: wrong diff id calculated on extraction "sha256:22a4c9947a252dd9f3c19c63cb7e18e820b9fa63b8fb85a4fe0ef8f6b61d3027"

```

Example 2 (Ray 2.9.0): Happening in this PR https://github.com/ray-project/kuberay/pull/1857

```
Image: "rayproject/ray:2.9.0" with ID "sha256:ee1c865e02572031f5c68be4184f21d929d5cd233289c83b2a10b9ce455eb75f" not yet present on node "kind-control-plane", loading...
ERROR: failed to load image: command "docker exec --privileged -i kind-control-plane ctr --namespace=k8s.io images import -" failed with error: exit status 1
Command Output: unpacking docker.io/rayproject/ray:2.9.0 (sha256:c0648f29a35efc1b2c3ee71393914fbab27e85ee4add32a1582d532159ae9f6d)...time="2024-01-22T16:47:05Z" level=info msg="apply failure, attempting cleanup" error="wrong diff id calculated on extraction \"sha256:db6680cb129d39fad6405b4fc83b612de4a228c95b437893af46d8b781ddd0f6\"" key="extract-983277564-yt-D sha256:3a03f09d212915b240e9d216069aba5652ed4765c7e4b098c65e71860d47b8e1"
ctr: wrong diff id calculated on extraction "sha256:db6680cb129d39fad6405b4fc83b612de4a228c95b437893af46d8b781ddd0f6"
```

### Reproduction script

see above

### Anything else
Summary:
- Upgrading `kind` from 1.11 to 1.20 has no effect
- Reverting Docker from v25.0 (released Jan 19, which coincides with this issue) to v24.0 has no effect
- Changing Ray version to 2.8.1, 2.9.0, 2.9.1 doesn't affect it

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
Here's the relevant code:

```python
        def download_images():
            """Download Docker images from DockerHub"""
            logger.info("Download Docker images: %s", self.docker_image_dict)
            for key in self.docker_image_dict:
                # Only pull the image from DockerHub when the image does not
                # exist in the local docker registry.
                image = self.docker_image_dict[key]
                if (
                    shell_subprocess_run(
                        f"docker image inspect {image} > /dev/null", check=False
                    )
                    != 0
                ):
                    shell_subprocess_run(f"docker pull {image}")
                else:
                    logger.info("Image %s exists", image)
```

In our output we're seeing "Image exists", which is weird: how could the Buildkite machine already have the Ray 2.9.1 image pulled?

In any case, it looks like one fix would be to always pull the image fresh, or somehow check the hashes and only pull it if the hashes don't match.

**Comment by architkulkarni** [comment]
@kevin85421 actually, can we just eliminate this custom check and always run `docker pull`? It seems that `docker pull` will skip downloading things which already exist locally, so it will still be efficient. And maybe `docker pull` has some built-in way of dealing with this hash issue.

**Comment by kevin85421** [comment]
It makes sense to me. We can avoid the checking.

**Comment by architkulkarni** [comment]
Unfortunately we're still getting the same error, even though it's pulling fresh:
```
2024-01-22:18:49:46,476 INFO     [utils.py:288] Download Docker images: {'ray-image': 'rayproject/ray:2.9.1', 'kuberay-operator-image': 'kuberay/operator:nightly'}
--
  | 2024-01-22:18:49:46,476 INFO     [utils.py:349] Execute command: docker pull rayproject/ray:2.9.1
  | 2.9.1: Pulling from rayproject/ray
  | 521f275cc58b: Pull complete
  | bf72fdb087e6: Pull complete
  | bf1ecb086b72: Pull complete
  | 4f4fb700ef54: Pull complete
  | f38b8e60ced2: Pull complete
  | 86eb5ea39abc: Pull complete
  | cf9fa6809682: Pull complete
  | 0d7128e71fad: Pull complete
  | a849c7c52514: Pull complete
  | Digest: sha256:08f711dffe947bf7aea219066ca8871bc24b78c96ff0450c4f5807d71ba07a23
  | Status: Downloaded newer image for rayproject/ray:2.9.1
  | docker.io/rayproject/ray:2.9.1
  | 2024-01-22:18:50:12,550 INFO     [utils.py:349] Execute command: docker pull kuberay/operator:nightly
  | nightly: Pulling from kuberay/operator
  | e6e98c874e21: Already exists
  | 6350fae67ca1: Pull complete
  | Digest: sha256:7aa36a5d3cda5dc424a7898c075a1883c1771e8ced1e79c2e5fddac08c71c751
  | Status: Downloaded newer image for kuberay/operator:nightly
  | docker.io/kuberay/operator:nightly
  | 2024-01-22:18:50:16,97 INFO     [utils.py:295] Load images into KinD cluster
  | 2024-01-22:18:50:16,97 INFO     [utils.py:349] Execute command: kind load docker-image rayproject/ray:2.9.1
  | Image: "rayproject/ray:2.9.1" with ID "sha256:1b80f2dd7cb3daaafc5fc33a17ad46fe68c02e2fffd6601c7b3b68c86101d394" not yet present on node "kind-control-plane", loading...
  | ERROR: failed to load image: command "docker exec --privileged -i kind-control-plane ctr --namespace=k8s.io images import -" failed with error: exit status 1
  | Command Output: unpacking docker.io/rayproject/ray:2.9.1 (sha256:553e7af4a541619772d531c3b7e1722fdbf9d9a4d43d4255e2a8debc2bbac518)...time="2024-01-22T18:51:33Z" level=info msg="apply failure, attempting cleanup" error="wrong diff id calculated on extraction \"sha256:64dba0d4b6296b5d85b7b8a27a4027bcc37405b7293e868adb5e12f6471c8359\"" key="extract-207399946-OyBF sha256:61b67ada3a810ce6d65ce004a85a36c8d2f7485c89b8330f609e052292b8314e"
  | ctr: wrong diff id calculated on extraction "sha256:64dba0d4b6296b5d85b7b8a27a4027bcc37405b7293e868adb5e12f6471c8359"
```
Very weird

**Comment by architkulkarni** [comment]
Docker was updated from 24.0 to 25.0 on Jan 19, which aligns with when this started failing. And currently KubeRay just pulls the latest Docker version.

I'll pin the Docker version to 24.0 and see if that fixes it.

**Comment by architkulkarni** [comment]
Pinning to 24.0 doesn't work, it results in the same error.

**Comment by kevin85421** [comment]
A workaround is to avoid using `kind load`, as shown in https://github.com/ray-project/kuberay/pull/1862/commits/4a6f13d41a8b1290914e28225a8f9c101f10f661. If we can find the root cause, we can increase the timeout and avoid using `kind load` as a workaround.

**Comment by architkulkarni** [comment]
> A workaround is to avoid using `kind load`, as shown in [4a6f13d](https://github.com/ray-project/kuberay/commit/4a6f13d41a8b1290914e28225a8f9c101f10f661). See [this build](https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/3026#018d3340-b7f4-4846-83a9-2af379ac1dbc) for more details. If we can find the root cause, we can increase the timeout and avoid using `kind load` as a workaround.

@kevin85421 Nice find, I was pretty stuck on this.  But how does the test work if `kind load` isn't there? Is it just that `kind load` is unnecessary because the Ray containers will pull the Ray image on their own if necessary, so it's not needed to preload it in the `kind` cluster?

 I think the priority should be (1) merge the `kind load` workaround to unblock CI, then (2) figure out the root cause and add back `kind load` if necessary.

**Comment by kevin85421** [comment]
> But how does the test work if `kind load` isn't there? Is it just that kind load is unnecessary because the Ray containers will pull the Ray image on their own if necessary, so it's not needed to preload it in the kind cluster?

If a Pod can't find the image on the Kubernetes node (i.e. `kind` node), it will pull images from remote image registry such as DockerHub or Quay. We should determine whether the issue occurs when we use `kind load $KUBERAY_IMAGE`, or if it only happens with `kind load $RAY_IMAGE`. We should still load the KubeRay image to the Kind cluster.

**Comment by architkulkarni** [comment]
It only happens when loading Ray. Loading the KubeRay operator is fine.  

Passing test when only `kind load $RAY_IMAGE` is skipped: https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/3027#018d3381-ae0e-4025-b56b-6cc2d2d4b434

**Comment by architkulkarni** [comment]
> It only happens when loading Ray. Loading the KubeRay operator is fine.
> 
> Passing test when only `kind load $RAY_IMAGE` is skipped: https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/3027#018d3381-ae0e-4025-b56b-6cc2d2d4b434

Actually, it turns out the KubeRay operator failed to load in one case: https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/3028#018d3397-cd40-4ecc-ac10-e1f3e88f1595/251-522

Since CI is now just flaky instead of consistently failing, I'll downgrade the priority to P1.  But we can change it back to P0 if we think it's still too flaky.

**Comment by kevin85421** [comment]
I believe it should remain a P0 priority, given that failures are still common.

**Comment by architkulkarni** [comment]
Sure. One possible clue is that `kind load` isn't failing on Ray CI, although the setup seems to be a bit different (https://github.com/ray-project/ray/pull/41836)

**Comment by architkulkarni** [comment]
Seems related to https://github.com/kubernetes-sigs/kind/issues/3488, it's the same error message.  Maybe I somehow messed up when I tried reverting to Docker 24.0.
