### ISSUE TITLE
[RayJob] Add tests for #1855 

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1866]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

#1855

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
> It may involve significant changes because it needs to execute a command in the head Pod, a process not currently used in the existing RayJob e2e tests.

If we're talking about the `ray job stop`, we might be able to just do it using `JobSubmissionClient.stop_job` inside the Ray job entrypoint itself.
