### ISSUE TITLE
[Feature] What is kuberay's roadmap for 2024 ?

### ISSUE THREAD

**Issue by kadisi** [ray-project/kuberay#1889]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

What does KubeRay look like for 2024?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Hi @kadisi, thank you for the question! If you are interested in the roadmap, you can ping me in the Slack channel or attend our community sync.

**Comment by kevin85421** [comment]
Close this issue. Feel free to reach out to me Slack.
