### ISSUE TITLE
[Docs] Add example docs of using RayJob and Kueue 

### ISSUE THREAD

**Issue by andrewsykim** [ray-project/kuberay#1890]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

After discussing with @kevin85421, it would be helpful to have some documentation on how to use RayJob and Kueue for job priority/premption and gang scheduling.  

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by andrewsykim** [comment]
opened https://github.com/ray-project/ray/pull/42903

**Comment by andrewsykim** [comment]
@jjyao @kevin85421 can we re-open this? I think we still want to a guide for gang scheduling and one using a toy example

**Comment by kevin85421** [comment]
https://github.com/ray-project/ray/pull/43585
