### ISSUE TITLE
[Feature] Allow setting of common values between head and worker pods

### ISSUE THREAD

**Issue by chainlink** [ray-project/kuberay#1934]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

It would be nice to be able to specify things like `containerEnv` once and have the values shared between the head and worker pods.

### Use case

The use case here it to reduce duplication and possible errors when specifying the values for a ray cluster using the helm chart.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by morhidi** [comment]
fyi: in Flink we implemented a layered podTemplate structure:
https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-release-1.7/docs/custom-resource/pod-template/#pod-template
