### ISSUE TITLE
[Feature] Consider using `WithLogConstructor`

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1947]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

https://github.com/ray-project/kuberay/pull/1945#discussion_r1503835776

I don't fully understand `WithLogConstructor` at the moment, so I'm unsure of its benefits. If it clearly offers advantages over the existing solution, we can consider using WithLogConstructor instead.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rueian** [comment]
Sorry for the previous misleading example.

The correct one should be:

```go
// SetupWithManager builds the reconciler.
func (r *RayClusterReconciler) SetupWithManager(mgr ctrl.Manager, reconcileConcurrency int) error {
	b := ctrl.NewControllerManagedBy(mgr).
		For(&rayv1.RayCluster{}, builder.WithPredicates(predicate.Or(
			predicate.GenerationChangedPredicate{},
			predicate.LabelChangedPredicate{},
			predicate.AnnotationChangedPredicate{},
		))).
		Owns(&corev1.Pod{}).
		Owns(&corev1.Service{})

	if EnableBatchScheduler {
		b = batchscheduler.ConfigureReconciler(b)
	}

	return b.
		WithOptions(controller.Options{
			MaxConcurrentReconciles: reconcileConcurrency,
			LogConstructor: func(request *reconcile.Request) logr.Logger {
				return ctrl.Log.WithName("controllers").
					WithName("RayCluster").
					WithValues("RayCluster", request.NamespacedName)
			},
		}).
		Complete(r)
}
```
