### ISSUE TITLE
[Bug]  Issues with installing kuberay with Kustomize

### ISSUE THREAD

**Issue by gushob21** [ray-project/kuberay#1962]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator, apiserver

### What happened + What you expected to happen

**Bug:**
I am using [Config Sync](https://cloud.google.com/anthos-config-management/docs/config-sync-overview) to create Kubernetes resources on my GKE cluster. I have set up a git repository that the  [Config Sync](https://cloud.google.com/anthos-config-management/docs/config-sync-overview) syncs with my cluster to create resources on it. I want to use the same git repository to install kuberay on my cluster with Kustomize. But, I am getting malformed yaml error.

**Expected result:**
The kuberay operator should be installed successfully

**Error:**
error: accumulating resources: accumulating resources from 'https://github.com/ray-project/kuberay/tree/master/ray-operator/config/default': MalformedYAMLError: yaml: line 214: mapping values are not allowed in this context in File: https://github.com/ray-project/kuberay/tree/master/ray-operator/config/default

### Reproduction script

1. Content of the git repository that is connected to the [Config Sync](https://cloud.google.com/anthos-config-management/docs/config-sync-overview):

cloudshell:~/$ ls -lrt
total 4
-rw-r--r-- 1 gushob gushob   0 Mar  4 17:19 README.md
-rw-r--r-- 1 gushob gushob 158 Mar  4 17:47 kustomization.yaml

2. The repo has a kustomzation.yaml that points to the kuberay repo as instructed in [kuberay installation instructions](https://ray-project.github.io/kuberay/deploy/installation/)

cloudshell:~/$ cat kustomization.yaml 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- "https://github.com/ray-project/kuberay/tree/master/ray-operator/config/default"

3. [Config Sync](https://cloud.google.com/anthos-config-management/docs/config-sync-overview) fails with the following error. Below command is my attempt to replicate the error via command line to show that [kubectl command as mentioned in installation instructions](https://ray-project.github.io/kuberay/deploy/installation/) is failing.

cloudshell:~/$ kubectl create -k .
error: accumulating resources: accumulating resources from 'https://github.com/ray-project/kuberay/tree/master/ray-operator/config/default': MalformedYAMLError: yaml: line 214: mapping values are not allowed in this context in File: https://github.com/ray-project/kuberay/tree/master/ray-operator/config/default

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Everything goes well from my side. Does it only happen on ConfigSync?

* Step 1: Create a `kustomization.yaml`.
  ```yaml
  # kustomization.yaml
  resources:
    - github.com/ray-project/kuberay/ray-operator/config/default?ref=v1.1.0
  ```
* Step 2: `kubectl create -k .`

<img width="685" alt="Screen Shot 2024-04-03 at 10 14 12 AM" src="https://github.com/ray-project/kuberay/assets/20109646/f5c9c837-d301-43de-8857-c66b7e416649">

**Comment by kevin85421** [comment]
Sync with the team. Close this issue. Feel free to open a new one or reopen this one if it still exists.
