### ISSUE TITLE
[Feature] Release ray-operator/v1.1.0-rc.0

### ISSUE THREAD

**Issue by tenzen-y** [ray-project/kuberay#1983]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

I'd like to use the RayJob API as a go module, but it seems that the `ray-operator/v1.1.0-rc.0` wasn't released in spite of already cut `v1.1.0-rc.0`.

https://github.com/ray-project/kuberay/tags

### Use case

I'd like to perform `go get github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0` in the external project.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by tenzen-y** [comment]
cc: @andrewsykim @kevin85421 @astefanutti

**Comment by tenzen-y** [comment]
> Interesting, I wonder why #1574 did not work this time 🤔.

I'm not sure why the CI didn't trigger.
@kevin85421 Did you trigger CI against the `ray-operator/v1.1.0-rc.0` tag?

**Comment by kevin85421** [comment]
I ran the following command, and the package seems to exist.

```sh
> go list -m github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0
github.com/ray-project/kuberay/ray-operator v1.1.0-rc.0
```

**Comment by tenzen-y** [comment]
> I ran the following command, and the package seems to exist.
> 
> ```shell
> > go list -m github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0
> github.com/ray-project/kuberay/ray-operator v1.1.0-rc.0
> ```

It's interesting...
In my local, when I ran the command, I can get error:

```
$ go list -m github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0
go: github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0: invalid version: unknown revision ray-operator/v1.1.0-rc.0
```

And I can not find such a tag in https://github.com/ray-project/kuberay/tags.
@astefanutti Could you share the result of `go list -m github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0`?

**Comment by astefanutti** [comment]
Now that @kevin85421 has created the [ray-operator/v1.1.0-rc.1](https://github.com/ray-project/kuberay/releases/tag/ray-operator%2Fv1.1.0-rc.1) tag, here is what I have:

```
$ go list -m github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0
github.com/ray-project/kuberay/ray-operator v1.1.0-rc.0
```

I see the release workflow run successfully this time https://github.com/ray-project/kuberay/actions/runs/8292825124/job/22694778378.

@kevin85421 maybe we could have that workflow triggered on tag creation in addition to manual trigger, WDYT?

**Comment by tenzen-y** [comment]
> Now that @kevin85421 has created the [ray-operator/v1.1.0-rc.1](https://github.com/ray-project/kuberay/releases/tag/ray-operator%2Fv1.1.0-rc.1) tag, here is what I have:
> 
> ```
> $ go list -m github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0
> github.com/ray-project/kuberay/ray-operator v1.1.0-rc.0
> ```
> 
> I see the release workflow run successfully this time https://github.com/ray-project/kuberay/actions/runs/8292825124/job/22694778378.
> 
> @kevin85421 maybe we could have that workflow triggered on tag creation in addition to manual trigger, WDYT?

Oh, for the new release, it can work fine!

```
$ go list -m github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.1
github.com/ray-project/kuberay/ray-operator v1.1.0-rc.1
```

**Comment by kevin85421** [comment]
Both rc.0 and rc.1 exist. I'm not sure why you're unable to get the package locally.
* https://sum.golang.org/lookup/github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0
* https://sum.golang.org/lookup/github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.1

> @kevin85421 maybe we could have that workflow triggered on tag creation in addition to manual trigger, WDYT?

SGTM

**Comment by tenzen-y** [comment]
> Both rc.0 and rc.1 exist. I'm not sure why you're unable to get the package locally.
> 
> * https://sum.golang.org/lookup/github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0
> * https://sum.golang.org/lookup/github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.1
> 
> > @kevin85421 maybe we could have that workflow triggered on tag creation in addition to manual trigger, WDYT?
> 
> SGTM

I tried downloading the `github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0` in 2 PCs and 2 different networks, but it doesn't work well :(

Anyway, I'm ok since the new `rc.1` could be downloaded.

**Comment by tenzen-y** [comment]
> Both rc.0 and rc.1 exist. I'm not sure why you're unable to get the package locally.
> 
> * https://sum.golang.org/lookup/github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0
> * https://sum.golang.org/lookup/github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.1
> 
> > @kevin85421 maybe we could have that workflow triggered on tag creation in addition to manual trigger, WDYT?
> 
> SGTM

It seems that the broken module has been uploaded to the mirror server.

```shell
$ GOPROXY=direct o get github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0
go: downloading github.com/ray-project/kuberay v1.1.0-rc.0
go: github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0: github.com/ray-project/kuberay@v1.1.0-rc.0: verifying module: checksum mismatch
	downloaded: h1:OxdPfF1opn6jovjEQErp+N4oO+ZKMGbbpNAlZSpbOxs=
	sum.golang.org: h1:l0vgglACcxUDa18yJSSgDEqCQY6YiKbkro0GAcY/rD4=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

- https://sum.golang.org/lookup/github.com/ray-project/kuberay/ray-operator@v1.1.0-rc.0

```
23269514
github.com/ray-project/kuberay/ray-operator v1.1.0-rc.0 h1:QZIFpSxxoTFyC64Z6NK+TUCbQqs6PKLj2lCKHsZpLOc=
github.com/ray-project/kuberay/ray-operator v1.1.0-rc.0/go.mod h1:ZqyKKvMP5nKDldQoKmur+Wcx7wVlV9Q98phFqHzr+KY=

go.sum database tree
23724899
g+5VuoMoxTAxblah+r89kpnSf7gg2enNVw9O2DukKG4=

— sum.golang.org Az3grtpRLqW87+B3OV1rY8ExWUXRPGUjdIncEvYnVV3MK0c9T8CiIjFjwZkeq4+6UXPe/B3WFsMeVol9Lzf5KiH6DQg=
```

- I obtained the module hash

```
	downloaded: h1:OxdPfF1opn6jovjEQErp+N4oO+ZKMGbbpNAlZSpbOxs=
	sum.golang.org: h1:l0vgglACcxUDa18yJSSgDEqCQY6YiKbkro0GAcY/rD4=
```
