### ISSUE TITLE
[Feature] Refactor APIServer id and name configuration

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#205]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, even we expose id fields for every object in apiserver, we don't use it for resource identification.  Instead, we use `name`

https://github.com/ray-project/kuberay/blob/ee72afc2125bbebd76ee2834c4ef7599d3b53fcd/proto/cluster.proto#L65

https://github.com/ray-project/kuberay/blob/ee72afc2125bbebd76ee2834c4ef7599d3b53fcd/apiserver/pkg/manager/resource_manager.go#L107-L114

There're some historical reasons we left `id` here. Before the open source version, we internally use UUID as the id. Community forks gave some feedbacks to remove them but we don't have enough time to clean them up prior to open sourcing. Let's make it now. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by blublinsky** [comment]
Not relevant anymore
