### ISSUE TITLE
[Feature] May I ask why is there such a prompt?

### ISSUE THREAD

**Issue by LronDC** [ray-project/kuberay#2055]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

![image](https://github.com/ray-project/kuberay/assets/59912384/81bdf815-975b-4f3c-a195-1c8890d7a1a2)
Reading docs and noticed there is a Kubernetes cluster version request in YAML installation part, 
Will there be any problems if the version is lower than 1.23?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
You can see this PR for more details: https://github.com/ray-project/kuberay/pull/1696. In most cases, versions lower than 1.23 will not have issues. However, in KubeRay v1.2.0, KubeRay may introduce support for the Kubernetes Gateway API, which only guarantees support for at least the five most recent Kubernetes minor versions.
