### ISSUE TITLE
[Bug] Operator don't scale up if replicas in cluster are set to 0 

### ISSUE THREAD

**Issue by EnricoBeltramo** [ray-project/kuberay#2071]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I installed a managed cluster in Azure, with two node pool (one for cpus and one for gpus), and I installed kube-operator and autoscale. 
- When I try follow example:
 https://docs.ray.io/en/latest/cluster/kubernetes/examples/rayjob-batch-inference-example.html#kuberay-batch-inference-example
the operator correctly scale up the cluster and execute the job. Once the job finish, the cluster scale down correctly too.
- When I try follow example: 
 https://docs.ray.io/en/latest/cluster/kubernetes/examples/gpu-training-example.html
the job is correctly executed.
- anyway, in the second case, if I set in ray-cluster.gpu.yaml 
replicas: 0
minReplicas: 0
The operator don't scale up the cluster and the job is not started. The issue looks similar to #321 but I didn't understand if there is a fix.

### Reproduction script

Execute the example described in:
https://docs.ray.io/en/latest/cluster/kubernetes/examples/gpu-training-example.html setting in ray-cluster.gpu.yaml 
replicas: 0
minReplicas: 0

### Anything else

Because I'm using Ray in cloud, my aim is to scale up automatically and free resource when are no longer necessary. How I can do?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
The [YAML file](https://raw.githubusercontent.com/ray-project/ray/master/doc/source/cluster/kubernetes/configs/ray-cluster.gpu.yaml) doesn't enable Ray autoscaling. You need to set `enableInTreeAutoscaling` in your RayCluster YAML. See 
https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/configuring-autoscaling.html#enabling-autoscaling for more details.

**Comment by EnricoBeltramo** [comment]
Thank you. I was expected that writing minReplicas and maxReplicas in configuration files the autoscaling was automaticaly enabled, so I din't add this option. Now it works perfectly.
