### ISSUE TITLE
[Bug] KubeRay Deployment Failure with Large ServeZip File in Working_Dir

### ISSUE THREAD

**Issue by USER-HFC** [ray-project/kuberay#2072]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I am using KubeRay, with the image being ray_ml:2.9.0. I built a serve that is 92MB in size, and I found that when inserting it into the working_dir, the head node does not fully pull the zip file, leading to deployment failure. However, when I switch it to a smaller servezip, this problem does not occur.

### Reproduction script

pass 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
This seems to be a Ray question. Would you mind opening an issue in the Ray repository and cc me in the issue? Thanks!

**Comment by kevin85421** [comment]
Close this one, and track in the Ray repository https://github.com/ray-project/ray/issues/44614.
