### ISSUE TITLE
Kuberay operator failed to watch endpoint

### ISSUE THREAD

**Issue by apurvamishra20** [ray-project/kuberay#2073]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

After installing Kuberay-operation v1.1.0, The kubernetes API started complaining K8s can't watch the endpoint as it is missing in the rbac
pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.Endpoints: unknown (get endpoints) 

### Reproduction script

Ray 2.9.2 
Kuberay: v1.1.0

Deploy any ray serve application on GCP

### Anything else

Although I have not seen this effecting any functionality but it will keep reoccurring every min 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by apurvamishra20** [comment]
Yes! Watch is missing there.

**Comment by kevin85421** [comment]
Good catch! Thanks!
