### ISSUE TITLE
[Feature] Namespaced Operation Support 

### ISSUE THREAD

**Issue by daikeshi** [ray-project/kuberay#209]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

KubeRay currently uses `ray-system` namespace to host Ray clusters by default, and all its operations assume this default namespace. We would like KubeRay to offer namespaced operations. 

### Use case

Users from different teams can use KubeRay to create and manage their Ray clusters in their own namespaces with different resource quota and configurations. 

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
This is reasonable request. The best practice is not to mix data plane workloads with control plane (ray-system) components. We support single namespace for simplification at that moment and this should be definitely extends to multi-namespace

**Comment by DmitriGekhtman** [comment]
> The best practice is not to mix data plane workloads with control plane (ray-system) components.

That makes sense.
It's not strictly necessary to run a namespace-scoped operator in the namespace being managed, so there's no contradiction there.

**Comment by daikeshi** [comment]
>The best practice is not to mix data plane workloads with control plane (ray-system) components.
>It's not strictly necessary to run a namespace-scoped operator in the namespace being managed

I assume we can run operator under `ray-systme` namespace (control plane), and launch Ray clusters in different team namespaces (data plane) right?

**Comment by Jeffwan** [comment]
@daikeshi If you like to make some contributions, you can follow this way

1. We need to make changes to proto definition and introduce namespace field to `ListClustersRequest` or `DeleteClusterRequest` etc.
https://github.com/ray-project/kuberay/blob/master/proto/cluster.proto#L67

2. Follow instruction here https://github.com/ray-project/kuberay/tree/master/proto and generate new pb files.

3. Update `cluster_server.go` and pass namespace to succeeding calls.
https://github.com/ray-project/kuberay/blob/2beb34c15eeaaa92e344bd4ebb4b0116058a4ad9/apiserver/pkg/server/cluster_server.go#L42

4. in `resource_manager.go`, update `DefaultNamespace` to the namespace from the request body.

https://github.com/ray-project/kuberay/blob/2beb34c15eeaaa92e344bd4ebb4b0116058a4ad9/apiserver/pkg/manager/resource_manager.go#L117
