### ISSUE TITLE
[Feature] Upgrade ray version to 2.20

### ISSUE THREAD

**Issue by can-anyscale** [ray-project/kuberay#2112]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Upgrade ray version to 2.20

### Use case

N/A

### Related issues

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
I will not upgrade to Ray 2.20 since there is a bug about Ray Serve. https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1714683469966249
