### ISSUE TITLE
[Feature] RayCluster Helm Chart: Add pod level securityContext in addition to container level securityContext

### ISSUE THREAD

**Issue by arueth** [ray-project/kuberay#2136]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently you can only set the securityContext at the container level with the RayCluster Helm chart.

### Use case

Some compliance tools scan for securityContext at both the Pod and Container level. You should be able to set the securityContext at both levels.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
@arueth Are you interested in opening a PR? Thanks!

**Comment by arueth** [comment]
Do I create a PR against:
https://github.com/ray-project/kuberay/tree/master/helm-chart/ray-cluster
or
https://github.com/ray-project/kuberay-helm/tree/main/helm-chart/ray-cluster

**Comment by kevin85421** [comment]
@arueth, you can open a PR for the KubeRay repository, and I will update kuberay-helm when preparing for the next release.
