### ISSUE TITLE
[Feature] Why RayJob Spec can't set EndpointMemory？

### ISSUE THREAD

**Issue by meibenjin** [ray-project/kuberay#2146]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

As we know, Ray job cli support --entrypoint_memory flag(https://docs.ray.io/en/latest/cluster/running-applications/job-submission/sdk.html#specifying-cpu-and-gpu-resources).

My question is If there some reason why RayJob Spec can't set entrypointMemory ?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
You can set anything you want in `submitterPodTemplate`. See https://docs.ray.io/en/latest/cluster/kubernetes/getting-started/rayjob-quick-start.html for more details.

**Comment by kevin85421** [comment]
Close this issue. If https://github.com/ray-project/kuberay/issues/2146#issuecomment-2116218259 doesn't answer your question, feel free to let me know and reopen the issue.

**Comment by Moonquakes** [comment]
Hi @kevin85421 , I also have this requirement (entrypointMemory) and hope to set the memory parameters of the driver task. If it is based on the submitterPodTemplate, I think it is a bit too troublesome to implement. Can the next version of kuberay support this parameter? I understand that the development cost should not be very high?
