### ISSUE TITLE
[Feature] Checkpoint API to recover from checkpoint from previous runs

### ISSUE THREAD

**Issue by sathyanarays** [ray-project/kuberay#2155]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Steps to reproduce
There are examples that illustrate checkpointing and recovering from checkpointing in the Ray training frameworks. One such [example](https://docs.ray.io/en/latest/train/user-guides/checkpoints.html) illustrates how to configure checkpointing to a pytorch training job.

#### 1. Trigger the training RayJob

```
 kubectl apply rayjob.yaml

```

#### 2. Kill the head pod
Let the training job make a couple of checkpoints and then kill the head pod.

```
kubectl delete pods rayjob-sample-raycluster-lv85g-head-tbfwq

```

#### 3. The new driver ignores the checkpoint
The current driver pod errors out and a new driver pod gets created. The new driver pod runs the training job again from scratch ignoring the checkpoints produced in the last run.

### Hacky Fix

To overcome this problem, we have to write a function with a tightly coupled logic. For example, look at the function `findLatestCheckpoint` in [this](https://gist.github.com/sathyanarays/c1cad159bc5f438b17431b6d75019de8) job definition.

### Use case

It would be great if we have an API that we can call and get the latest checkpoint location for the previous iteration of the given run.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
What is the relationship between this issue and KubeRay? It seems like a Ray Train issue.

**Comment by sathyanarays** [comment]
Closing as this is covered by https://docs.ray.io/en/latest/train/user-guides/fault-tolerance.html#auto-resume
