### ISSUE TITLE
[Feature] Allow setting `ttlSecondsAfterFinished` for RayJob submitter Job

### ISSUE THREAD

**Issue by mickvangelderen** [ray-project/kuberay#2187]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

The RayJob cluster can be cleaned up by setting `spec.shutdownAfterJobFinishes: true`, but I can not figure out how to clean up the RayJob itself including the submitter k8s Job.

I am not familiar with Go, but browsing the source code a bit, it seems like this can be realized in [createNewK8sJob](https://github.com/ray-project/kuberay/blob/40a946a57f9aae943d7deae13a54bb1ec6288621/ray-operator/controllers/ray/rayjob_controller.go#L419-L457). The `backoffLimit` can be set through `submitterConfig`, perhaps the `shutdownAfterJobFinishes` field can just be added to that type and used in `createNewK8sJob`? That would not delete the RayJob resource though.

### Use case

I want the RayJob cluster, the RayJob and the submitter k8s Job to be cleaned up automatically. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by andrewsykim** [comment]
FYI there's a PR for this already https://github.com/ray-project/kuberay/pull/2097

**Comment by mickvangelderen** [comment]
Dang, my bad. Thanks. Closing as duplicate of https://github.com/ray-project/kuberay/issues/1944.
