### ISSUE TITLE
[Bug] Unable to open a custom application port 

### ISSUE THREAD

**Issue by anovv** [ray-project/kuberay#2203]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator, Others

### What happened + What you expected to happen

I have an actor listening on TCP port for incoming connections from other actors on different nodes - they locate the actor by `node-ip:port` address (ZMQ transport). When running locally (on local Ray instance, actors in the same node) everything works fine, but fails when running in Kubernetes.

I figured the issue is exposing the port, so added following to helm chart:

```
worker:
  ports:
    - containerPort: 1234
      name: 'test-tcp'
```

Unfortunately this did not seem to fix the problem. 

What am I doing wrong?

### Reproduction script

I ran a sample test

- Run in shell of a pod (node_a, node_ip=10.244.3.21) to start a simple http server
```
>>> from http.server import HTTPServer, SimpleHTTPRequestHandler
>>> httpd = HTTPServer(('localhost', 1234), SimpleHTTPRequestHandler)
>>> httpd = HTTPServer(('localhost', 1234), SimpleHTTPRequestHandler)
>>> httpd.serve_forever()

```
- Run in the same pod (different shell, previous is blocked):
```
>>> import requests
>>> requests.get('http://localhost:1234').text
'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n<title>Directory listing for /</title>\n</head>\n<body>\n<h1>Directory listing for /</h1>\n<hr>\n<ul>\n<li><a href=".bash_logout">.bash_logout</a></li>\n<li><a href=".bashrc">.bashrc</a></li>\n<li><a href=".cache/">.cache/</a></li>\n<li><a href=".conda/">.conda/</a></li>\n<li><a href=".profile">.profile</a></li>\n<li><a href=".sudo_as_admin_successful">.sudo_as_admin_successful</a></li>\n<li><a href=".whl/">.whl/</a></li>\n<li><a href="anaconda3/">anaconda3/</a></li>\n<li><a href="pip-freeze.txt">pip-freeze.txt</a></li>\n<li><a href="requirements_compiled.txt">requirements_compiled.txt</a></li>\n</ul>\n<hr>\n</body>\n</html>\n'
```
this works fine

```
>>> requests.get('http://10.244.3.21:1234').text
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/ray/anaconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/ray/anaconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```
this fails

You can see that server works (localhost based request works), but using node_ip + port fails

- Similarly in another pod
```
>>> requests.get('http://10.244.3.21:1234').text
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/ray/anaconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/ray/anaconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

Using node_ip+port from another node/pod fails as well

### Anything else

I'm running minikube on m2 mac. KubeRay 1.1.1 , Ray 2.22.0

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by anovv** [comment]
Also separate issue is that if setting `worker.ports `on head node spec it overrides all existing ports (dashboard, prometheus, client, etc.) instead of appending it

**Comment by andrewsykim** [comment]
Just to clarify, when you say node_ip + port, you are referring to the pod IP and not the Kubernetes node right?

**Comment by anovv** [comment]
Correct pod_ip == node_ip here, not kubernetes node

**Comment by andrewsykim** [comment]
Your example code is binding the server to localhost:
```
>>> from http.server import HTTPServer, SimpleHTTPRequestHandler
>>> httpd = HTTPServer(('localhost', 1234), SimpleHTTPRequestHandler)
>>> httpd = HTTPServer(('localhost', 1234), SimpleHTTPRequestHandler)
>>> httpd.serve_forever()
```

Which explains why you can only reach it from localhost. Can you run it with `0.0.0.0` and test it again?

**Comment by anovv** [comment]
Thanks @andrewsykim, this solved the issue, it works now. Also figured you don't even need to add ports to `worker.ports`, any port works without any configuration on Kubernetes side.

**Comment by kevin85421** [comment]
@anovv Can I close this issue?

**Comment by anovv** [comment]
@kevin85421, closed, thanks!
