### ISSUE TITLE
[Feature] Rayjob GitHub Enterprise integration

### ISSUE THREAD

**Issue by HCharlie** [ray-project/kuberay#2204]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Rayjob take care of the ray cluster creation, code submission, and cluster decommision. My goal is to have a disposable way to create jobs without worrying about the cluster resource provision and decommision. In an ideal world,  everytime I only need apply the rayjob manifest, I could get the result and it's done. However, in the [official documentation](https://docs.ray.io/en/latest/cluster/kubernetes/getting-started/rayjob-quick-start.html), I see it's supporting mounting code as a [configmap](https://raw.githubusercontent.com/ray-project/kuberay/v1.1.1/ray-operator/config/samples/ray-job.sample.yaml), which doesn't look like a scalable solution when the project contains complex file structures. It also supports using git clone from public Github inside the rayjob entrypoint. But I didn't find any information on GitHub Enterprise support/integration, so I would like to have this feature to support more enterprise use cases.  

### Use case

similar to https://github.com/ray-project/kuberay/issues/2200, I also come from an ML platform team, and we would like our users to clone their code from GHE in the rayjob entrypoint, and run the code from there. 

### Related issues

https://github.com/ray-project/kuberay/issues/2200

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by andrewsykim** [comment]
@HCharlie try the tips here? https://docs.ray.io/en/latest/ray-core/runtime_env_auth.html

**Comment by HCharlie** [comment]
nice! this looks like what I am looking for! thanks for the reply! :)

**Comment by HCharlie** [comment]
I see it seems to work on the worker nodes to install some dependencies, will this also work on the entrypoint from the job submisstion job/pod?

**Comment by kevin85421** [comment]
I think this issue is resolved. Close this issue. @HCharlie feel free to reopen the issue if it is not resolved.
