### ISSUE TITLE
[Feature] Expose Cluster State via cluster.status and api response

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#223]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, we have not leveraged state field well in our implementation. This is critical because our caller need detail information to let user know the exact stage the cluster is at. 

1. Define key stage in cluster CRD and emit events.
1. Reuse those information and expose them to apiserver get/list response

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by davidxia** [comment]
@Jeffwan happy to contribute something. Just need someone to sketch out an approach or some tips.

**Comment by daikeshi** [comment]
Thanks @Jeffwan! That's awesome. @scarlet25151 please let @davidxia and me know if there's anything we can help with.

**Comment by scarlet25151** [comment]
Hi @daikeshi and @davidxia , we have designed and implemented some state machine for `raycluster` lifecycle and expose some status like ports and state. Let's discuss more detail about what we have and what you would like for the raycluster lifecycle and then we can start the work, shall we call a meeting?

**Comment by daikeshi** [comment]
Thanks @scarlet25151. Look forward to the collaboration! Let's chat more on the slack.

**Comment by asm582** [comment]
Can we please know the different states that we are planning to expose?

**Comment by scarlet25151** [comment]
@asm582 sure for now we will implement the state, the design would look like in the doc: [kuberay state design](https://docs.google.com/document/d/1NngbRxcT70QhglpG9kS1oS3CkpnQIIERcYdxTLI1RnY/edit#)
