### ISSUE TITLE
[Feature] REP 54: Implement the ReplicaFailures condition

### ISSUE THREAD

**Issue by rueian** [ray-project/kuberay#2232]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

This is one of the tracking items of the [REP: RayCluster status improvement](https://github.com/ray-project/enhancements/pull/54), the **step 2** in the design doc: https://docs.google.com/document/d/1bRL0cZa87eCX6SI7gqthN68CgmHaB6l3-vJuIse-BrY

We should add information about Pod failures to the new `RayClusterReplicaFailure` condition by 
referring to how the ReplicaSetReplicaFailure does similar things: https://github.com/kubernetes/api/blob/857a946a225f212b64d42c68a7da0dc44837636f/apps/v1/types.go#L912-L915

### Related issues

https://github.com/ray-project/enhancements/pull/54

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Closed by #2259
