### ISSUE TITLE
[CI] Check the consistency between role.yaml and multiple_namespaces_role.yaml

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2233]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

#1711 added the verb `deletecollection` to the `role.yaml`, but didn't add to `multiple_namespaces_role.yaml`. #2231 fixes the issue. In best scenario, we should catch the issue before #1711 got merged.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LeoLiao123** [comment]
Hello, could I take on this issue?

**Comment by kevin85421** [comment]
Closed by #2244
