### ISSUE TITLE
[Feature] REP 54: Don’t assign the rayv1.Failed to the State field

### ISSUE THREAD

**Issue by rueian** [ray-project/kuberay#2234]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

This is one of the tracking items of the [REP: RayCluster status improvement](https://github.com/ray-project/enhancements/pull/54), the **step 2** in the design doc: https://docs.google.com/document/d/1bRL0cZa87eCX6SI7gqthN68CgmHaB6l3-vJuIse-BrY

We should stop writing the `rayv1.Failed` to the `.Status.State` field if [the RayClusterStatusConditions feature gate](https://github.com/ray-project/kuberay/pull/2219) is enabled.

### Related issues

https://github.com/ray-project/enhancements/pull/54
https://github.com/ray-project/kuberay/pull/2219

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rueian** [comment]
Hi @Yicheng-Lu-llll, would you like to take this one?

**Comment by Yicheng-Lu-llll** [comment]
sure
