### ISSUE TITLE
[Refactor] REP 54: Refactor usages of the inconsistentRayClusterStatus function

### ISSUE THREAD

**Issue by rueian** [ray-project/kuberay#2235]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

This is one of the tracking items of the [REP: RayCluster status improvement](https://github.com/ray-project/enhancements/pull/54), the **step 3** in the design doc: https://docs.google.com/document/d/1bRL0cZa87eCX6SI7gqthN68CgmHaB6l3-vJuIse-BrY

As @kevin85421 stated in the design doc, the current status update process in the RayCluster controller is quite random. For example, if some errors are thrown, the function rayClusterReconcile returns immediately and updates some parts of the RayCluster CR status randomly. Sometimes it doesn’t update anything; sometimes it updates Status.State and/or Status.Reason.

We should make sure every reconciliation that has a status change goes through the inconsistentRayClusterStatus function, and we only call r.Status().Update(...) when it returns true.

By doing so, we can then move forward with confidence that future works in the [REP: RayCluster status improvement](https://github.com/ray-project/enhancements/pull/54) will be on track.

### Related issues

https://github.com/ray-project/enhancements/pull/54

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rueian** [comment]
Hi @MortalHappiness, would you like to take this one?

**Comment by MortalHappiness** [comment]
Hi @rueian. Yes. I am glad to take this issue. Can you assign it for me? Thanks.
