### ISSUE TITLE
[Feature] REP 54: Implement the HeadReady condition

### ISSUE THREAD

**Issue by rueian** [ray-project/kuberay#2237]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

This is one of the tracking items of the [REP: RayCluster status improvement](https://github.com/ray-project/enhancements/pull/54), the **step 5** in the design doc: https://docs.google.com/document/d/1bRL0cZa87eCX6SI7gqthN68CgmHaB6l3-vJuIse-BrY

We should implement the new HeadReady condition by referring to the current `utils.IsRunningAndReady`
https://github.com/ray-project/kuberay/blob/a43217bd2864961ee188a134807df57fd06e0a77/ray-operator/controllers/ray/rayservice_controller.go#L1211-L1217

Once the condition is implemented, we should base on it to refactor the `isHeadPodRunningAndReady` function.

### Related issues

https://github.com/ray-project/enhancements/pull/54

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rueian** [comment]
Hi @cchen777, would you like to take on this?

**Comment by cchen777** [comment]
yes @rueian i'd like to take on this !

**Comment by kevin85421** [comment]
Closes #2261
