### ISSUE TITLE
[Feature] REP 54: Re-define rayv1.Ready

### ISSUE THREAD

**Issue by rueian** [ray-project/kuberay#2238]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

This is one of the tracking items of the [REP: RayCluster status improvement](https://github.com/ray-project/enhancements/pull/54), the **step 6** in the design doc: https://docs.google.com/document/d/1bRL0cZa87eCX6SI7gqthN68CgmHaB6l3-vJuIse-BrY

Currently, once the `.Status.State` has been set to `rayv1.Ready`, it keeps `rayv1.Ready` even when the Head pod is gone.

Here, as stated in the design doc, we redefine ready as follows:
* When all Pods in the RayCluster are running for the first time, the RayCluster CR’s Status.State will transition to ready.
* After the RayCluster CR transitions to ready, KubeRay only checks whether the Ray head Pod is ready to determine if the RayCluster is ready.

This new definition is effective only when [the RayClusterStatusConditions feature gate](https://github.com/ray-project/kuberay/pull/2219) is enabled to maintain backward compatibility.

### Related issues

https://github.com/ray-project/enhancements/pull/54
https://github.com/ray-project/kuberay/pull/2219

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by rueian** [comment]
Hi @Yicheng-Lu-llll, would you like to take on this?

**Comment by Yicheng-Lu-llll** [comment]
sure！

**Comment by kevin85421** [comment]
Closed by https://github.com/ray-project/kuberay/pull/2271
