### ISSUE TITLE
[Feature] Add a strict parser for YAMLs in CI

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2254]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

* #2174
* #2239

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LeoLiao123** [comment]
Hi @kevin85421 , Can I take on this issue?
