### ISSUE TITLE
[Feature] Ray 1.12.0 Support

### ISSUE THREAD

**Issue by tianlinzx** [ray-project/kuberay#226]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

v1.12.0 has been officially released. 

In order for KubeRay to work with v1.12.0, we need to check whether we has references to redis-address etc and make sure they can be migrated to address etc.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by wilsonwang371** [comment]
AFAIK, we use `redis-password` which is no longer used in ray 1.11.0 and above. However, this will not cause any error. Ray just ignores this parameter.

regarding `redis-address`, I don't think we use it in kuberay. So generally speaking, we should be able to support ray 1.12.0. But we need to watch closely in case of any other failures.

cc @Jeffwan

**Comment by Jeffwan** [comment]
We need to run some tests and also enable CI for 1.12. I think it's ok to rotate the version and deprecate the oldest one, probably 1.8 now.
