### ISSUE TITLE
[Feature] Support namespace scoped deployment

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#227]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

In our company, we start to limit the access to platform users on Kubernetes cluster. That means, user will only have permission to operate objects in single namespace. cluster level objects like crds, clusterroles, clusterrolerolebings has to be submited to ops team and ask them to apply to the cluster.

In this case, current deployment way doesn't work in one-click. 

```
kubectl apply -k "github.com/ray-project/kuberay/manifests/cluster-scope-resources"
kubectl apply -k "github.com/ray-project/kuberay/manifests/base"
```

We need to provide a kustomize override to limit the kuberay to single specificed namespace for a successful deployment.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wilsonwang371** [comment]
What is our new expectation on this change?
1. Shall we separate `crds, clusterroles, clusterrolerolebings` yamls to different places?
2. are we supposed to change this apply procedure to a two phases? 1. apply `controllers`. 2 apply required `crds, clusterroles, clusterrolerolebings` yamls

**Comment by DmitriGekhtman** [comment]
@wilsonwang371 @Jeffwan we covered this in #258 right?

**Comment by kevin85421** [comment]
Close this issue because it is covered by #258 and #860. Feel free to reopen this issue if I am wrong.
