### ISSUE TITLE
[Bug] Issue with glibc version GLIBC_2.34 and GLIBC_2.32 not found in earlier operator tags

### ISSUE THREAD

**Issue by vaggeliskls** [ray-project/kuberay#2270]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator, ci

### What happened + What you expected to happen

I am encountering an error when trying to execute an operator with any tag earlier than `quay.io/kuberay/operator:40a946a` on both OpenShift and AWS EKS clusters. The error message indicates that specific glibc versions (`GLIBC_2.34` and `GLIBC_2.32`) are not found.

**Error Message:**
```
/manager: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /manager)
/manager: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /manager)
```

### Reproduction script

**Steps to Reproduce**:
1. Deploy the operator with any tag earlier than `quay.io/kuberay/operator:40a946a` on an OpenShift or AWS EKS cluster.
2. Execute the operator.

**Expected Behaviour:**
The operator should execute without errors related to missing glibc versions.
**Actual Behaviour:**
The operator fails to execute, returning the error messages mentioned above.

**Environment**:
1. **OpenShift Cluster**:
   - Single Node installation
   - `ldd --version` output:
     ```
     ldd (GNU libc) 2.34
     ```
   - `/etc/os-release`:
     ```
     VERSION_ID="4.15"
     VARIANT="CoreOS"
     VARIANT_ID=coreos
     PLATFORM_ID="platform:el9"
     PRETTY_NAME="Red Hat Enterprise Linux CoreOS 415.92.202405281402-0 (Plow)"
     ANSI_COLOR="0;31"
     CPE_NAME="cpe:/o:redhat:enterprise_linux:9::coreos"
     HOME_URL="https://www.redhat.com/"
     DOCUMENTATION_URL="https://docs.openshift.com/container-platform/4.15/"
     BUG_REPORT_URL="https://bugzilla.redhat.com/"
     REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
     REDHAT_BUGZILLA_PRODUCT_VERSION="4.15"
     REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
     REDHAT_SUPPORT_PRODUCT_VERSION="4.15"
     OPENSHIFT_VERSION="4.15"
     RHEL_VERSION="9.2"
     OSTREE_VERSION="415.92.202405281402-0"
     ```

2. **AWS EKS Cluster**:
   - `ldd --version` output:
     ```
     ldd (GNU libc) 2.26
     ```
   - `/etc/os-release`:
     ```
     NAME="Amazon Linux"
     VERSION="2"
     ID="amzn"
     ID_LIKE="centos rhel fedora"
     VERSION_ID="2"
     PRETTY_NAME="Amazon Linux 2"
     ANSI_COLOR="0;33"
     CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
     HOME_URL="https://amazonlinux.com/"
     SUPPORT_END="2025-06-30"
     ```

### Anything else

- The issue seems to be related to the glibc version requirements of the /manager binary.
- OpenShift has glibc 2.34, but the error persists, suggesting a potential misconfiguration.
- AWS EKS has glibc 2.26, which is lower than the required version.
- I suspect that this issue is happening due to the use of ubuntu-latest when you build the operator. Probably the ubuntu-latest OS updated automatically as a GitHub runner and made the executable available to the latest OS.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Thanks! I opened a PR to fix the issue https://github.com/ray-project/kuberay/pull/2272.
