### ISSUE TITLE
[Epic][Test] Rewrite sample YAML tests with Golang

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/kuberay#2310]
### Description

Rewrite the [sample YAML tests](https://github.com/ray-project/kuberay/tree/8e3296ea489062bee1cb92a807067440f81dacde/tests), which was originally written in Python, with Golang.

Reasons:
1. Those Python tests are very awkward when they need to interact with the Kubernetes cluster.
2. They are flaky tests.

#### RayCluster
- [x] #2311
- [x] #2431
- [x] #2451

#### RayJob
- [x] #2452

#### RayService
- [x] #2453
- [x] #2483
- [x] #2481
- [x] #2482
- [x] #2455
- [x] #2476

#### Cleanup

- [x] #2506

**Comment by CheyuWu** [comment]
Sorry, wrong referencing
