### ISSUE TITLE
[Question] Clarify how to use `JobSubmissionClient` with jobs created by `RayJob`

### ISSUE THREAD

**Issue by danielgafni** [ray-project/kuberay#2348]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

I would like to use the `ray.job_submission.JobSubmissionClient`'s to interact with the created job: tail logs or stop it if necessary. 

However, the created job is missing `job_id` field, while all `JobSubmissionClient`'s methods require it to be provided (I tried both http and kubernetes job submission methods).

It's unclear to me how to proceed.  Is there something I'm missing here? 

I it ok to patch the `RayJob` Kubernetes object in order to interrupt it? More or less hot it's done [here](https://github.com/ray-project/kuberay/blob/2ac9c44a2ce0eb551235e0f1acd1d30864a5ae37/ray-operator/controllers/ray/rayjob_controller.go#L268)  

### Use case

I'm writing a Pytho SDK & CLI wrapper for `RayJob` and would like to be able to stream logs directly from the ray job and also interrupt it.

**Comment by danielgafni** [comment]
Oh, it looks like `submission_id` can be used as `job_id`.

**Comment by andrewsykim** [comment]
@danielgafni you may find this relevant: https://docs.google.com/document/d/1hCJsrCFYPJLS3Zusdr8N_4Y5leWUMy4bQEbsqSQp2mw/edit?usp=sharing

**Comment by andrewsykim** [comment]
In https://github.com/ray-project/kuberay/pull/2364 we are considering a new submission mode for RayJob where you give it a pre-defiend job ID that needs to be submitted by the user

**Comment by danielgafni** [comment]
@andrewsykim I do find this document really interesting! 

So far, I have implemented a very similar CLI which internally port-forwards (with random ports) and then uses the `JobSubmissionClient` to interact with the submitted job. 

So far it works well for me!

I believe it should be trivial to use the same logic for interactive development, e.g. syncing local scripts. I can try this approach with `RayCluster` right now.
