### ISSUE TITLE
[Bug] Submit a task with kuberay-operator, deliberately let the task fail, found that the submitter will repeatedly create three times, how to turn off this option?

### ISSUE THREAD

**Issue by ming-shy** [ray-project/kuberay#2376]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

The error picture is as follows, the associated submitter will be created three times, I want to turn this option off:
![image](https://github.com/user-attachments/assets/03d407c6-7e3e-4c58-8f27-48c07f5cd69e)

### Reproduction script

**Using the official yaml file [ray-job-sample.yaml], the task was deliberately executed incorrectly.**

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by andrewsykim** [comment]
Starting in v1.2 you can configure how many times we attempt job submission. See `rayjob.spec.submitterConfig.backoffLimit`

**Comment by ming-shy** [comment]
> backoffLimit

According to the information you provided, I have solved the problem, and I am very glad to get your timely reply. @andrewsykim
