### ISSUE TITLE
[Bug] kuberay cannot run long tasks, and service disconnection occurs.

### ISSUE THREAD

**Issue by ming-shy** [ray-project/kuberay#2378]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I started a task, in the normal operation of the process, suddenly appeared the connection access blocked situation how to solve.

The specific error information is as follows（It works for a while）:

![image](https://github.com/user-attachments/assets/1979122e-5af9-4d28-a675-b93674c62316)
![image](https://github.com/user-attachments/assets/1979122e-5af9-4d28-a675-b93674c62316)
![image](https://github.com/user-attachments/assets/1979122e-5af9-4d28-a675-b93674c62316)
![image](https://github.com/user-attachments/assets/94e28297-ba17-4061-b7e0-1a6b61bfe14e)
![image](https://github.com/user-attachments/assets/94e28297-ba17-4061-b7e0-1a6b61bfe14e)
![image](https://github.com/user-attachments/assets/94e28297-ba17-4061-b7e0-1a6b61bfe14e)

### Reproduction script

The official script used is ray-job-sample.yaml. Modify distributed data processing for your own logic.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by andrewsykim** [comment]
What version of KubeRay are you using?

**Comment by kevin85421** [comment]
Which version of Ray are you using? We found some regressions in recent Ray versions. See https://github.com/ray-project/kuberay/issues/2355#issuecomment-2344374832 for more details.

**Comment by han-steve** [comment]
Yeah this looks very similar to the issue we are experiencing. Most likely the head node stops responding to health checks and gets marked as unready.

**Comment by han-steve** [comment]
In the mean time, @kevin85421's suggestion of disabling liveliness and readiness checks works for us.

**Comment by ming-shy** [comment]
Thank you all for your responses. I solved the problem by adding the following line of code with the annotation # activeDeadlineSeconds: 240. I hope there will be more detailed documentation available in the future.

**Comment by ming-shy** [comment]
The problem has been resolved.
