### ISSUE TITLE
[Bug] can not set submitter pod restart times

### ISSUE THREAD

**Issue by xiaoyu1095** [ray-project/kuberay#2393]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

In my scenario, if the execution fails, it should be considered a failure and no retries are needed. However, I cannot disable retries entirely.

### Reproduction script

  submitterPodTemplate:
    spec:
      restartPolicy: Never
      containers:
        - image: harbor.thupx.cn/docker.io/rayproject/ray:2.34.0
          imagePullPolicy: IfNotPresent
          name: ray-job-submitter

<img width="662" alt="image" src="https://github.com/user-attachments/assets/8e65fae6-10d3-4baf-92c3-e5281e7089da">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xiaoyu1095** [comment]
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: test
spec:
  entrypoint: cd /thup/code/runner && python main.py
  jobId: "123"
  submitterPodTemplate:
    spec:
      restartPolicy: Never
      containers:
        - image: harbor.thupx.cn/docker.io/rayproject/ray:2.34.0
          imagePullPolicy: IfNotPresent
          name: ray-job-submitter
  shutdownAfterJobFinishes: true
  rayClusterSpec:
    headGroupSpec:
      rayStartParams:
        dashboard-host: 0.0.0.0
      template:
        spec:
          containers:
            - image: harbor.thupx.cn/docker.io/rayproject/ray:2.34.0
              imagePullPolicy: IfNotPresent
              name: ray-master
              ports:
                - containerPort: 6379
                  name: gcs-server
                  protocol: TCP
                - containerPort: 8265
                  name: dashboard
                  protocol: TCP
                - containerPort: 10001
                  name: client
                  protocol: TCP
                - containerPort: 8000
                  name: serve
                  protocol: TCP
              volumeMounts:
                - mountPath: /thup
                  name: thudx
                - mountPath: /tmp/ray/
                  name: log-volume
    rayVersion: 2.34.0
    workerGroupSpecs:
      - groupName: small-group
        maxReplicas: 1
        minReplicas: 1
        replicas: 1
        rayStartParams: {}
        template:
          spec:
            containers:
              - image: harbor.thupx.cn/docker.io/rayproject/ray:2.34.0
                name: ray-worker
                resources:
                  limits:
                    cpu: 500m
                    memory: 8Gi
                    nvidia.com/gpu: 0
                  requests:
                    cpu: 500m
                    memory: 8Gi
                    nvidia.com/gpu: 0

**Comment by andrewsykim** [comment]
Try setting `submitterConfig.backoffLimit = 0`
