### ISSUE TITLE
[Feature] Disable zero downtime upgrade for a RayService

### ISSUE THREAD

**Issue by smit-kiri** [ray-project/kuberay#2397]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently we have a global flag to disable zero downtime upgrades for ALL RayService resources. It would be great to have a flag in the CRD to disable zero-downtime upgrade for a specific RayService resource.

### Use case

We're managing multiple `RayService` resources, and want to disable zero-downtime upgrade in one of the resources.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by andrewsykim** [comment]
I would be in favor of a new field in RayService to toggle the upgrade policy. We can default it to zero-downtime upgrade for compatibility

**Comment by andrewsykim** [comment]
There are some other proposals floating around for supporting N RayCluster per RayService as well, it might be good to revisit this as part of those proposals.

**Comment by smit-kiri** [comment]
> There are some other proposals floating around for supporting N RayCluster per RayService as well, it might be good to revisit this as part of those proposals.

I would also be in favor of having N RayCluster per RayService!

**Comment by kevin85421** [comment]
Closed by #2468
