### ISSUE TITLE
Use kubebuilder way to build binary and run test in Github CI

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#24]
Currently, we are using following way to build and test code. 

https://github.com/ray-project/ray-contrib/blob/f4076b4ec5bfae4cea6d9b66a1ec4e63680ca366/.github/workflows/test-job.yaml#L47-L53

In ray operator project, we can change to use `make manager` and `make test` instead. The major reason is it can find more problems for us. One example is it may fail to generate manifest which indicates our code is not compatible with controller-tools

**Comment by anencore94** [comment]
Doesn't this issue resolved by #31 ?

**Comment by Jeffwan** [comment]
@anencore94 Hi, this has been supported and we didn't get a chance to close the issue. Thanks for your reminder.
