### ISSUE TITLE
[Bug] Yunikorn logger doesn't add context info

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2408]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Ensure that all log messages are in JSON format and include context. For example, some logs from controller-runtime are not in JSON format, and the YuniKorn logger does not add context (such as CR name, namespace, or reconcile ID) to log messages

https://github.com/ray-project/kuberay/pull/2396/files#r1777912678

### Reproduction script

https://github.com/ray-project/kuberay/pull/2396/files#r1777912678

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by win5923** [comment]
Hi @kevin85421, Can I take on this issue?
