### ISSUE TITLE
[Feature] Add a feature gate for `submissionMode: UserMode` for v1.3.0

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2418]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

KubeRay v1.2.2 is a special release that is exclusive to Ray Summit. We don't have enough time to follow our API conventions. For v1.3.0, we should add a feature gate for `submissionMode`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by andrewsykim** [comment]
@kevin85421 since the new API is available v1.2.2 it probably doesn't make sense to add a feature gate for v1.3, unless we re-release v1.2.2. I'm okay to close this one, what do you tihnk?

**Comment by kevin85421** [comment]
I think either adding or not adding a feature gate is fine with me. UserMode should only be used by the Kubectl plugin, which is in alpha status, meaning we can still update the API.
