### ISSUE TITLE
[Bug] KubeRay operator error if installed with helm chart with value `batchScheduler.name` set to `volcano`

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/kuberay#2428]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

If KubeRay is installed via `helm install kuberay-operator kuberay/kuberay-operator --version 1.2.2 --set batchScheduler.name=volcano`, the following error will occur:

```
{"level":"info","ts":"2024-10-06T03:16:19.757Z","logger":"setup","msg":"Feature flag batch-scheduler is enabled","scheduler name":"volcano"}
{"level":"info","ts":"2024-10-06T03:16:19.757Z","logger":"setup","msg":"Loaded feature gates","featureGates":{"RayClusterStatusConditions":false}}
{"level":"info","ts":"2024-10-06T03:16:19.757Z","logger":"setup","msg":"Flag watchNamespace is not set. Watch custom resources in all namespaces."}
{"level":"info","ts":"2024-10-06T03:16:19.757Z","logger":"setup","msg":"Setup manager"}
panic: podGroup CRD is required to exist in current cluster. error: customresourcedefinitions.apiextensions.k8s.io "podgroups.scheduling.volcano.sh" is forbidden: User "system:serviceaccount:default:kuberay-operator" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope

goroutine 1 [running]:
github.com/ray-project/kuberay/ray-operator/controllers/ray.NewReconciler({_, _}, {_, _}, {{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}}, ...)
    /home/runner/work/kuberay/kuberay/ray-operator/controllers/ray/raycluster_controller.go:114 +0x30b
main.main()
    /home/runner/work/kuberay/kuberay/ray-operator/main.go:226 +0x12c8
Stream closed EOF for default/kuberay-operator-68f8d7665b-786rb (kuberay-operator)

```

### Reproduction script

- Install volcano first via `helm install volcano volcano-sh/volcano -n volcano-system --create-namespace`
- Run  `helm install kuberay-operator kuberay/kuberay-operator --version 1.2.2 --set batchScheduler.name=volcano`
- Check the log of the operator

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by tinaxfwu** [comment]
Hi @MortalHappiness, I can help with this issue.

**Comment by kevin85421** [comment]
https://github.com/ray-project/kuberay/blob/release-1.2.2/helm-chart/kuberay-operator/templates/_helpers.tpl#L335 

We should add `podgroup` to the Role or ClusterRole when using Volcano.

**Comment by kevin85421** [comment]
@MortalHappiness can you take this issue? We should fix this as soon as possible.
