### ISSUE TITLE
Using RayJob with existing Ray cluster

### ISSUE THREAD

**Issue by aybidi** [ray-project/kuberay#2429]
We are looking into using RayJob with existing Ray cluster, instead of a creating a new Ray cluster each time.

In the [docs](https://docs.ray.io/en/latest/cluster/kubernetes/getting-started/rayjob-quick-start.html), it doesn't mention that it could be done. However, I see the field [clusterSelector](https://github.com/ray-project/kuberay/blob/35e913a9b96e84b8e4a41ebe1efc6e656420afbd/ray-operator/apis/ray/v1/rayjob_types.go#L86), which seems to be for using an existing cluster.

- Is it a supported use case for RayJob to submit a job to an existing cluster instead of creating a new one?
- If yes, are there docs that talk about the instructions and best practices?
- If not then what architectural design decisions prompted this?

**Comment by andrewsykim** [comment]
> Is it a supported use case for RayJob to submit a job to an existing cluster instead of creating a new one?

Yes, this is supported. But you need to use the ray.io/cluster label, which I think is a bit confusing and not well documented.

> If yes, are there docs that talk about the instructions and best practices?

I don't recall seeing any docs on this, we should add something.
