### ISSUE TITLE
[Bug] RayService stay in Restarting status forever during zero-downtime upgrade if headService.metadata.name is set

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/kuberay#2433]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When `spec.rayClusterConfig.headGroupSpec.headService.metadata.name` is set to a non-empty string in RayService, a zero-downtime upgrade failed. The RayService stays in `Restarting` status forever.

The root cause is that 2 RayClusters are created but their `spec.headGroupSpec.headService.metadata.name` are the same, so the k8s service for the new RayCluster cannot be created.

### Reproduction script

- Set `spec.rayClusterConfig.headGroupSpec.headService.metadata.name` to a non-empty string in `ray-operator/config/samples/ray-service.sample.yaml` and then `kubectl apply` it.
- Wait for the RayService becomes ready.
- Set `spec.rayClusterConfig.rayVersion` to a different value to trigger a zero-downtime upgrade
- Find that `rayservice-name` stays in `Restarting` status forever.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by dcela** [comment]
Discovery thread - https://ray.slack.com/archives/C02GFQ82JPM/p1728531326207399?thread_ts=1724853766.667949&cid=C02GFQ82JPM
