### ISSUE TITLE
[Feature] Add an event on KubeRay CR if the validation fails

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2437]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, if a CR fails the validation function (e.g. `validateRayJobSpec`), we only log an error and requeue it. We can consider filing a CR event so that users can use `kubectl describe` to find the issue instead of checking KubeRay operator's log.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @rueian can you add this into the KubeRay observability roadmap? Thanks!

**Comment by rueian** [comment]
Sure, I added. I can also address this today.
