### ISSUE TITLE
[Feature][kubectl-plugin] Also show kuberay operator version in kubectl ray version command

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/kuberay#2439]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently `kubectl ray version` only shows the version of itself. We can dynamic query the kuberay operator version and show it to users.

Expected behavior:

If kuberay operator is installed:
```
$ kubectl ray version
kubectl ray plugin version: vx.x.x
kuberay operator version: vy.y.y
```

If kuberay operator is not installed or cannot be found:
```
$ kubectl ray version
kubectl ray plugin version: vx.x.x
Warning: kuberay operator installation cannot be found - did you install it with the name "kuberay-operator"?
```

Implementation Details:

- Get the kuberay-operator deployment using the `app.kubernetes.io/name` label. (If installed via helm chart, this value is `kuberay-operator`. If installed via kusotmize, this value is `kuberay`)
- Parse the image tag from the pod template of this deployment to get the version.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by win5923** [comment]
Hi @MortalHappiness, I can help with this issue.
