### ISSUE TITLE
Check RayCluster `ray job submit` can successfully create a job by running it in the head Pod

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/kuberay#2451]
This is a subtask of https://github.com/ray-project/kuberay/issues/2310. See the parent issue for more information.

## Implementation Details

- Implement the `EasyJobRule` here with Golang. 
  https://github.com/ray-project/kuberay/blob/e5dc0f802e48e2c851f8de0a0736565a6340b8d5/tests/framework/prototype.py#L247-L253
- Implement this check as a utility function so that other tests can use it
- Add the test after this line
  https://github.com/ray-project/kuberay/blob/e5dc0f802e48e2c851f8de0a0736565a6340b8d5/ray-operator/test/sampleyaml/raycluster_test.go#L90

**Comment by CheyuWu** [comment]
Hi @MortalHappiness I'd like to help with this
