### ISSUE TITLE
Check RayJob successfully create RayCluster

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/kuberay#2452]
This is a subtask of https://github.com/ray-project/kuberay/issues/2310. See the parent issue for more information.

Check:
- The underlying RayCluster created the correct number of Pods and ready
- https://github.com/ray-project/kuberay/blob/5cb2f56b9d3eebbadbeb0aec70dfd30a9d5dab83/ray-operator/apis/ray/v1/rayjob_types.go#L40
- https://github.com/ray-project/kuberay/blob/5cb2f56b9d3eebbadbeb0aec70dfd30a9d5dab83/ray-operator/apis/ray/v1/rayjob_types.go#L20

**Comment by fscnick** [comment]
Hi @MortalHappiness , could I help with this issue?
