### ISSUE TITLE
[TBD] Implement `CurlServiceRule` with golang for RayService

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/kuberay#2455]
This is a subtask of https://github.com/ray-project/kuberay/issues/2310. See the parent issue for more information.

## Implementation Details

- Implement the `CurlServiceRule` here with Golang. 
  https://github.com/ray-project/kuberay/blob/e5dc0f802e48e2c851f8de0a0736565a6340b8d5/tests/framework/prototype.py#L287-L322
- Needs to wait for https://github.com/ray-project/kuberay/issues/2453

**Comment by win5923** [comment]
Hi @MortalHappiness, I can help.

**Comment by kevin85421** [comment]
don't need to do this. close this one.
