### ISSUE TITLE
[Refactor] Rewrite ExecPodCmd with client-go remotecommand package

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/kuberay#2462]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

In

https://github.com/ray-project/kuberay/blob/1213d1578ac08a5fc993e2f1eb34fa021fe07749/ray-operator/test/support/core.go#L63-L71

we called external `kubectl` command.

It's better to use the [remotecommand](https://pkg.go.dev/k8s.io/client-go/tools/remotecommand) package from `client-go` because this can remove dependencies for external command.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by MortalHappiness** [comment]
@CheyuWu would you want to do this? Because this is found while reviewing https://github.com/ray-project/kuberay/pull/2459

**Comment by CheyuWu** [comment]
Hi @MortalHappiness  I'd like to help with this
