### ISSUE TITLE
Check all applications in Ray Serve are running

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/kuberay#2482]
Ref:

- https://github.com/ray-project/kuberay/blob/5cb2f56b9d3eebbadbeb0aec70dfd30a9d5dab83/ray-operator/controllers/ray/rayservice_controller.go#L912
- https://github.com/ray-project/ray/blob/1e5c5829be3c56adca9d0f7b98a8a7e2ffd3f00c/src/ray/protobuf/serve.proto#L280

**Comment by win5923** [comment]
Hi @MortalHappiness, I can help.
