### ISSUE TITLE
[Feature] Some client-go logs are not in JSON format

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2512]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Some logs from client-go are not in JSON format. For example,

<img width="1439" alt="Screenshot 2024-11-06 at 9 25 39 PM" src="https://github.com/user-attachments/assets/8e4a042c-c0e5-47a3-9934-372617b94acc">

https://github.com/kubernetes/client-go/blob/v0.31.2/tools/leaderelection/leaderelection.go#L254

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by EagleLo** [comment]
Hi @kevin85421 , I can take on this issue.

**Comment by fscnick** [comment]
Hi @kevin85421, I'd like to help with this issue.
