### ISSUE TITLE
[Doc] Write a doc for persisting KubeRay operator log

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2513]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, Ray website has [a logging doc](https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/logging.html#kuberay-logging) to describe how to persist Ray logs. However, there is no doc to persist KubeRay operator logs. 

Add a doc to the Ray website (Ray repository).

It's better to discuss with me how you plan to persist KubeRay logs before starting to write the documentation.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by win5923** [comment]
Is this just an example showing how to persist KubeRay Operator logs, right? If so, I recommend Grafana Loki + promtail. It’s not too difficult to deploy and integrates well with Grafana.

https://grafana.com/docs/loki/latest/get-started/overview/

**Comment by kevin85421** [comment]
> Is this just an example showing how to persist KubeRay Operator logs, right?

yes

> If so, I recommend Grafana Loki + promtail. It’s not too difficult to deploy and integrates well with Grafana.

maybe start from `FluentBit` first to make it consistent with https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/logging.html#kuberay-logging?

**Comment by kevin85421** [comment]
Closed by https://github.com/ray-project/ray/pull/48725
