### ISSUE TITLE
[Feature] Revisit Ray logging doc

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2515]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

* P0
  * TODO: Delete the sections from "Set up logging on a DaemonSet with Fluent Bit" to "Check the CloudWatch dashboard".
    * The section that installs FluentBit via DaemonSet only persists logs from STDOUT/STDERR. However, most Ray logs are located in /tmp/ray/session_latest. See [this comment](https://github.com/ray-project/ray/pull/39895#pullrequestreview-1669385697) for more details. 
  * TODO: sidecar solution
    * The FluentBit sidecar container redirects logs from `/tmp/ray/session_latest/logs` to Grafana Loki.
  * TODO: Allow users to associate logs from different RayCluster / RayJob CRs

* P1
  * TODO: Use Configuration API ([code](https://github.com/ray-project/kuberay/blob/40f5ddbbe32caf8b4631a292e018096280ce7a0c/ray-operator/apis/config/v1alpha1/configuration_types.go#L50-L56)) to set up the logging container instead of configuring each custom resource.
  * ~~Consider removing the section for `RAY_LOG_TO_STDERR=1`.~~ (https://github.com/ray-project/kuberay/issues/2515#issuecomment-2476761824)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by mtralka** [comment]
@kevin85421 could you please elaborate on the idea behind removing `RAY_LOG_TO_STDERR` from the documentation? Does this demonstrate a longer-term shift in support for logging to stderr / stdout?

My team uses this flag extensively as we use an external Grafana stack to scrape stdout / stderr workload logs. We intentionally don't want to write to log files on disk and we do not need dashboard / driver log redirection in production.

**Comment by kevin85421** [comment]
> My team uses this flag extensively as we use an external Grafana stack to scrape stdout / stderr workload logs. We intentionally don't want to write to log files on disk and we do not need dashboard / driver log redirection in production.

Good to know. In that case, maybe we should leave the section there after all. I considered removing it from the doc because it will cause some dashboard features don't work.

**Comment by kevin85421** [comment]
@win5923 will take this issue.
