### ISSUE TITLE
[Feature] Implement RayService In-place update test in Golang

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2516]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Implement `test_in_place_update` in Golang, and add a file `rayservice_in_place_update_test.go` under https://github.com/ray-project/kuberay/tree/master/ray-operator/test/e2e.

https://github.com/ray-project/kuberay/blob/4fc17996bb7aedb06d4fc02727f1ca24c86f4090/tests/test_sample_rayservice_yamls.py#L205

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by CheyuWu** [comment]
@kevin85421  I 'd like to help with this
