### ISSUE TITLE
[Umbrella] Remove RayService sample YAML Python tests

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2518]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Remove RayService sample YAML Python tests like #2507 after 
* #2517 
* #2516 

are merged.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by CheyuWu** [comment]
@kevin85421  I'd like to help with this
