### ISSUE TITLE
[Feature] Remove the permission to patch pods for autoscaler

### ISSUE THREAD

**Issue by KunWuLuan** [ray-project/kuberay#2551]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

I didn't find the code to patch pod in ray-autoscaler. So I think maybe the permission to patch pods can be removed.

Please correct me if autoscaler has to patch pods.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by andrewsykim** [comment]
@KunWuLuan can you run a quick test where you remove patch pods permission and then see if autoscaling works?

**Comment by KunWuLuan** [comment]
Yes, I tested the functionality after remove the permission of patch pods and the autoscaler seemed to work well. @andrewsykim .

**Comment by kevin85421** [comment]
@KunWuLuan how do you test it? The autoscaler uses patch here: https://github.com/ray-project/ray/blob/52b07685e744e5d72a6c0691e015a74aebb9bca9/python/ray/autoscaler/_private/kuberay/node_provider.py#L531

**Comment by andrewsykim** [comment]
> @KunWuLuan how do you test it? The autoscaler uses patch here: https://github.com/ray-project/ray/blob/52b07685e744e5d72a6c0691e015a74aebb9bca9/python/ray/autoscaler/_private/kuberay/node_provider.py#L531

This is patching RayCluster, not Pod right?

**Comment by kevin85421** [comment]
> This is patching RayCluster, not Pod right?

Oh yeah, I don't read the issue description carefully. @KunWuLuan would you mind opening a PR to fix it? Thanks!
