### ISSUE TITLE
[Feature] How to deploy a RayService with deployment to exist RayCluster ?

### ISSUE THREAD

**Issue by xushaoxiao** [ray-project/kuberay#2560]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Hi teams, i want to deploy directly a application via rayservice to exist raycluster, what can do it ?

Now exist:
<img width="343" alt="image" src="https://github.com/user-attachments/assets/cab13439-4189-4059-a41a-a738f1902f51">

<img width="481" alt="image" src="https://github.com/user-attachments/assets/a456a9f0-e318-47bd-a2f1-637ab2ff1ef9">

### Use case

You can asume i have a new application serving by rayserve, the name is **rayservice-app-one** .

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xushaoxiao** [comment]
> You can connect to the Ray cluster and then use `serve run` to deploy your serve applications

via common "deployment" to kuberay cluster

**Comment by kevin85421** [comment]
For prototyping, you can run `serve run`. However, for production, you should create a RayService CR with a new RayCluster. To achieve RayService high availability, all Pods must be configured with readiness probes which are different from RayCluster CR.

**Comment by kevin85421** [comment]
feel free to reopen the issue if the reply doesn't answer your questions.
