### ISSUE TITLE
[Feature] Add e2e tests for Autoscaler V2

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2574]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, [Autoscaler e2e tests](https://github.com/ray-project/kuberay/blob/master/ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go) in KubeRay repo are only for Autoscaler V1. We should also test V2. 

Check here to see how to configure Autoscaler V2: https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/configuring-autoscaling.html#kuberay-autoscaling

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by simotw** [comment]
Hi @kevin85421 I would like to work on this.
