### ISSUE TITLE
[Feature] Add an e2e test for Autoscaler to scale up by manually updating `minReplicas`

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2576]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Users may manually update `minReplicas` to a value greater than `replicas`. Then, KubeRay will create new Pods to ensure the worker group has `$minReplicas` Pods. It's the Autoscaler's duty to update `replicas` to ensure it is equal to or greater than `minReplicas`.

For this test,

* Create a RayCluster with the Autoscaler enabled, containing a worker group with `replicas: 1` and `minReplicas: 0`.
* Update `minReplicas` from 0 to 2.
* KubeRay should create an additional Pod.
* Submit some Ray detached actors to trigger autoscaling to 5 Pods.
* Verify whether the Autoscaler successfully scales up to 5 Pods.
* Check whether `replicas` is set to 5.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LeoLiao123** [comment]
Hi @kevin85421 , I would like to take on this issue.
