### ISSUE TITLE
[Feature] RayService HA test - GCS fault tolerance + kill GCS process

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2577]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

* Create a RayService with GCS FT enabled. No Ray Serve replica should be deployed on the head Pod.
* Kill the GCS process on the head Pod `pkill gcs_server`.
* Wait until the head Pod is removed from the K8s serve service.
* Use locust to submit requests until the new Ray head is running and ready for 30 seconds.
* No request should be dropped.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by CheyuWu** [comment]
@kevin85421  I'd like to help with this
