### ISSUE TITLE
[Feature] Add a field to configure whether to add a proxy actor on the head Pod to the K8s serve service or not

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2593]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

If the proxy actor on the head Pod is included in the K8s serve service, it is highly likely that some requests will be dropped when GCS is down.

Add a field in [RayService CRD](https://github.com/ray-project/kuberay/blob/master/ray-operator/apis/ray/v1/rayservice_types.go) to control whether to add a proxy actor on the head Pod to the K8s serve service or not. If the field is configured, the value of the label `ray.io/serve` on the head Pod should always be false https://github.com/ray-project/kuberay/blob/master/ray-operator/controllers/ray/rayservice_controller.go#L1193.

With this field, no request should be dropped in the test https://github.com/ray-project/kuberay/issues/2577.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by CheyuWu** [comment]
@kevin85421  I'd like to help with this
