### ISSUE TITLE
[Feature] How to avoid duplicate pip package installation when enabled autoscaler

### ISSUE THREAD

**Issue by zjj2wry** [ray-project/kuberay#2594]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

My ray cluster enabled autoscaler . When there are no tasks being executed, the workers will be scaled down. When re-running, the pip package must be re-installed.

### Use case

code in my notebook
```
import ray
import time

ray.shutdown()

# Specify the runtime environment
ray.init(runtime_env={
    "env_vars": {"PIP_INDEX_URL": "https://mirrors.aliyun.com/pypi/simple/"},
    "pip": {
        "packages": ["torch"],  # Specify the required packages
    } 
})

# Specify that this task requires one GPU and 2Gi of GPU memory
@ray.remote(num_gpus=1, resources={"aliyun.com/gpu-mem": 2})
def gpu_task():
    import torch
    # Simulate a computation task that requires a GPU
    x = torch.rand(10000, 10000).cuda()  # Transfer data to the GPU
    y = torch.mm(x, x)  # Matrix multiplication
    return y.sum().item()

# Submit the task
future = gpu_task.remote()
result = ray.get(future)

print("Result:", result)

# Shut down Ray
ray.shutdown()

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Hi @zjj2wry, if a dependency is commonly used, it'd better to bake the dependency in the container image.

**Comment by kevin85421** [comment]
Close this issue. Feel free to reopen the issue if it doesn't answer your question.

**Comment by zjj2wry** [comment]
> Hi @zjj2wry, if a dependency is commonly used, it'd better to bake the dependency in the container image.

ok, thanks
