### ISSUE TITLE
[Refactor] Remove redundant `test.T().Run`

### ISSUE THREAD

**Issue by MortalHappiness** [ray-project/kuberay#2609]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Some tests call `test.T().Run` only once, which is redundant.

https://github.com/ray-project/kuberay/blob/1ced2b968eabcfee4dcfa61391d307b60e46a2ed/ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go#L94

Calling another `t.Run` inside a test function is meaningful only when we need to run multiple test cases, as shown in the following example:

https://github.com/ray-project/kuberay/blob/1ced2b968eabcfee4dcfa61391d307b60e46a2ed/ray-operator/controllers/ray/rayjob_controller_unit_test.go#L225-L226

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by tinaxfwu** [comment]
Hi @MortalHappiness, I would like to contribute to this issue.

**Comment by MortalHappiness** [comment]
Closed this because I found that only `raycluster_autoscaler_test.go` has redundancy, and https://github.com/ray-project/kuberay/pull/2588 will remove it.
