### ISSUE TITLE
[Feature] Make RayCluster Helm chart and `ray-cluster.sample.yaml` consistent

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2616]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

https://github.com/ray-project/ray/pull/49085 adds instructions for installing the KubeRay operator and RayCluster CR without Helm. However, they are not consistent. For example, the name of the CR is different.

1. Update `ray-cluster.sample.yaml` to ensure that https://anyscale-ray--49085.com.readthedocs.build/en/49085/cluster/kubernetes/getting-started/raycluster-quick-start.html works regardless of whether users use Helm or Kustomize.

2. Update the `raycluster-quick-start` doc to use the YAML on the master branch instead.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by fscnick** [comment]
Hi @kevin85421, I'd like to help with this issue.
