### ISSUE TITLE
[Umbrella] RayClusterStatusConditions Tests Review

### ISSUE THREAD

**Issue by rueian** [ray-project/kuberay#2645]
Continue on https://github.com/ray-project/kuberay/pull/2562: We have 5 status conditions on RayCluster CR which are gated by the `RayClusterStatusConditions` feature gate in v1.2.0. Now, we want to make them enable by default in v1.3.0. This issue is an umbrella for reviewing the tests for these status conditions.

-  HeadPodReady
-  RayClusterProvisioned
-  ReplicaFailure
-  RayClusterSuspending
-  RayClusterSuspended

## HeadPodReady and RayClusterProvisioned

In the envtest https://github.com/ray-project/kuberay/blob/3a624193b3119ec4ca0db613b5b24105f19438cf/ray-operator/controllers/ray/raycluster_controller_test.go#L1069

1. We make sure that the `HeadPodReady` condition is set when the Head Pod is ready. https://github.com/ray-project/kuberay/blob/3a624193b3119ec4ca0db613b5b24105f19438cf/ray-operator/controllers/ray/raycluster_controller_test.go#L1111-L1130

2. We make sure that the `RayClusterProvisioned` condition is NOT set when Worker Pods are not ready but set after they are ready. https://github.com/ray-project/kuberay/blob/3a624193b3119ec4ca0db613b5b24105f19438cf/ray-operator/controllers/ray/raycluster_controller_test.go#L1132-L1162

3. We make sure that the `RayClusterProvisioned` condition is STILL set after workers are down. https://github.com/ray-project/kuberay/blob/3a624193b3119ec4ca0db613b5b24105f19438cf/ray-operator/controllers/ray/raycluster_controller_test.go#L1164-L1183

4. We make sure that the `RayClusterProvisioned` condition is STILL set but the `HeadPodReady` condition is NOT set after Head Pod is dead. https://github.com/ray-project/kuberay/blob/3a624193b3119ec4ca0db613b5b24105f19438cf/ray-operator/controllers/ray/raycluster_controller_test.go#L1185-L1214

## ReplicaFailure

In the envtest, we make sure the ReplicaFailure condition is set when Pods can't be created. https://github.com/ray-project/kuberay/blob/3a624193b3119ec4ca0db613b5b24105f19438cf/ray-operator/controllers/ray/raycluster_controller_test.go#L1217-L1238

In the unit test, we make sure the `calculateStatus` function will set the `ReplicaFailure` condition from the `reconcileErr`.
https://github.com/ray-project/kuberay/blob/3a624193b3119ec4ca0db613b5b24105f19438cf/ray-operator/controllers/ray/raycluster_controller_unit_test.go#L1804-L1807

## RayClusterSuspending

In the envtest https://github.com/ray-project/kuberay/blob/3a624193b3119ec4ca0db613b5b24105f19438cf/ray-operator/controllers/ray/raycluster_controller_test.go#L714

1. We make sure the `RayClusterSuspending` condition is set when `.Spec.Suspend` is true. https://github.com/ray-project/kuberay/blob/3a624193b3119ec4ca0db613b5b24105f19438cf/ray-operator/controllers/ray/raycluster_controller_test.go#L746-L753
2. We make sure the `RayClusterSuspending` condition is STILL set when `.Spec.Suspend` turns to false before finishing suspension. https://github.com/ray-project/kuberay/blob/3a624193b3119ec4ca0db613b5b24105f19438cf/ray-operator/controllers/ray/raycluster_controller_test.go#L755-L761

## RayClusterSuspended

3. We make sure the `RayClusterSuspended` condition is set and `RayClusterProvisioned` is unset when all Pods are gone. https://github.com/ray-project/kuberay/blob/3a624193b3119ec4ca0db613b5b24105f19438cf/ray-operator/controllers/ray/raycluster_controller_test.go#L600-L612
4. We make sure the `RayClusterSuspended` condition is unset after resume the RayCluster. https://github.com/ray-project/kuberay/blob/3a624193b3119ec4ca0db613b5b24105f19438cf/ray-operator/controllers/ray/raycluster_controller_test.go#L686-L698

**Comment by andrewsykim** [comment]
Do we have any e2e tests for this feature? I'm guessing we never added it since our e2e tests don't make it easy to enable feature gates. But this should be simpler now that the feature gate is always enabled

**Comment by rueian** [comment]
We don't have explicit e2e tests for this feature yet. We do have implicit ones which are e2e tests for RayService since we check the new status condition in `rayservice_controller.go`: https://github.com/ray-project/kuberay/blob/402176656b779b990ebdd084145a71a56fd9f6fe/ray-operator/controllers/ray/rayservice_controller.go#L1123-L1128

To test them explicitly, how about we add some assertions to these condition values at [`sampleyaml/raycluster_test.go`](https://github.com/ray-project/kuberay/blob/master/ray-operator/test/sampleyaml/raycluster_test.go)?

**Comment by kevin85421** [comment]
@rueian, do we need any additional tests after #2661 has been merged?

**Comment by rueian** [comment]
I think we could have some tests on the `RayClusterSuspending` and `RayClusterSuspended` conditions. The https://github.com/ray-project/kuberay/pull/2661 doesn't include them. But testing `RayClusterSuspending` in e2e sampleyamls might be hard without flaky unless we find a way to inject a custom finalizer to prevent deletion.
