### ISSUE TITLE
[Feature] Make Replicas field in WorkerGroupSpec optional 

### ISSUE THREAD

**Issue by daikeshi** [ray-project/kuberay#265]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

The [Replicas field](https://github.com/ray-project/kuberay/blob/master/ray-operator/api/raycluster/v1alpha1/raycluster_types.go#L46) in `WorkerGroupSpec` is currently required. This field should be optional since it's a dynamic property and can be updated by the autoscaler. 

When we update other static properties (i.e. MaxReplicas) of a Ray cluster, we have to make sure the Replicas field is in sync with the value currently in use, so our deployment process wouldn't accidentally change the state of the Ray cluster running with a different replica value.  

### Use case

If `Replicas` is optional, when I update the Ray cluster with the autoscaler enabled, I don't need to make sure `Replicas` field has the same value as the one that is currently been using. I can simply ignore this field and update other static fields without affecting the current status of the cluster. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
This is a little subtle. The `Replicas` field is a goal state that the operator tries to maintain. In the current architecture it has to be present in the CR so that the operator knows what to do. 
The autoscaler works by editing the Replicas field.

On the other hand, it is awkward to have to specify a `Replicas` field on a cluster that is currently autoscaling.

One current workaround is to apply changes to the CR only by PATCHing it.
Could you say more about your workflow for updating a RayCluster?

I think it'd be possible to work out appropriate defaulting behavior for replicas, but it might be a little tricky.

**Comment by DmitriGekhtman** [comment]
Hmm, I guess if the replicas field were empty, the operator's reconcile logic could determine the correct replicas field to fill in based on
- The current pod count
- MinReplicas
- MaxReplicas

Basically, if absent, set Replicas to the current pod count,
unless it's out of range of [MinReplicas, MaxReplicas], 
in which case set Replicas to MinReplicas or MaxReplicas as appropriate.

This strategy would be strange in that it basically sets spec according to status, but it could work.

**Comment by daikeshi** [comment]
> One current workaround is to apply changes to the CR only by PATCHing it.
> Could you say more about your workflow for updating a RayCluster?

We currently manage several Ray clusters for different teams in a declarative way. We do give users the permission to scale up/down the cluster in their own namespaces, so the clusters may run with a different number of replicas due to the manual overriding or autoscaling. When we perform the maintenance work on managed Ray clusters and change their static properties (i.e. updating MaxReplicas, adding new worker groups), we don't want to override the existing `Replicas` value that is currently used. It would be nice if the proper replica number can be determined by the operator when it's absent.

**Comment by DmitriGekhtman** [comment]
For now, the suggestion is to patch just the replica count.

**Comment by davidxia** [comment]
@daikeshi can correct me if I'm wrong, but we've switched our user workflow to creating RayClusters on an as-needed basis via a CLI. So this is less of a concern for us now.
