### ISSUE TITLE
[Feature] Print KubeRay logs in Buildkite runner when tests fail

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2652]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/5662#0193c112-1087-45ff-bdf6-bda38ca89bd4

If `go test -timeout 30m -v ./test/e2e` fails, the `kubectl logs` command will not be executed. Modify the behavior to print the logs only when there are failed tests.
https://github.com/ray-project/kuberay/blob/8ec59e518354f281cd7ac7cad68cc5546a06131e/.buildkite/test-e2e.yml#L15-L17

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LeoLiao123** [comment]
Hi, @kevin85421 Can I take on this?
