### ISSUE TITLE
[Feature] Add a synchronization mechanism to ensure a goroutine's completion before the RayService HA test ends

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2653]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

We use a goroutine in `rayservice_ha_test.go`. However, there is no synchronization mechanism to ensure its completion before the test ends.

https://github.com/ray-project/kuberay/blob/8ec59e518354f281cd7ac7cad68cc5546a06131e/ray-operator/test/e2e/rayservice_ha_test.go#L176-L193

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by win5923** [comment]
Hi @kevin85421  , can I take on this issue?
