### ISSUE TITLE
[Feature] Add an e2e test for K8s Job submitter failures

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2655]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Add an test for https://github.com/ray-project/kuberay/pull/2579.

1. Create a RayJob
2. Wait for the Pod created by the K8s Job submitter to be ready
3. Let the Pod to run for a while (e.g. 15s)
4. Delete the Pod
5. The K8s Job should create another Pod
6. The RayJob should eventually succeed.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
This issue is included in KubeRay v1.3.0. I expect it to be completed in 2 weeks.

**Comment by simotw** [comment]
Hi @kevin85421, I would like to work on this issue.
