### ISSUE TITLE
[Feature] Separate `Test E2E` into two Buildkite runners

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2665]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, the `Test E2E` takes approximately 35 minutes to complete. To avoid a timeout, #2664 increases the timeout from 30 minutes to 1 hour. However, a better solution would be to split it into two Buildkite runners.

TODO 1: Put `rayservice_ha_test.go` and `rayservice_in_place_update_test.go` into a new Buildkite runner.
TODO 2: Revert the timeout from 1h to 30m (#2664)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
This is important for developer productivity, so it's better to have a PR this week.

**Comment by fscnick** [comment]
Hi @kevin85421, I'd like to help with this issue.
