### ISSUE TITLE
[Feature] Add a new event type `FailedToDeleteWorkerPodCollection`

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2672]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

See https://github.com/ray-project/kuberay/pull/2663/files#r1893148428 for more details.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by CheyuWu** [comment]
@kevin85421 I'd like to help with this
