### ISSUE TITLE
[QUESTION] running autoscaler as a sidecar is preferable? 

### ISSUE THREAD

**Issue by sivaguru-pat** [ray-project/kuberay#272]
thank you for the amazing work!

while testing samples for kuberay i came across same file name with different configuration

https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/kuberay/ray-cluster.complete.yaml
 
In this repo autoscaler is configured  as sidecar

https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.complete.yaml

here without that

need to know which configuration is preferable and why?

Thanks in Advance!!

**Comment by DmitriGekhtman** [comment]
> sidecar is a proper way to know to enable autoscaler especially when the integration work is not fully done yet.

Yep, the autoscaler is an experimental component -- it helps to be able to run it in a way that's semi-isolated from the head.
It also helps during development to have the flexibility to run the autoscaler at a pinned Ray master commit while running the Ray nodes at release Ray versions.

You also get the usual advantages of containerization...e.g. resource isolation and simplified logging.
(kubectl logs to get autoscaler's stdout/err)

Also, I like the idea of having the thing making K8s api calls somewhat isolated from the parts processing Ray workloads.

> For long term, I can we may provide the option to start the autoscaler process inside the head.

Having that optionality might be a good idea. The autoscaler was originally designed to be collocated with the rest of the Ray head processes and that's definitely the simplest way to deploy it.

Another very long term possibility is to have a replicated centralized component which handles autoscaling for all Ray clusters in the K8s cluster. (I think the K8s Horizontal Pod Autoscaler works like this, but I'm not completely sure.) One current issue with that approach is that autoscaling a single cluster currently uses a lot of memory, so things wouldn't scale well.

**Comment by DmitriGekhtman** [comment]
So... a summary of the above:

The autoscaler is a **sensitive** component that is **tightly coupled with the Ray head**.
So it makes sense to keep it close to the Ray head, but also keep it somewhat isolated so you can see what it's doing.

**Comment by sivaguru-pat** [comment]
@DmitriGekhtman @Jeffwan thank you for the valuable insights!!!
