### ISSUE TITLE
CNCF TAG-Runtime Discussion/Presentation?

### ISSUE THREAD

**Issue by raravena80** [ray-project/kuberay#281]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Hello kuberay team,

I'm one of the co-chairs of the CNCF TAG-Runtime, I'm reaching out and think it would be great for you to present/discuss the project at one of our meetings. An overview of the project would be great.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

### Use case

N/A

### Related issues

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by akanso** [comment]
Hi Ricardo,

Great to see you hear :)  Sure there are many of us that are very comfortable presenting KubeRay.

One thing to note here, is while Ray itself is the Framework for running distributed applications, KubeRay is the Operator responsible for setting up the cluster of pods capable of hosting the distributed computation. 

In the context of TAG Runtime, are you more interested in Ray or KubeRay, or maybe both?

@DmitriGekhtman and others, any thoughts....

**Comment by DmitriGekhtman** [comment]
cc @Jeffwan @dynamicwebpaige @zhe-thoughts

**Comment by DmitriGekhtman** [comment]
@raravena80 
I think it would make sense to aim for the July 7th slot. I'd be glad to present and/or co-present with others.
Let us know details (such as presentation timing etc.)

**Comment by raravena80** [comment]
Hi @akanso and all, covering both sounds like a good thing 😄  @DmitriGekhtman July 7th sounds good, the meeting/presentation is at 8am PT and the details are in the [meeting notes.](bit.ly/cncf-tag-runtime-meeting-notes)

**Comment by Jeffwan** [comment]
We have plenty time for July 7th slot. Let's sync up in ray slack and post the plan later here.
