### ISSUE TITLE
[Bug] Missing rayservices.ray.io CRD access rules in ClusterRole

### ISSUE THREAD

**Issue by retrry** [ray-project/kuberay#284]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

After deployment I expected for kuberay-operator to work correctly, but it gives error in log:
```
Failed to watch *v1alpha1.RayService: failed to list *v1alpha1.RayService: rayservices.ray.io is forbidden: User "system:serviceaccount:my-namespace:kuberay-operator" cannot list resource "rayservices" in API group "ray.io" at the cluster scope
```

### Reproduction script

Deploy kuberay-operator from master branch to Kubernetes via kuberay-operator Helm chart. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
Seems we do update the cluster roles here.
https://github.com/ray-project/kuberay/blob/7ecdd22c5812db8754e470635b20d9ee4a6a425d/ray-operator/config/rbac/role.yaml#L110-L122

But we have not synced role and rolebindings to helm folder
https://github.com/ray-project/kuberay/blob/master/helm-chart/kuberay-operator/templates/role.yaml

Did you use kustomize or helm?

**Comment by retrry** [comment]
I have used Helm chart.

**Comment by retrry** [comment]
Maybe the main question would be: if this is not synced, what else is not synced to helm chart?

**Comment by Jeffwan** [comment]
Helm needs to be updated. /cc @scarlet25151

**Comment by brucez-anyscale** [comment]
I think the issue is helm needs to be updated. The operator package should have the right rbac.

**Comment by pcmoritz** [comment]
It seems this is being worked on in https://github.com/ray-project/kuberay/pull/354

**Comment by scarlet25151** [comment]
@Jeffwan Sorry for the miss here, Let me add one for that

**Comment by Jeffwan** [comment]
#354 addresses this issue and it can be closed
