### ISSUE TITLE
[Feature] applying container spec updates to an existing cluster

### ISSUE THREAD

**Issue by tekumara** [ray-project/kuberay#289]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Given an existing cluster I'd like to be able to update the container spec (eg: to a different ray image version) and reapply, eg:
```
kubectl apply -f ray-operator/config/samples/ray-cluster.mini.yaml
``` 

Currently changes to the container spec are not applied to an existing cluster. This would make the raycluster work similar to Deployment and Pod resources.

### Use case

Upgrading an existing cluster.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
Hi @tekumara , this is a known issue. similar to https://github.com/ray-project/kuberay/issues/234

Let me push this PR #231 which address the issue. BTW, which field you like to change?

**Comment by tekumara** [comment]
Thank you! I'd like to change the image and also cpu/mem requests and limits

**Comment by Jeffwan** [comment]
All above field have been supported.

**Comment by tekumara** [comment]
I've tried this in kuberay 0.3.0 and the CRD is updated, but it's still not updating the existing pods to the new image.

**Comment by tekumara** [comment]
Still happening with kuberay-operator nightly.

**Comment by tekumara** [comment]
I can't get this to work with kuberay 1.3.2 either
