### ISSUE TITLE
Support clientset for RayCluster objects 

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#29]
We have some backend services written in Golang wants to interact with RayCluster Kubernetes objects and it needs to use typed clients.

Kubebuilder itself doesn't generate clients for objects. It would be great to leverage `code-gen` to generate clientset for external system to interact with

**Comment by chenk008** [comment]
It's useful to integrate Ray devops platform.

**Comment by harryge00** [comment]
@chenk008 @Jeffwan I can take this if nobody else is going to implement it

**Comment by Jeffwan** [comment]
@harryge00 Feel free to pick it up. The tricky part is kubebuilder structure is not friendly to reuse code-gen. I think we may need to adjust api structures like 

- api 
  - raycluster
    - v1alpha1

If you have other ways without reorganize the folder, that would be great

**Comment by Jeffwan** [comment]
@harryge00 The last PR is to generate clientset, can you help on that as well?

**Comment by Jeffwan** [comment]
This issue can be closed. Thanks for the contribution. @harryge00
