### ISSUE TITLE
[Feature] Ray 2.0 GCS HA support in KubeRay

### ISSUE THREAD

**Issue by wilsonwang371** [ray-project/kuberay#290]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

As Ray is evolving towards its 2.0 target these few months, from KubeRay side, we need to add support for this.

Fault-tolerant is one of the important goals in Ray 2.0 and GCS HA is one part of it. We need to make the necessary changes to KubeRay to work with GCS HA. 

Also, we need to add test cases to make sure GCS HA is working as expected.

Current design proposal is at: https://github.com/wilsonwang371/gcs_ha_design . I will make necessary changes to convert it to our internal proposal document.

### Use case

This can improve the ray cluster stability and this feature has been requested some time back by many different parties.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by iycheng** [comment]
I synced offline with @wilsonwang371 on this topic and I feel there are a couple of things we should include in this doc (or with a follow up doc) and the ray community can work together to see what's the feature missing and can coordinate accordingly.

* Credential
  * The current way to set up the password is to put it into the YAML file which is not very safe. We should have some paragraphs there discussing the short-term and long-term solutions.
* Storage state cleanup. Previously, whenever the cluster started, it'll come with an empty Redis cluster. But the situation changes here. We need to add some paragraphs discussing this and propose short-term and long-term solutions.
  * When GCS is restarted by KubeRay, storage doesn't need to be cleaned up
  * When the cluster restarted due to dome reason:
      *  If the user want a clean cluster, storage needs to be cleaned up
      * If the user want to recover from a cluster failure, for example, ray serve user just want to recover to the previous state, the storage doesn't need to be cleaned up.

**Comment by wilsonwang371** [comment]
Some initial testing. I killed head node and kuberay started a new head node. I can login to head node and connect to the cluster with no problem. But the information displayed is a little bit strange. It needs @iycheng to verify

```python
Python 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> from pprint import pprint as p
>>> ray.init("ray://localhost:10001")
ClientContext(dashboard_url='10.244.0.14:8265', python_version='3.7.7', ray_version='3.0.0.dev0', ray_commit='29a063afdf15102cac4eff288a3375997e5a41cf', protocol_version='2022-05-13', _num_clients=1, _context_to_restore=<ray.util.client._ClientContext object at 0x7f5f9db78150>)
>>> p(ray.nodes())
[{'Alive': True,
  'MetricsExportPort': 8080,
  'NodeID': 'a0859e3de06d679e7c6791cc8096e5c48231926e3797e316cfc45f7d',
  'NodeManagerAddress': '10.244.0.12',
  'NodeManagerHostname': 'raycluster-external-redis-worker-small-group-w6q44',
  'NodeManagerPort': 43001,
  'NodeName': '10.244.0.12',
  'ObjectManagerPort': 33257,
  'ObjectStoreSocketName': '/tmp/ray/session_2022-06-07_16-33-22_283085_18/sockets/plasma_store',
  'RayletSocketName': '/tmp/ray/session_2022-06-07_16-33-22_283085_18/sockets/raylet',
  'Resources': {'CPU': 1.0,
                'memory': 11516773991.0,
                'node:10.244.0.12': 1.0,
                'object_store_memory': 4935760281.0},
  'alive': True},
 {'Alive': True,
  'MetricsExportPort': 8080,
  'NodeID': '788835c16223b7e0f7a2c3f5cbb2e51145ce0d50e4913fcd0d71ea3c',
  'NodeManagerAddress': '10.244.0.13',
  'NodeManagerHostname': 'raycluster-external-redis-worker-small-group-k7w79',
  'NodeManagerPort': 35833,
  'NodeName': '10.244.0.13',
  'ObjectManagerPort': 34251,
  'ObjectStoreSocketName': '/tmp/ray/session_2022-06-07_16-33-22_283085_18/sockets/plasma_store',
  'RayletSocketName': '/tmp/ray/session_2022-06-07_16-33-22_283085_18/sockets/raylet',
  'Resources': {'CPU': 1.0,
                'memory': 11516851405.0,
                'node:10.244.0.13': 1.0,
                'object_store_memory': 4935793459.0},
  'alive': True},
 {'Alive': True,
  'MetricsExportPort': 8080,
  'NodeID': 'a075d5929dbd77b5e2d6e083003494abeb222bf3e2d4046789232795',
  'NodeManagerAddress': '10.244.0.15',
  'NodeManagerHostname': 'raycluster-external-redis-head-w7k6l',
  'NodeManagerPort': 42385,
  'NodeName': '10.244.0.15',
  'ObjectManagerPort': 44569,
  'ObjectStoreSocketName': '/tmp/ray/session_2022-06-07_16-41-36_785631_19/sockets/plasma_store',
  'RayletSocketName': '/tmp/ray/session_2022-06-07_16-41-36_785631_19/sockets/raylet',
  'Resources': {'CPU': 1.0,
                'memory': 9867679335.0,
                'node:10.244.0.15': 1.0,
                'object_store_memory': 4933839667.0},
  'alive': True},
 {'Alive': False,
  'MetricsExportPort': 8080,
  'NodeID': '8ab9eac6f02494896cea249260069c61632d8812ded2a871d8722814',
  'NodeManagerAddress': '10.244.0.14',
  'NodeManagerHostname': 'raycluster-external-redis-head-2dhfr',
  'NodeManagerPort': 33837,
  'NodeName': '10.244.0.14',
  'ObjectManagerPort': 43467,
  'ObjectStoreSocketName': '/tmp/ray/session_2022-06-07_16-39-02_496597_18/sockets/plasma_store',
  'RayletSocketName': '/tmp/ray/session_2022-06-07_16-39-02_496597_18/sockets/raylet',
  'Resources': {},
  'alive': False},
 {'Alive': False,
  'MetricsExportPort': 8080,
  'NodeID': '056c2945ddfcbf9e4c668c0281897c6dbe467f05fb2aa8a609063c49',
  'NodeManagerAddress': '10.244.0.14',
  'NodeManagerHostname': 'raycluster-external-redis-head-2dhfr',
  'NodeManagerPort': 45067,
  'NodeName': '10.244.0.14',
  'ObjectManagerPort': 42905,
  'ObjectStoreSocketName': '/tmp/ray/session_2022-06-07_16-33-22_283085_18/sockets/plasma_store',
  'RayletSocketName': '/tmp/ray/session_2022-06-07_16-33-22_283085_18/sockets/raylet',
  'Resources': {},
  'alive': False}]
>>> p(ray.cluster_resources())
{'CPU': 3.0,
 'memory': 32901304731.0,
 'node:10.244.0.12': 1.0,
 'node:10.244.0.13': 1.0,
 'node:10.244.0.15': 1.0,
 'object_store_memory': 14805393407.0}

```

**Comment by brucez-anyscale** [comment]
I have a question, why do we want to restart head node through KubeRay?
Could ray itself have some fault tolerance for head node, like a head node replica?

**Comment by wilsonwang371** [comment]
> I have a question, why do we want to restart head node through KubeRay? Could ray itself have some fault tolerance for head node, like a head node replica?

Good question. For Ray 2.0, it assumes the infra will detect failures and restart the ray head node. For a HA head nodes cluster, it is not the goal for Ray 2.0.

**Comment by DmitriGekhtman** [comment]
@wilsonwang371 @Jeffwan @brucez-anyscale @iycheng what's the  goal state for this in the KubeRay 0.3.0 / Ray 2.0.0?
https://github.com/ray-project/kuberay/issues/349

**Comment by wilsonwang371** [comment]
> @wilsonwang371 @Jeffwan @brucez-anyscale @iycheng what's the  goal state for this in the KubeRay 0.3.0 / Ray 2.0.0?
> https://github.com/ray-project/kuberay/issues/349

Ray will have a rc in late this month and we want our release to get aligned with ray. HA support in kuberay will not break existing functionalities

**Comment by DmitriGekhtman** [comment]
For GCS HA on KubeRay, I imagine we're aiming for something like alpha (since the implementation isn't finished yet)?

**Comment by wilsonwang371** [comment]
> For GCS HA on KubeRay 0.3.0, I imagine we're aiming for something like alpha (since the implementation isn't finished yet)? Is that accurate?

The implementation is almost ready. @iycheng @brucez-anyscale @Jeffwan @scarlet25151 were in the meeting discussion. Since 0.3.0 is very close to the first RC release, I am thinking we probably can make ray HA support available in 0.3.0.

**Comment by DmitriGekhtman** [comment]
Got it -- will leave the messaging around feature readiness (alpha, beta, etc.) to you all.

**Comment by Jeffwan** [comment]
@wilsonwang371 @iycheng @brucez-anyscale Do we have anything left for this story in v0.3.0 release?

**Comment by brucez-anyscale** [comment]
> @wilsonwang371 @iycheng @brucez-anyscale Do we have anything left for this story in v0.3.0 release?

I think @wilsonwang371 has a `env variable` issue need to be fixed.

**Comment by wilsonwang371** [comment]
> > @wilsonwang371 @iycheng @brucez-anyscale Do we have anything left for this story in v0.3.0 release?
> 
> I think @wilsonwang371 has a `env variable` issue need to be fixed.

I posted a new mr

**Comment by wilsonwang371** [comment]
> @wilsonwang371 @iycheng @brucez-anyscale Do we have anything left for this story in v0.3.0 release? 

I posted a new mr

**Comment by Jeffwan** [comment]
https://github.com/ray-project/kuberay/pull/406 this is merged. There's no sub issues left now. We can close the issue and feel free to reopen it if we forget something.
