### ISSUE TITLE
[Bug] gpu-accelerator in template don't work

### ISSUE THREAD

**Issue by armandpicard** [ray-project/kuberay#295]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

apiserver

### What happened + What you expected to happen

When creating a template with a gpu-accelerator like "amd.com/gpu" and then creating a cluster than use this template the resource for gpu  remain "nvidia.com/gpu" but it should be "amd.com/gpu"

### Reproduction script

`bash
kuberay template compute create --name test-gpu-accelerator --namespace default --cpu 4 --memory 8 --gpu-accelerator "amd.com/gpu" --gpu 1

kuberay cluster create --head-compute-template test-gpu-accelerator --head-image ray --name test-gpu-accelerator --namespace default --user armand --worker-compute-template test-gpu-accelerator --worker-group-name group-a --worker-image ray
`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
Thanks! This is indeed a bug and the default should be `nvidia.com/gpu` and any given value should override the default settings.
