### ISSUE TITLE
[Feature] Add more CI tests 

### ISSUE THREAD

**Issue by wilsonwang371** [ray-project/kuberay#298]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

We need to add more tests to CI to improve code stability.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
I agree. @kevin85421 has been working in this direction. 
We should definitely think about what kinds of testing need to be added.

Going to remove the 0.4.0 milestone label as this issue is not completely specific.

**Comment by kevin85421** [comment]
There are some related issues with more details in 0.5.0 milestone. Close this issue and track the progress in 0.5.0 milestone.
