### ISSUE TITLE
[Bug] Spelling incorrect for some spec in kuberay apiserver

### ISSUE THREAD

**Issue by scarlet25151** [ray-project/kuberay#320]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

apiserver

### What happened + What you expected to happen

As the figure shows below, we have some wrong spelling for `workerGroupSpec` and need to correct them.
![image](https://user-images.githubusercontent.com/38214590/175222268-5e4b631a-d1ae-4a77-9a7b-28cb06fc9dbb.png)

### Reproduction script

when we use api for clusters there would be the wrong spelling `worker_group_sepc`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
Nice catch! Please help submit a PR to address the issue @scarlet25151.

**Comment by Jeffwan** [comment]
https://github.com/ray-project/kuberay/pull/330 This PR has addressed the issue and merged
