### ISSUE TITLE
[Bug] Specifying Ray GPU resources is unintuitive

### ISSUE THREAD

**Issue by Nintorac** [ray-project/kuberay#321]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

When no nodes are available the autoscale does not scale pods. This would be useful because unschedulable pods trigger upstream autoscaling in kubernetes autoscale

### Reproduction script

1. Have an autoscaling GPU node pool in k8s
2. set replicas to 0 and then request a GPU
3. No pods are created.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
Hi, thanks for posting! 

We're working on fixing up the interface for specifying resource such as GPUs.
https://github.com/ray-project/kuberay/pull/318

For now, the solution is to
- Deploy an autoscaling cluster following [these instructions](https://ray-project.github.io/kuberay/guidance/autoscaler/)
- **Critically**, include num-gpus: 1 in the rayStartParams for your gpu worker group.

Once https://github.com/ray-project/kuberay/pull/318 is merged, GPUs will be auto-detected from the Ray container config, which will obviate the need for the second bullet above!

**Comment by DmitriGekhtman** [comment]
I've updated the issue title -- if the above suggestions don't work, we can debug further.

**Comment by Nintorac** [comment]
Nice that works :) 

I had to use `num-gpus: "1"` because the schema is expecting a string here
