### ISSUE TITLE
[Bug] compatibility test is not using the right kuberay build image

### ISSUE THREAD

**Issue by wilsonwang371** [ray-project/kuberay#323]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen

during gcs ft development, i realized compatibility test is not using the right kuberaty build image. This need to be fixed.

### Reproduction script

manually checked the kuberay operator & apiserver images after deployed in local kind-based k8s cluster.

### Anything else

I am working on a patch for this.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by wilsonwang371** [comment]
patch is in https://github.com/ray-project/kuberay/pull/294

**Comment by Jeffwan** [comment]
@wilsonwang371  Can we split the bug fix and HA stuff? Some HA features are only available in master. We may need more time to merge the PR.

**Comment by wilsonwang371** [comment]
ok. I will do a separate patch for this

**Comment by wilsonwang371** [comment]
The patch is under review. https://github.com/ray-project/kuberay/pull/327
