### ISSUE TITLE
[Bug] ray-cluster.autoscaler.debug.yaml does not work

### ISSUE THREAD

**Issue by Cloudhax23** [ray-project/kuberay#325]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

The bug happens when you perform a fresh install of the operator. The ray-cluster.autoscaler.debug.yaml will return 

2022-06-27T19:27:30.687Z	ERROR	controller.raycluster-controller	Reconciler error	{"reconciler group": "ray.io", "reconciler kind": "RayCluster", "name": "raycluster-complete", "namespace": "default", "error": "pods \"raycluster-complete-head-\" is forbidden: error looking up service account default/autoscaler-sa: serviceaccount \"autoscaler-sa\" not found"}

when applied to the cluster.

### Reproduction script

Apply the ray-cluster.autoscaler.debug.yaml after installing autoscaler version of KubeRay. 

### Anything else

Occurs every time. Annoying because I need to use a custom autoscaler image. The non-debug version works as expected but I have to manually patch the autoscaler image to make it work as expected. The debug config is necessary. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
Hi @Cloudhax23! We've very recently added the ability to specify a custom autoscaler image!

To use a custom autoscaler image, start with the non-debug version of the autoscaler config and add the following configuration to the RayCluster CR:
```
spec:
    autoscalerOptions:
        image: <your-custom-autoscaler-image>
```

Out of curiosity, may I ask why you need to use a custom autoscaler image?

@Jeffwan do you think we can delete the file `ray-cluster.autoscaler.debug.yaml` at this point to prevent confusion?

**Comment by Cloudhax23** [comment]
> Hi @Cloudhax23! We've very recently added the ability to specify a custom autoscaler image!
> 
> To use a custom autoscaler image, start with the non-debug version of the autoscaler config and add the following configuration to the RayCluster CR:
> 
> ```
> spec:
>     autoscalerOptions:
>         image: <your-custom-autoscaler-image>
> ```
> 
> Out of curiosity, may I ask why you need to use a custom autoscaler image?
> 
> @Jeffwan do you think we can delete the file `ray-cluster.autoscaler.debug.yaml` at this point to prevent confusion?

Primarily due to the inability to access docker hub within the ecosystem.
