### ISSUE TITLE
[Discussion] Prepare for v0.3.0 release

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#349]
It's almost time to release v0.3.0 and we still have some issues not resolved in v0.3.0 milestone. https://github.com/ray-project/kuberay/milestone/3 yet. Beside these issue listed in the milestone, we may have other issue in the backlog not associated with v0.3.0 release. Please help tag the issue we want to include in next release. 

On the compatibility side, we need to have consensus on the latest Ray version we want to support. For those 2.0-dev or experimental feature, it would be great to add the feature flags and explain the usage and maturity in the docs.

Timeline perspective, we can merge all v0.3.0 features by end of week and then cut a branch `release-0.3` and RC release. Starting from next week, let's concentrate on the integrations and testings.  If no more bugs are reported, we can cut the official release. 

Any thoughts? 

/cc @DmitriGekhtman @brucez-anyscale @simon-mo @akanso @caitengwei @harryge00  @daikeshi @davidxia  @scarlet25151 @wilsonwang371

**Comment by DmitriGekhtman** [comment]
The KubeRay 0.3.0 release will be coordinated closely with the critical Ray 2.0.0 release.
Will start by tagging some Ray and Anyscale team leads, so that we don't miss anything.

@zhe-thoughts @ericl @pcmoritz @richardliaw @edoakes @jaikumarg1 @iycheng @sriram-anyscale

**Comment by richardliaw** [comment]
@Jeffwan that sounds awesome. On Ray side we plan to cut 2.0rc on 7/22. Kuberay to cut anytime before that or close to that would be ideal. Also cc @tgaddair .

**Comment by DmitriGekhtman** [comment]
Following up on @richardliaw's comment, I think it'd be acceptable to cut a KubeRay RC by the end of **next week**, but any time before is also fine.
I think it would be natural to use next Tuesday's sync meeting to finalize some of the details. 
On the other hand, before is fine as well.

**Comment by DmitriGekhtman** [comment]
For the items under the 0.3.0 milestone, let's discuss on the individual issues. It may be wise to remove some of the items.

**Comment by DmitriGekhtman** [comment]
If possible, we should [flip the feature flags](https://github.com/ray-project/kuberay/issues/357) now.

**Comment by DmitriGekhtman** [comment]
The KubeRay-related Ray issues for this release are here

https://github.com/ray-project/ray/issues?q=is%3Aopen+is%3Aissue+author%3ADmitriGekhtman+label%3Akuberay+label%3A%22Ray+2.0%22

**Comment by Jeffwan** [comment]
@DmitriGekhtman  I think major features are all there, the left things are docs and improvements.
- https://github.com/ray-project/kuberay/pull/398
- https://github.com/ray-project/kuberay/issues/290#issuecomment-1192777995

I see in the 0.3.0 issues, there're 3 issues related to autoscaler. Any updates on those issues?

**Comment by DmitriGekhtman** [comment]
This one https://github.com/ray-project/kuberay/issues/360 is better handled in the context of the release process (once the Ray 2.0.0 branch is cut).

The other two I'll take care of within the next couple of business days.

**Comment by davidxia** [comment]
@Jeffwan any chance we can include https://github.com/ray-project/kuberay/pull/383 in 0.3.0?

**Comment by Jeffwan** [comment]
@davidxia The change looks good to me and I merge it. Thanks for the fix, we did encounter the same issue in downstream.

**Comment by DmitriGekhtman** [comment]
Just noting some release todos, based on discussion yesterday:

Definite requirements:
- Changelog
- Document with high-level release notes

Could be useful:
- Release candidate? It could help, for example, to have a 0.3.0rc0 tag for docker images and configs.

Should have eventually (if not this release then in a future one):
- Documented, structured release process (a checklist, say). That would make it easier for the community to contribute in the release process.

**Comment by Jeffwan** [comment]
Sounds good. I will help cut branch and rc release today once these two merged. 
- test is really annoying We need to fix the root issue here https://github.com/ray-project/kuberay/pull/424 
- https://github.com/ray-project/kuberay/pull/423
- https://github.com/ray-project/kuberay/issues/417

**Comment by Jeffwan** [comment]
I cut `release-0.3` branch and `v0.3.0-rc.0` tag. 

We can test the latest version using below commands or use helm to install kuberay (https://github.com/ray-project/kuberay/tree/release-0.3/helm-chart/kuberay-operator)

```
export KUBERAY_VERSION=release-0.3
kubectl create -k "github.com/ray-project/kuberay/manifests/cluster-scope-resources?ref=${KUBERAY_VERSION}"
kubectl apply -k "github.com/ray-project/kuberay/manifests/base?ref=${KUBERAY_VERSION}"
```

Docs: https://ray-project.github.io/kuberay/


For bug fixes, let's file PR against master and we will cherry-pick to `release-0.3` later.

**Comment by Jeffwan** [comment]
v0.3.0-rc.1 is out.

```
export KUBERAY_VERSION=v0.3.0-rc.1
kubectl create -k "github.com/ray-project/kuberay/manifests/cluster-scope-resources?ref=${KUBERAY_VERSION}"
kubectl apply -k "github.com/ray-project/kuberay/manifests/base?ref=${KUBERAY_VERSION}"
```

**Comment by Jeffwan** [comment]
v0.3.0 has been officially released and we can close the issue https://github.com/ray-project/kuberay/releases/tag/v0.3.0
