### ISSUE TITLE
[Feature] Create a Github team for code review or issue discussion

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#350]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, for breaking changes, community discussions, we need to manually tag lots of stakeholders. This is inefficient, instead, we should create some Github team. All the user belong to the team will be notified. 

### Use case

Save time on tagging community people

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Is the Slack channel sufficient? I don't have any experience with GitHub teams. Feel free to reopen it if you believe Slack isn't adequate.
