### ISSUE TITLE
[Feature] Set RAY_ADDRESS env for the head pod

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#373]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

This issue is a "note to self".

Have the KubeRay operator automatically set the following env for the head pod 
RAY_ADDRESS=localhost:<ray-head-port>

The effect of this is simply to allow connecting to Ray via `ray.init()` rather than `ray.init("auto")`.

### Use case

Just simplifies/uniformizes the process of connecting to Ray.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
@pcmoritz tracking this here

**Comment by DmitriGekhtman** [comment]
Corresponding Ray issue https://github.com/ray-project/ray/issues/26542

**Comment by DmitriGekhtman** [comment]
Sorry -- it wasn't clear.
For cases in which a user is executing a script directly on the Ray cluster (say via job submission),
we would like the user to be able to connect to Ray in the script with
`ray.init()` rather than `ray.init("auto")`.

`ray.init()` would read the `RAY_ADDRESS` env variable.

**Comment by Jeffwan** [comment]
I mean this is helpful when user submit workloads inside the head?

**Comment by DmitriGekhtman** [comment]
Right, this would be useful in any circumstance where Ray's entry-point is running in the head.

The main goal is to avoid users accidentally starting a local single-node cluster, which is what `ray.init()` would do when `RAY_ADDRESS` is unset.
