### ISSUE TITLE
[Feature] Improve RayService Event logs and better naming

### ISSUE THREAD

**Issue by brucez-anyscale** [ray-project/kuberay#395]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

--- 1 ---
Based on the bug bash of RayService. We would like to improve the event log message.
1. Make it less frightening with better event like `wait for ray cluster ready` instead of `fail to deploy`
2. Add more events when update serve config. For example:
When the serve deployment is running healthy, and then users apply a new serve config. RayService should record an event for `ServeDeploymentConfigUpdateFailed` or `ServeDeploymentConfigUpdateSucceed`

--- 2 ---
Now the 4 services created by RayCluster and RayService have names that are hard to understand. Give them better naming.

--- 3 ---
In states:
we have
```
Health Last Update Time
Last Update Time
```
Seems the naming is hard to understand.   
Health Last Update Time: record the last timestamp that RayCluster is healthy
Last Update Time: record the last timestamp that RayCluster is checked for health

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
@brucez-anyscale @simon-mo have we solved this yet?

**Comment by brucez-anyscale** [comment]
I think so. Should be resolved I remember correctly

**Comment by DmitriGekhtman** [comment]
Great!

Closing. Cleaning up GitHub issues is the best.
