### ISSUE TITLE
[Feature] Support multi-version docs

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#401]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/4739316/180336147-630bd9ec-e13f-4601-b87a-7a3045fccc22.png)

We plan to cut v0.3.0 release pretty soon. Currently it's pointing to master and any doc changes will be deployed. In order to give user a stable site, we need to support a dropdown to allow user to choose the versions. 

https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/ seems there's a way to make it

### Use case

Keep stable and nightly docs separate

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
KubeRay docs have moved to the Ray repository. The Ray website supports doc versioning.
