### ISSUE TITLE
[Bug] Operator watch resource needs to be optimized

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#403]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

![image](https://user-images.githubusercontent.com/4739316/180622227-ef2e0ec0-6368-46f8-8786-98d05b51e242.png)

HA Feature added some logic to reconcile events. We can see some unrelated pods are filtered out. This should be optimized to filter to watch and reconcile kuberay specific resources.

### Reproduction script

Just start the operator and watch logs

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
The filter for Kubernetes events is improved by https://github.com/ray-project/kuberay/pull/946. It will still receive some unrelated events, but filter all events in the resource event filters requiring two lookup operations for the local cache. See the PR description of https://github.com/ray-project/kuberay/pull/996 for more details. The next step may remove the Kubernetes informer. Close this issue.
