### ISSUE TITLE
[Feature] Update sample configurations with larger resource requests

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#417]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

The KubeRay sample configurations show Ray clusters with tiny Ray nodes (1 CPU) etc.
It's fine to have a couple such configurations for local experiments -- but the majority of the samples should emphasize real life applications where a Ray node should be sized to take up a sizable fraction of a K8s node (if not the entire node).

Ray is not meant to operate with 1 CPU nodes.

### Use case

Prevent users from burning themselves with tiny Ray nodes.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by akanso** [comment]
We use multiple Worker-groups in a single ray cluster. Each group has a difference functionality, some have 6 or 12 cores and others have only 2 cores. 

I think in our examples and docs we can add a note that users should not limit themselves to a single core, but I don't think we should "prevent" them :)

**Comment by DmitriGekhtman** [comment]
Thanks Ali, great point.

I'm just curious -- 2 cores is a little small -- what's the application for that?

**Comment by akanso** [comment]
we dynamically add and remove simulators used for RL during training, some simulators do not need more than 0.5 cores. We can share the sim config using Ray GCS. And that is why they sit in their own worker-group. When the training is complete, we can remove the entire Ray Cluster with all the workers.

**Comment by DmitriGekhtman** [comment]
Ray folks consider this sufficiently important for preventing user confusion that we consider this a release blocker -- I've added the label.
