### ISSUE TITLE
Create issue and pull request templates

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#43]
I notice we have more community members come to the repo and submit issues now.  

Issue templates and pull request templates help us provide more guidance for opening issues/PR while allowing contributors to provide specific, structured information their issue/PR. This help ensure maintainers receive desired information and reduce back and force communication. 

https://www.google.com/search?client=safari&rls=en&q=issue+and+pull+request+templates&ie=UTF-8&oe=UTF-8

/cc @akanso @chenk008 @chaomengyuan

**Comment by chaomengyuan** [comment]
Sure.

**Comment by Jeffwan** [comment]
This has been enabled
