### ISSUE TITLE
[Feature] Enabled e2e test using examples

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#46]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

This is a follow up request of https://github.com/ray-project/kuberay/issues/42

We should enable e2e testing using some examples from the operator. That helps to track example changes and make sure they are always working.

### Use case

User will use example directly in their cluster. 

### Related issues

https://github.com/ray-project/kuberay/issues/42

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
I would suggest to use papermill to test some real world use cases. These notebook can come from some well written ray tutorials.  This give us extra confidence the application can run against the the cluster KubeRay brings up .

**Comment by Jeffwan** [comment]
Let's use simple way to verify cluster status in CI now. Once we have more examples checked in, let's prioritize this story then. I will move this story to v0.3.0 release

**Comment by dynamicwebpaige** [comment]
+1 for creating end-to-end tutorials for real world use cases, and ensuring that they are regularly tested. We are in the process of creating such examples for Ray's upcoming AI Runtime (AIR); it might make sense to expand those examples to include support for KubeRay.

cc: @richardliaw @ericl

**Comment by DmitriGekhtman** [comment]
cc @kevin85421 
The theme here is automated testing of actual user workflows. We don't have that yet.
