### ISSUE TITLE
[Bug] KubeRay CRDs cannot be installed with Kubernetes 1.16.0

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#466]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

KubeRay's CRDs are not compatible with Kubernetes versions 1.16 or older due to an API change in Kubernetes 1.17 introducing the `x-kubernetes-map-type`
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#api-changes

While the README does offer some guidance on suggested kubernetes versions, it could be useful to establish actual compatibility boundaries and perhaps introduce workarounds for Kubernetes 1.16 in particular. 
(1.15 is outside the range we'd want to support, given that 1.16 was the GA release for CRDs)

### Reproduction script

Try `kubectl create -k kuberay/ray-operator/config/default` with a Kubernetes version 1.16.
The result is
```
error: error validating "kuberay/ray-operator/config/default": error validating data: ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.headGroupSpec.properties.template.properties.spec.properties.nodeSelector): unknown field "x-kubernetes-map-type" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps; if you choose to ignore these errors, turn validation off with --validate=false
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
Delete the `x-kubernetes-map-type` should  work. BTW, this is expected and 1.16 is retired for long time and we should ask user to bump the version.

**Comment by DmitriGekhtman** [comment]
> Delete the `x-kubernetes-map-type` should work. 

Will pass that on :)

> should ask user to bump the version

The particular user had to use an old Kubernetes version apparently due to internal constraints at their company.

**Comment by kevin85421** [comment]
Close this issue because the KubeRay community does not support Kubernetes 1.16.0.
