### ISSUE TITLE
[Feature] host helm in github static site

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#475]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, we ask user to clone the repo and then install helm chart. This is inconvenient and not the best practice for installation. We should use tools like https://github.com/helm/chart-releaser to provide experience like 

```
helm repo add ray-project https://ray-project.github.io/kuberay
helm install kuberay ray-project/kuberay -n ray-system
``` 

The tricky thing is we already have docs served in Github `gh-pages`. https://ray-project.github.io/kuberay/ We can not automatically use it to serve helm static files.

The ideal solution is to create a separate repo to host charts. like `ray-project/kuberay-charts` or `ray-project/ray-charts`. 
Then we can sync helm update there. We just need to update the chart if we have a release. if it's called `ray-charts`, then other manifest could be deployed in Kubernetes can be moved there.

### Use case

Provide user easier way to install helm chart.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
Closing https://github.com/ray-project/kuberay/issues/260 in favor of this one, since this one is more recent and specific.

**Comment by kevin85421** [comment]
I opened a PR #545.
