### ISSUE TITLE
[Bug] Scheduling GPU trials on CPU Workers

### ISSUE THREAD

**Issue by peterghaddad** [ray-project/kuberay#484]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator, Others

### What happened + What you expected to happen

When there are none CPU workers available, then Ray's autoscaler schedules the workers on GPU nodes. Even if GPUs requests were `0`.

This can be an inhibitor when it comes to deploying on certain systems and infrastructure.

Would having some sort of flag or rayStartParam be an option to make this optional?

### Reproduction script

Request {"GPU": 1"} for a tune experiment to trigger the autoscaler to instantiate a GPU worker. The GPU workers gets scheduled on a CPU worker.

### Anything else

n/a

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
@peterghaddad would you mind posting config files and scripts for a minimal reproduction?

I don't 100% follow the description.
