### ISSUE TITLE
[Feature] Integrate KubeRay with Kubeflow

### ISSUE THREAD

**Issue by richardsliu** [ray-project/kuberay#502]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

KubeRay can be installed with other OSS ML Ops products (like Kubeflow) in the same Kubernetes cluster to provide an integrated platform.

Some benefits provided by Kubeflow that can be complementary to KubeRay:
* User profiles (access control and resource isolation)
* Authentication/authorization support
* Jupyter notebook integration

I have a blog post (coming soon) that discusses these ideas in more detail. Would be great to work with the KubeRay community to make this a long-term supported solution.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
For reference, @richardsliu's blogpost is live here: https://cloud.google.com/blog/products/ai-machine-learning/build-a-ml-platform-with-kubeflow-and-ray-on-gke !

The goal of a Kubeflow/KubeRay integration would be to simplify the management of the components described in the blog. Let's use this thread to discuss implementation ideas.

cc @cadedaniel @sublimotion @zhe-thoughts @ericl @richardliaw
