### ISSUE TITLE
[Feature] [Governance] [RFC] Restrict write access

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#506]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

It appears that any member of the Ray project can merge KubeRay PRs **without review**.
That should be fixed up.

At the very least,
- Require an approving review to merge to master.

Possibly,
- Restrict write access (merge capability) to a specific group of committers.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
cc @Jeffwan @akanso @pcmoritz for thoughts

**Comment by Jeffwan** [comment]
not sure if Github natively support it and we use other ways to achieve that. I am trying to see how Ray core does it?

**Comment by DmitriGekhtman** [comment]
> not sure if Github natively support it and we use other ways to achieve that. I am trying to see how Ray core does it? 

@pcmoritz would know, I think
