### ISSUE TITLE
[Bug] working_dir in RayService can only pull from https link?

### ISSUE THREAD

**Issue by james-tn** [ray-project/kuberay#510]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I am testing ray serve using the ray[ service sample ](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray_v1alpha1_rayservice.yaml). It worked when the work_dir points to a github archive zip file but the service failed to deploy when it pointed to a local directory such as "./script". The folder contains the same content I pushed to github.

### Reproduction script

Point the working_dir to a local directory 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by simon-mo** [comment]
If the "local directory" means a directory in the docker image, then it should work!

**Comment by kevin85421** [comment]
Feel free to reopen this issue if you have any further questions.
