### ISSUE TITLE
[Bug] When using the new GCS FT feature, not able to connect to external Redis cluster with multiple master nodes

### ISSUE THREAD

**Issue by sigmundv** [ray-project/kuberay#512]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

When using the new GCS FT feature by applying the `ray.io/ft-enabled: "true"` annotation I'm not able to connect to an external Redis cluster with multiple master nodes. On the other hand it works with a Redis cluster that only has a single master node.

You can use these YAML files to reproduce the two scenarios: [ray-external-redis-yaml-files.zip](https://github.com/ray-project/kuberay/files/9457509/ray-external-redis-yaml-files.zip)

More details are mentioned in [this](https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1661801778494529) Slack thread, where I was discussing the issue with @iycheng.

### Reproduction script

Assuming that the RayCluster, RayServices and RayJobs CRD are installed in the Kubernetes cluster, run the following commands to deploy an external Redis cluster with a single master node:
```shell
kubectl create namespace exampledotcom
kubectl create -f ray-external-redis-single-master.yaml
```
And the following commands to delete the previous deployment and create a new one with an external Redis cluster with multiple master nodes:
```shell
kubectl delete -f ray-external-redis-single-master.yaml
kubectl create -f ray-external-redis-multimaster.yaml
```
After this you'll observe that the Ray head node is not able to connect to the external Redis cluster.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wilsonwang371** [comment]
are you able to provide more information such as the head node logs?

**Comment by DmitriGekhtman** [comment]
@sigmundv could you also describe your Redis configuration at a high level?
What is the reason for using multiple masters?

**Comment by iycheng** [comment]
@sigmundv Ray right now doesn't support sharded redis cluster. It only supports Redis cluster with multiple replicas (HA). The one you mentioned is a sharded redis cluster.
Ray doesn't write a lot of data into redis, so sharding seems not that important for now.
