### ISSUE TITLE
[Feature] Generate new manifest and update generated API in pre-commit hook

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#519]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

We need to keep two things synchronizing with `types.go`.

1. `types.go` should be synchronized with the CRD YAML file.
```
make manifests
```
3. `types.go` should be synchronized with generated API (`pkg/client`)
```
./hack/update-codegen.sh # update generated API
./hack/verify-codegen.sh   # Verify the consistency between types.go and generated API
```

In my opinion, we should do these synchronizations in 4 places.
(1) build (2) test (3) run (4) pre-commit hook

### Use case

The inconsistency may cause different behaviors.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
The key part of the consistency check in the CI is done. Having this in

> (1) build (2) test (3) run (4) pre-commit hook

would greatly improve the developer experience, but is somewhat less critical. Thus, will mark this with P2 (important but not urgent) priority.

**Comment by kevin85421** [comment]
The pre-commit hook seems not to be important. Contributors are comfortable with running commands manually.
