### ISSUE TITLE
[Feature] Add consistency check for types.go, CRDs, and generated API in GitHub Actions

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#521]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

As I mentioned in #519, the inconsistency between `types.go`, CRD YAML files, and generated API may cause wrong behaviors. Hence, we can add the consistency checks into GitHub Actions.

### Implementation:
1. We can use `./hack/verify-codegen.sh` to check the consistency between `types.go` and generated API.
2. I did not know how to check the consistency between `types.go` and CRD YAML files. `controller-gen` seems not support the validation.

### Related issues

#519

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
> I did not know how to check the consistency between types.go and CRD YAML files. controller-gen seems not support the validation.

One form of consistency check is to run the code/yaml generation and make sure that the relevant files are unchanged.

**Comment by DmitriGekhtman** [comment]
@kevin85421 
I'll provisionally assign this one and #519 to you.

Resolving these would definitely improve the KubeRay dev process!

**Comment by kevin85421** [comment]
PR: https://github.com/ray-project/kuberay/pull/546

**Comment by DmitriGekhtman** [comment]
Closed by https://github.com/ray-project/kuberay/pull/546!
