### ISSUE TITLE
[Bug] Ray GettingStarted tutorial causes head node OOM 

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#528]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I tried to follow the [document](https://docs.ray.io/en/latest/cluster/kubernetes/getting-started.html) to build a simple ray cluster (1 head node + 1 worker node) and run a simple job on the cluster. However, when I submitted a job to my head node, the job failed due to OOM as shown in the following picture.

<img width="1920" alt="Screen Shot 2022-09-01 at 3 42 17 PM" src="https://user-images.githubusercontent.com/20109646/188027472-339a85a9-1f52-4ead-836f-1e428b7f1244.png">

### Reproduction script

I ran this experiment on GKE with autopilot. Some nodes in GKE may have just the same amount of memory as the resource request of head node. As shown in the figure, the node only have 0.5G memory (same as resource request) rather than 1G (resource limit). Hence, we need to increase the value of resource request of the head node.
```bash
# Step1: Deploy the operator
! kubectl create -k "github.com/ray-project/kuberay/ray-operator/config/default?ref=v0.3.0&timeout=90s"

# Step2: Deploy a ray cluster
! kubectl apply -f https://raw.githubusercontent.com/ray-project/kuberay/release-0.3/ray-operator/config/samples/ray-cluster.autoscaler.yaml

# Step3: port-forwarding
! kubectl port-forward service/raycluster-autoscaler-head-svc 8265:8265

# Step4: Run an application
! ray job submit --address http://localhost:8265 -- python -c "import ray; ray.init(); print(ray.cluster_resources())"
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
It does seem we need at the very least to set the requests to at least 500MB.

**Comment by kevin85421** [comment]
Resolved by https://github.com/ray-project/kuberay/pull/529.
