### ISSUE TITLE
[Bug] kustomization.yaml

### ISSUE THREAD

**Issue by huadubadaniao** [ray-project/kuberay#534]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I cloned your project and manually deployed kuberay according to your documentation, but I found kustomization. In YAML, the file path is written under the resources, and the YAML file is written under the bases. After I correct it, I can install it properly.

### Reproduction script

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ray-system

resources:
- namespace.yaml

bases:
- ../../ray-operator/config/crd

configurations:
- params.yaml

-----------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ray-system

bases:
- ../../apiserver/deploy/base
- ../../ray-operator/config/rbac
- ../../ray-operator/config/manager

images:
- name: kuberay/apiserver
  newName: kuberay/apiserver
  newTag: nightly
- name: kuberay/operator
  newName: kuberay/operator
  newTag: nightly

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
Thanks for posting this issue!

Could you clarify the following:

- What command you ran.
- What error you encountered.
- What steps you took to correct the issue.

**Comment by DmitriGekhtman** [comment]
The issue is not stated clearly enough.
