### ISSUE TITLE
[Task] Update RayCluster to v1beta1

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#536]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

KubeRay CR resource versions are currently at v1alpha1. These should be upgraded, simply to signal the APIs’ stability. RayCluster should be upgraded now. RayService and RayJob can be upgraded later. The main task is to put in place the machinery (webhooks, whatever) required to update api versions.

### Use case

Signal maturity of the APIs.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
There's a dependency task to support multi-version API. (webhook or multiple controllers or other ways). With that supported, we can introduce v1beta1

**Comment by DmitriGekhtman** [comment]
I'll mark this as P2 for now, as we don't have an urgent need to introduce breaking changes. This mostly a public relations item.

**Comment by DmitriGekhtman** [comment]
If it's too much of a bother to update to v1beta1, we can just keep developing until we reach a GA state (whenever that will be) and upgrade straight to v1 with KubeRay 1.0.0.

**Comment by kevin85421** [comment]
Close this one. I will bump the CRD versions to v1 this week.
