### ISSUE TITLE
[Bug] Helm chart install fails due to undefined worker key in values.yml

### ISSUE THREAD

**Issue by tbabej** [ray-project/kuberay#537]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

Installing the helm chart from the current master via

```
$ helm install my-ray-cluster .
```

the installation fails with:

```
Error: INSTALLATION FAILED: template: ray-cluster/templates/raycluster-cluster.yaml:107:9: executing "ray-cluster/templates/raycluster-cluster.yaml" at <ne .Values.worker.disabled true>: error calling ne: incompatible types for comparison
```

This happens because the `disabled` key on the default worker group is undefined.

### Reproduction script

See above.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
Someone else posted an issue about the same thing, but somehow I can't find it.

Also, I'm not able to reproduce this against master. It should be possible by running `helm template .` within the default ray-cluster chart, but I'm not seeing an error.

cc @kevin85421

**Comment by tbabej** [comment]
Not the behaviour I see on my end:

```
$ helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
$ git rev-parse HEAD
5254dcae5c803224674ed1fea10264f6265c5446
$ helm install upstream-test .
Error: INSTALLATION FAILED: template: ray-cluster/templates/raycluster-cluster.yaml:105:9: executing "ray-cluster/templates/raycluster-cluster.yaml" at <ne .Values.worker.disabled true>: error calling ne: incompatible types for comparison
$ helm template .
Error: template: ray-cluster/templates/raycluster-cluster.yaml:105:9: executing "ray-cluster/templates/raycluster-cluster.yaml" at <ne .Values.worker.disabled true>: error calling ne: incompatible types for comparison

Use --debug flag to render out invalid YAML
```

**Comment by tbabej** [comment]
For reference, #543 implements the changes that were necessary on my end to get the chart working (really just a oneliner).

**Comment by DmitriGekhtman** [comment]
Maybe it has something to do with Helm versions...
