### ISSUE TITLE
[Bug] kuberay-operator helm chart v0.3.0 in the restart loop

### ISSUE THREAD

**Issue by Tellz777** [ray-project/kuberay#538]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Tried to install kuberay-operator using helm chart from branch release-0.3. Nothing has been edited from my side.

But after installation in my cluster my kuberay-operator pod is restarting constantly and I see this error inside the logs:

```
ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "RayJob.ray.io", "error": "no matches for kind \"RayJob\" in version \"ray.io/v1alpha1\""}
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/source/source.go:137
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:233
k8s.io/apimachinery/pkg/util/wait.WaitForWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:660
k8s.io/apimachinery/pkg/util/wait.poll
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:594
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:545
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/source/source.go:131
```

**Kubernetes version 1.21.5**

### Reproduction script

1. Clone kuberay repo.
2. Change the branch to release-0.3.
3. Run `helm install kuberay ~/kuberay/helm-chart/kuberay-operator -n kuberay --create-namespace`.
4. Check the logs in kuberay-operator pod.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
It's a known issue that's been resolved in master.
Use the Helm charts pulled from master, or use kustomize/kubectl to deploy the underlying k8s objects.

**Comment by DmitriGekhtman** [comment]
Also, be sure to deploy the CRDs using the commands provided in the docs.

**Comment by DmitriGekhtman** [comment]
Actually -- there is an issue here:

The CRDs here: https://github.com/ray-project/kuberay/tree/master/ray-operator/config/crd don't match the ones here: https://github.com/ray-project/kuberay/tree/master/helm-chart/kuberay-operator/crds

The first link is currently the correct one to install CRDs -- the KubeRay maintainers need to automate a process that keeps the second directory in sync with the first.

**Comment by DmitriGekhtman** [comment]
Here's the fix:
https://github.com/ray-project/kuberay/pull/541

To summarize, KubeRay Helm support is not yet stable -- kubectl and kustomize are preferred for now.

**Comment by Tellz777** [comment]
thx
