### ISSUE TITLE
[Helm][minor] Make "disabled" flag for worker groups optional

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#544]
This is a minor issue with the ray-cluster Helm chart.

It seems that leaving out the `disabled` flag from the default worker group may cause an error when deploying with Helm 3.7.2.

The RayCluster template should be modified such that the `disabled` flag can be removed without issue.
See https://github.com/ray-project/kuberay/issues/537 and https://github.com/ray-project/kuberay/pull/543.

The overall goal is to simplify default configuration as much as possible -- there should not be too many required fields.

**Comment by kevin85421** [comment]
PR: #548
