### ISSUE TITLE
Revisit all exposed fields in helm charts

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#549]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

We need to revisit all exposed fields in helm charts to determine which one should be an optional argument for users. We need to explicitly set the default values for the optional fields. As mentioned in #548 #537, undefined arguments will cause some errors in old helm versions.

### Use case

See related issues.

### Related issues

#537 
#544 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
Making configuration as simple and accessible as possible is important! Hence, P1 (moderate priority).
