### ISSUE TITLE
[Feature] [Helm] Work out versioning and release story for Helm charts

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#553]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

KubeRay master helm charts are hosted in a helm repo as of https://github.com/ray-project/kuberay/pull/545!
Now, we need to figure out versioning and release processes.

We need to do the following for the 0.4.0 KubeRay release (whenever that will be):
- Version the charts following standard practices
- Establish processes for releasing a versioned chart for each KubeRay release
- Document instructions for pulling released charts

### Use case

Basic best practices!

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
See #557 for more details.

**Comment by DmitriGekhtman** [comment]
> See #557 for more details.

That strategy makes sense -- we can revisit this when it's time for the 0.4.0 release.

**Comment by DmitriGekhtman** [comment]
I think we have a plan for this -- I'll set the priority to P2 for now and we'll revisit when we do the 0.4.0 release.

**Comment by kevin85421** [comment]
TODO: Host stable charts in a separate repo.

**Comment by DmitriGekhtman** [comment]
The release is approaching. We need to document a procedure for hosting the charts and carry it out for the 0.4.0 release.

**Comment by DmitriGekhtman** [comment]
> should we delete existing charts which are duplicated as existing tag release?

Yes.

> What's the separate repo we will use?

We need to make one.

**Comment by kevin85421** [comment]
Based on this [post](https://blog.bradmccoy.io/linking-helm-charts-in-github-pages-to-artifacthub-46e02e19abfe), we can create a separate repository to host Helm charts and link the charts in GitHub pages to ArtifactHUB.

@DmitriGekhtman Do you have the write access to create a new repository? Thank you! cc @Jeffwan

**Comment by DmitriGekhtman** [comment]
Sounds like we need to open a new git repository whether we use Artifact Hub or not? In that case maybe we don't need to both with Artifact Hub for now?

**Comment by kevin85421** [comment]
> Sounds like we need to open a new git repository whether we use Artifact Hub or not? In that case maybe we don't need to both with Artifact Hub for now?

The next step is to host Helm charts on GitHub pages. We can discuss whether we need Artifact Hub or not in the future.

**Comment by DmitriGekhtman** [comment]
Ok, sgtm -- let's open a new rayproject repo on Monday.

**Comment by kevin85421** [comment]
@DmitriGekhtman Are there any remaining action items for this issue? Thank you!

**Comment by DmitriGekhtman** [comment]
The remaining item is to release the charts with KubeRay 0.4.0.
I don't think keeping this issue around is helping anything, so will close.
