### ISSUE TITLE
[Bug] chart-releaser-action only release ray-cluster chart

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#561]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen

Problem
---
* We expected that the **chart-releaser-action** ([Link](https://github.com/ray-project/kuberay/commit/f8c37fe2a2adb11a05a9fec4fed0d8c766cb8561)) should create release for every chart in `charts_dir: helm-chart`. That is, we expected 3 chart releases (kuberay-apiserver / kuberay-operator / ray-cluster). However, we only got 1 chart release (`ray-cluster-chart-latest`) as shown in the following figure.
![截圖 2022-09-13 下午3 59 17](https://user-images.githubusercontent.com/20109646/190024187-e95fad6d-f5a7-4073-9527-23854e163de8.png)

* As shown in the following figure, `index.yaml` in the gh-pages branch only has the information of `ray-cluster-chart-latest`. (We expected to have 3 chart information.)
![截圖 2022-09-13 下午4 05 11](https://user-images.githubusercontent.com/20109646/190024482-64b62ea3-0a47-4cf2-b15d-c2280bdc9f24.png)

Root cause
---
* **chart-releaser-action** will try to search the latest tag of the release name ("xxxx-chart-latest" in this example) ([code](https://github.com/helm/chart-releaser-action/blob/main/cr.sh#L57-L63)). Then, **chart-releaser-action** will check whether there is any update between the current version and the latest tag. If there is any update, **chart-releaser-action** will create a new release. If not, it will not create any new release.
![截圖 2022-09-13 下午4 06 28](https://user-images.githubusercontent.com/20109646/190024604-2aa1c9ad-9cf2-4082-bf5d-27e0413b7d92.png)

* In `ray-project/kuberay` repo, the tags (kuberay-apiserver-chart-latest / kuberay-operator-chart-latest / ray-cluster-chart-latest) were created yesterday. To be more specific, the tags are created by the commit https://github.com/ray-project/kuberay/commit/f8c37fe2a2adb11a05a9fec4fed0d8c766cb8561.
![截圖 2022-09-13 下午4 13 51](https://user-images.githubusercontent.com/20109646/190025335-23cbc69c-2a86-4948-8af6-5e4f18e2449a.png)

* Next, check the `helm-chart` directory, and only `ray-cluster` was updated after the commit https://github.com/ray-project/kuberay/commit/f8c37fe2a2adb11a05a9fec4fed0d8c766cb8561. That's why only `ray-cluster-chart-latest` was created.
![截圖 2022-09-13 下午4 15 32](https://user-images.githubusercontent.com/20109646/190025502-a69e5664-4fd9-4b31-8565-68c970ad1950.png)

Solution
---
* Remove the old tags, and trigger the Github Actions again.

### Reproduction script

Discussed above.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Fixed.

* `index.yaml`
![截圖 2022-09-13 下午4 23 05](https://user-images.githubusercontent.com/20109646/190026498-22e8afca-461e-46b8-a8d2-4cc5f0ca16e2.png)

* chart releases
![截圖 2022-09-13 下午4 23 21](https://user-images.githubusercontent.com/20109646/190026520-b8a07bad-3c8b-41c2-bf18-0568d671bc81.png)

**Comment by kevin85421** [comment]
cc @DmitriGekhtman 

Feel free to close this issue if you have no questions.

**Comment by DmitriGekhtman** [comment]
Cool, thanks for fixing that.
