### ISSUE TITLE
[Feature] Synchronize RBAC between Helm charts and Kustomize

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#567]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

@DmitriGekhtman points out that we need to synchronize RBAC between Helm charts and Kustomize.

* [Helm RBAC](https://github.com/ray-project/kuberay/tree/master/helm-chart/kuberay-operator/templates)
* [Kustomize RBAC](https://github.com/ray-project/kuberay/tree/master/ray-operator/config/rbac)

### Related issues

#446 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
YAML files in the chart cannot be parsed by `pyyaml` without rendering (i.e. `helm template`). Take [role.yaml](https://github.com/ray-project/kuberay/blob/master/helm-chart/kuberay-operator/templates/role.yaml#L1-L7) as an example, the helm chart variables `{{ ... }}` are invalid for `pyyaml`. Hence, if we want to synchronize the RBAC YAML files automatically, we need to write a parser for YAML files in Helm. This is doable but may introduce instability in Kuberay.

In my opinion, we have the consistency check for RBAC files in #577 to prevent inconsistency. In addition, Kubebuilder markers for RBAC will not be updated frequently. Hence, I think that synchronizing RBAC YAML files manually is acceptable.

cc @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
@kevin85421 that makes sense.
The consistency check you've added should be sufficient!
I've updated the priority on this one to "wontfix".
