### ISSUE TITLE
[Bug] Cannot build kuberay with Go 1.16

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#568]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

My environment: Mac Pro (Intel i5), go1.16.2 darwin/amd64

```bash
make build
```
![截圖 2022-09-15 上午11 13 58](https://user-images.githubusercontent.com/20109646/190502771-61444a76-e4ce-477f-aeab-93b76b9a89b0.png)

This is very similar to https://github.com/kubernetes-sigs/controller-tools/issues/643. Hence, I doubt whether kuberay supports go 1.16 or not. If we cannot, I will update DEVELOPMENT.md.

My Solution: Update to 1.17.6
```bash
go install golang.org/dl/go1.17.6@latest
go1.17.6 download
export GOROOT=$(go1.17.6 env GOROOT)
export PATH="$GOROOT/bin:$PATH"
make build
```

### Reproduction script

See above.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
Let's just go the easy route here and assert in Development.MD that KubeRay requires Go 1.17.
