### ISSUE TITLE
[Bug] Installation (Helm) doc instructions don't work 

### ISSUE THREAD

**Issue by ckw017** [ray-project/kuberay#569]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

The instructions for installing the chart [here](https://ray-project.github.io/kuberay/deploy/helm/) don't work, since https://api.github.com/repos/ray-project/kuberay/releases/latest points to [this](https://github.com/ray-project/kuberay/releases/tag/ray-cluster-chart-latest) which didn't come with helm-chart-kuberay-operator in assets.

### Reproduction script

Run `helm install kuberay-operator --namespace ray-system --create-namespace $(curl -s https://api.github.com/repos/ray-project/kuberay/releases/latest | grep '"browser_download_url":' | sort | grep -om1 'https.*helm-chart-kuberay-operator.*tgz')`

> Error: INSTALLATION FAILED: must either provide a name or specify --generate-name

### Anything else

 Possible work around here is to change it to `https://api.github.com/repos/ray-project/kuberay/releases` (to pick from the list of all releases) and then do `tail -n 1` to get the latest version. (i.e. `curl -s https://api.github.com/repos/ray-project/kuberay/releases | grep '"browser_download_url":' | sort | grep -o 'https.*helm-chart-kuberay-operator.*tgz' | tail -n 1`).This'll probably degrade over time as more releases happen though.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Thank you for pointing this out! I will fix the document.
