### ISSUE TITLE
[Feature] Add build status, coverage status and go report card into the project

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#57]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Better to add some badges to the project

![image](https://user-images.githubusercontent.com/4739316/136508409-a0d94ad1-08db-4822-99c5-f0186eaf479e.png)

- build status comes from Github actions
- coverage status comes from https://coveralls.io  (I am not sure if permission is a problem)
- go report card comes from https://goreportcard.com

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by davidxia** [comment]
looks like this is fixed and can be closed

**Comment by ravishtiwari** [comment]
We should close this issue, because open issue is giving impression that some part of it is still pending.
