### ISSUE TITLE
[Bug] Service (Serve) changing port from 8000 to 9000 doesn't work

### ISSUE THREAD

**Issue by sihanwang41** [ray-project/kuberay#570]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Change the port in https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray_v1alpha1_rayservice.yaml#L103

Deploy it in the EKS. Curl will get empty reply. 
```
(fresh_env1) sihanwang@Sihans-MacBook-Pro-16 ray % curl -X POST -H 'Content-Type: application/json' localhost:9000 -d '["MANGO", 2]'
curl: (52) Empty reply from server
```

### Reproduction script

Mentioned above

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
A note from Shreyas offline: `host` and `port` has been added to the Serve REST API on the Ray master branch, but not in Ray 2.0: https://docs.ray.io/en/master/serve/rest_api.html#config-schema
