### ISSUE TITLE
[Feature] [Docs] Improve docs around KubeRay API server installation

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#581]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Docs around KubeRay API server installation should be improved.

- Document installing the KubeRay API server using Helm

There is a Helm chart available for deployment of the KubeRay API server.
It is not documented yet. That should be fixed.

- Clearly distinguish the following actions in the docs

Installing the KubeRay Operator.
Installing the KubeRay API Server.
Installing both the KubeRay API Server and the KubeRay Operator.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dhaval0108** [comment]
Couple of suggestions for the documentation from my experience

1. The image used in the current docs for cluster creation i.e. `ray.io/ray:1.9.2` seems to be outdated and led to ImagePullBackOff. Using `rayproject/ray:1.13.1-py37-cpu` resolved the issue for me.
2. `rayStartParams` for both head and worker nodes seems to be a required parameter. Upon passing an empty dictionary I kept getting `[spec.workerGroupSpecs.rayStartParams: Required value, spec.headGroupSpec.rayStartParams: Required value]`. Adding any dummy key-value pair did not work either. Eventually, adding `"rayStartParams": {"num-cpus": "1"}` resolved the issue. Thus, documenting the acceptable parameters would be really helpful.

Thank you for documenting the apiserver in the first place, it has really helped me set up the apiserver and get it running!
