### ISSUE TITLE
[Bug] Pod reconciliation fails if worker pod name is supplied

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#582]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

The operator fails to reconcile multiple worker pods when you specify a name in the worker's pod template.

The issue should be fixed by

- Documenting the problem in KubeRay 0.3.0
- Having the operator handle the presence of a name field

As a first cut, the operator could ignore the name field and log a warning.

### Reproduction script

Deploy a RayCluster with a worker group with replicas >= 2 and supply a name in the pod template.
The operator will fail to generate multiple worker replicas and will show an error creating the second pod.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Thank @DmitriGekhtman for pointing this out! I want to make sure the path of "name in the worker's pod template". Do you mean `spec.workerGroupSpecs[0].template.metadata.name` ([Link](https://github.com/ray-project/kuberay/blob/release-0.3/helm-chart/ray-cluster/templates/raycluster-cluster.yaml#L88))? Thank you!
