### ISSUE TITLE
[Bug] Example program doesn't get executed as specified in docs.

### ISSUE THREAD

**Issue by jasoonn** [ray-project/kuberay#583]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Followed the steps in ray-operator docs, but the logs in the head of ray-cluster don't show the execution of the example program as specified in docs. Besides, the number of jobs get executed is also zero in the dashboard.
Doc link: https://github.com/ray-project/kuberay/tree/master/ray-operator

### Reproduction script
```bash
kubectl create -k "github.com/ray-project/kuberay/ray-operator/config/default?ref=v0.3.0&timeout=90s"
kubectl create -f config/samples/config-map-ray-code.yaml
kubectl create -f config/samples/ray-cluster.heterogeneous.yaml
kubectl logs raycluster-heterogeneous-head-XXXXX  (XXXXX is related to the name of the ray-cluster head)
kubectl port-forward --address 0.0.0.0 svc/raycluster-heterogeneous-head-svc 8265:8265
# Access the dashboard on port 8265. 
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
@jasoonn Thank you for pointing this out! Can you add the document's link in the issue description?

**Comment by jasoonn** [comment]
@kevin85421 I have updated the document's link. Thank you!
