### ISSUE TITLE
[Feature] Support job timeout configuration

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#595]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Job in Ray core doesn't support timeout yet.  This can be easily supported in RayJob controller. 
We can introduce a new filed `timeout` etc and kick the timer when we submit the job. Once time is up, we should stop the job. I think a new status should be introduced as well. 

The challenging part is we also need to consider the failure cases. the timer will be gone if controller crashes, how can we resume the timer after it restarts.

/cc @Basasuya 

### Use case

As a user, I want to pass timeout configuration and terminate my job immediately after it times out. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by asm582** [comment]
It would be good if we can define when the timer is started, do we start the timer when pods are in the `Running` phase?

**Comment by Basasuya** [comment]
@asm582
I think start time is when these job custom resource is created.

Because the job crd supports cluster is already running or create cluster through `clusterSelector` (reference https://github.com/ray-project/kuberay/pull/470)
so the ray pods may be in the running phase before the job is submitted.

**Comment by simon-mo** [comment]
> Job in Ray core doesn't support timeout yet. 
This is currently planned for 2.1 release. https://github.com/ray-project/ray/issues/22736

**Comment by atinsood** [comment]
@Jeffwan how does a ray job maps to RayJob CR.  1 ray job == 1 RayJob CR and is the lifecycle of RayJob CR independent of lifecycle of the cluster. 

what is the benefit that you see from running a job with timeout vs user just calling out delete job. 

@simon-mo on the issue that you pointed out, how will this be different from `ray job stop`

**Comment by Basasuya** [comment]
@simon-mo same question with [atinsood](https://github.com/atinsood), what's the difference with ray job stop and stop_job api in Job Submission SDK ？

**Comment by Basasuya** [comment]
@atinsood
1 ray job == 1 RayJob CR, 
if clusterSelector is used, lifecycle of RayJob CR is independent of lifecycle of the cluster.
if not, the cluster would be deleted with the ray job.
But in current implement, delete rayjob cr will not delete the job in clusterSelector mode(here is one TODO)

job with timeout is the same as you call ray job stop when time is up

**Comment by Jeffwan** [comment]
> @Jeffwan how does a ray job maps to RayJob CR. 1 ray job == 1 RayJob CR and is the lifecycle of RayJob CR independent of lifecycle of the cluster.

1 ray job = 1 RayJob CR. It depends, user can either reuse the cluster or create/delete new cluster. 
- for existing cluster, timeout highly relies on `stop` or `delete` feature in ray core
- for ephemeral cluster, controller can delete the whole cluster. 

> what is the benefit that you see from running a job with timeout vs user just calling out delete job.

user doesn't need to set the timer and calling out delete job. Everything is managed on the server side. 

> @simon-mo on the issue that you pointed out, how will this be different from `ray job stop`

I feel this is a dependency but not the exact same feature

**Comment by kevin85421** [comment]
RayJob has already supported timeout.
