### ISSUE TITLE
[Feature] [RayService] [Doc] Explain how to access Serve application logs

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#610]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

The docs should explain how to access application-level logs from Ray Serve when deploying RayService CRs.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by akshay-anyscale** [comment]
We have done a lot of revamp of the dashboard and observability docs - https://docs.ray.io/en/latest/serve/production-guide/monitoring.html . I believe this can now be resolved
