### ISSUE TITLE
[Bug] HeadGroupSpec.Replicas is unused

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#612]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

This bug is found by #605. When I updated the value of `headGroupSpec.replicas` from 1 to 2. It breaks this [rule](https://github.com/ray-project/kuberay/pull/605/files#diff-665dbdd284a6d0222ec3ddb2710957546d6c3974808765d71fb73d119d4cbef8R187). The number of workers is determined by `worker.Replicas` ([code](https://github.com/ray-project/kuberay/blob/master/ray-operator/controllers/ray/raycluster_controller.go#L461)), but `HeadGroupSpec.Replicas` is unused in KubeRay.

Possible solutions:
(1) Remove the `HeadGroupSpec.Replicas` field.
(2) Create head pods based on `HeadGroupSpec.Replicas`.

### Reproduction script

* Updated the value of `headGroupSpec.replicas` in your YAML file from 1 to 2.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
Thank you for tracking this!
See also https://github.com/ray-project/kuberay/pull/362, which made the field optional.

I think we can handle this by removing the field in the next RayCluster API version.

**Comment by DmitriGekhtman** [comment]
So the solution is bullet (2) in your proposal.
I believe I've already removed the field in all example docs and documented the field as deprecated in the raycluster_types.go.

**Comment by DmitriGekhtman** [comment]
Oh, actually I think I left it in the examples for compatibility with KubeRay 0.2.0.
But now that we've released KubeRay 0.3.0, we can remove the field from all examples! 
@kevin85421 would you mind doing the honors of hunting down and deleting all instances of HeadGroupSpec.replicas in example yamls?

**Comment by Jeffwan** [comment]
We have an issue to track it and we need to do some clean up on the api.

**Comment by kevin85421** [comment]
Related issue: #368
