### ISSUE TITLE
[Bug] test_detached_actor does not handle messages from sockets properly

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#617]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen

https://github.com/ray-project/kuberay/blob/159d57f565cabee36c97fa55cbc5d401bfeef906/tests/compatibility-test.py#L329-L360

[L351](https://github.com/ray-project/kuberay/blob/159d57f565cabee36c97fa55cbc5d401bfeef906/tests/compatibility-test.py#L351) checks whether the received message includes "successful" or not. If the message includes "successful", it will leave the loop. Ideally, we expected the "successful" string is produced by [L339](https://github.com/ray-project/kuberay/blob/159d57f565cabee36c97fa55cbc5d401bfeef906/tests/compatibility-test.py#L339). However, the received message is "Unable to connect to GCS at 10.244.0.8:6379. Check that (1) Ray GCS with matching version started `successfully` at the specified address, and (2) there is no firewall setting preventing access"

The following log is printed by L350.
```bash
INFO:__main__:Unable to connect to GCS at 10.244.0.8:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
```

### Reproduction script

```bash
python3 tests/compatibility-test.py RayFTTestCase.test_detached_actor 2>&1 | tee log
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @DmitriGekhtman

**Comment by DmitriGekhtman** [comment]
cc @wilsonwang371

**Comment by wilsonwang371** [comment]
good catch! I can make some change or are you planing to make a patch? @kevin85421

**Comment by kevin85421** [comment]
@wilsonwang371 I plan to make a patch. I hope to learn more about the KubeRay E2E tests by fixing this issue. Thank you!
