### ISSUE TITLE
[Feature] Restart worker pod when raylet exited

### ISSUE THREAD

**Issue by chenk008** [ray-project/kuberay#62]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

For now, ray-operator generate worker pod command
```
ulimit -n 65536; ray start  --node-ip-address=$MY_POD_IP  --redis-password=LetMeInRay  --address=raycluster-heterogeneous-head-svc:6379  && sleep infinity
```

If the raylet in worker pod exited, the raylet don't restart, so the pod will be useless without raylet.

### Use case

If the raylet in worker pod exited, the raylet should restart.

One option is starting ray with `--block` and delete the `sleep infinity`.
Another option is restarting the pod, so the raylet will start. Maybe we can add some default liveness probe.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
Agree. this should be improved to handle failures
