### ISSUE TITLE
[Bug] Misuse of Docker API and misunderstanding of Ray HA cause test_ray_serve flaky

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#621]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen

See #620.

### Reproduction script

See #620.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @jasoonn 

The following links may be useful.

* #619
* #620 

How does the docker container communicate with the k8s cluster?
* NodePort Service: head pod <--> local
* Docker (`network_mode: host`): container <--> local

You can try `curl 127.0.0.1:10001` (valid port) in both your local laptop and the container. You will get `curl: (56) Recv failure: Connection reset by peer`. You can also run `curl 127.0.0.1:10002` (invalid port), and you will get `curl: (7) Failed to connect to 127.0.0.1 port 10002: Connection refused`.

**Comment by jasoonn** [comment]
@kevin85421 
 Thanks a lot for the information. I will work on it!
