### ISSUE TITLE
[Feature] [apiserver] Support custom cluster/pod annotations in KubeRay apiserver 

### ISSUE THREAD

**Issue by dhaval0108** [ray-project/kuberay#624]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

While creating a ray cluster using KubeRay apiserver (via the POST apis/v1alpha2/namespaces/namespace_name/clusters endpoint), there is no support to add custom annotations. These annotations are sometimes required by users to integrate with their respective in-house solutions. 

### Use case

My team needs to add custom annotations so that the ray cluster can have access to Vault, our secret management service. 

### Related issues

None

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
We have similar requirements in downstream and we extend a field to support it. Feel free to take this story!

**Comment by dhaval0108** [comment]
Thanks @Jeffwan, could you please share more details about your implementation?

**Comment by blublinsky** [comment]
Its done
