### ISSUE TITLE
[Bug] Worker pods crash unexpectedly when gcs_server on head pod is killed 

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#634]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

TODO

### Reproduction script

TODO

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
cc @sihanwang41 @shrekris-anyscale 
re: The potential impact on Ray Serve FT

**Comment by wilsonwang371** [comment]
This might be because worker health check failed which results in the worker failure. 

GCS failure -> worker raylet failure -> Kuberay detected health problem and restarted worker.

**Comment by DmitriGekhtman** [comment]
Ah, then we should look into the worker health check. Probably @iycheng is the most knowledgeable there?
