### ISSUE TITLE
[planning] 0.2 features collection 

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#64]
Let's have some discussion on the features we want to deliver in next release. 

What I like to include in this project is.

1.  ~~core proto API definition which can be used to build backend services and CLI tools~~
2. ~~A gRPC and proxy service to accept cluster CRUD requests~~
3. ~~A kubectl plugin to easily help operate cluster and debug cluster status~~
3.  ~~#62~~
5. #28 
6. #27 
7. Easier kuberay deployment steps. ~~#41~~ ~~#114~~
8. E2E workshop

**Comment by chenk008** [comment]
Please add https://github.com/ray-project/kuberay/issues/62

**Comment by Jeffwan** [comment]
v0.2.0 has been released and we can close this story.
