### ISSUE TITLE
Test sample RayCluster YAMLs to catch invalid or out of date ones

### ISSUE THREAD

**Issue by davidxia** [ray-project/kuberay#642]
There are lots of sample RayCluster YAMLs in this repo. They are at risk of falling out of date with CRD schemas or best practices. Testing the sample YAMLs will help.

[motivation from this issue](https://github.com/ray-project/kuberay/pull/501#issuecomment-1233452960)

**Comment by kevin85421** [comment]
Good idea. The sample YAML files can be easily tested with #605. I can work on this after the test framework is merged.

**Comment by davidxia** [comment]
@kevin85421 thanks so much!
