### ISSUE TITLE
[Feature][Docs] Explain how to specify container command for head pod

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#651]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Some users want to run additional commands when RayClusters are started. For example, a user wants to run `ray start && 
python3 something.py` when the cluster is started.

Users can use `headGroupSpec.template.spec.command` to set the command running in the head pod. However, there is a tricky behavior that may cause users to be confused. If `headGroupSpec.template.spec.command` does not contain the substring `ray start`, KubeRay will replace the command specified by users. See the following code snippet for more details.

https://github.com/ray-project/kuberay/blob/e77b0958b040de22c0eeb9320bff7cefed9ecd7b/ray-operator/controllers/ray/common/pod.go#L307-L325

This software design will introduce more "unknown unknowns" for users, and thus we need:
(1) Update the document (this issue)
(2) Discuss whether remove this behavior and find its replacement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @DmitriGekhtman

**Comment by tgaddair** [comment]
@kevin85421 I wonder if this could be added in a more explicit way. The current behavior of `command` is confusing, as it changes based on the presence or absence of a substring, and if the command is overwritten, the `rayStartParams` essentially become useless (and the user needs to implement this logic themselves).

Maybe there's room for something alongside the `rayStartParams` like a `postStartCommand` (which would be invalid if `block` is set) or similar?

**Comment by DmitriGekhtman** [comment]
There's some discussion about how to get something approximating the desired behavior with a post-start hook:
https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1669986058864489?thread_ts=1669647595.429959&cid=C02GFQ82JPM

**Comment by kevin85421** [comment]
> @kevin85421 I wonder if this could be added in a more explicit way. The current behavior of `command` is confusing, as it changes based on the presence or absence of a substring, and if the command is overwritten, the `rayStartParams` essentially become useless (and the user needs to implement this logic themselves).
> 
> Maybe there's room for something alongside the `rayStartParams` like a `postStartCommand` (which would be invalid if `block` is set) or similar?

I totally agreed with your arguments. In addition, I found a post-start hook (commands execute when the RayCluster is READY) is very important recently. The hook can combine both RayCluster creation and other commands as an atomic operation, and thus make KubeRay more idempotent. One of the use case is to avoid #756. 

cc @architkulkarni

**Comment by kevin85421** [comment]
Add this issue to v0.5.0 release.

**Comment by DmitriGekhtman** [comment]
Yeah, moving the job submission into the entry point makes sense to me. I don't really see the point of decoupling cluster creation and job submission...
Except that it could be nice to submit a new job to an already running cluster...
But that doesn't work so well anyway due to lack of clean isolation between subsequent jobs.

**Comment by kevin85421** [comment]
Related discussion: https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1675378764037199

**Comment by kevin85421** [comment]
Related discussion: https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1676506490994229

Upgrade the priority to P0.
