### ISSUE TITLE
KubeRay 0.4.0 release

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#656]
This is an issue to discuss and track next KubeRay release 0.4.0.
I think it would be great to aim for a release in mid-to-late November.
The improvements over the last release would consist of

- Bug fixes for new and experimental features (e.g. Services, Autoscaling)
- New feature: Stable, properly hosted Helm suppport. (This has been highly requested for months or even years.)

There might not be any fundamentally new features for the release, but I think it makes sense to keep a good release cadence so that folks can benefit from the bug fixes with the confidence afforded by using a stable official release version of the software.

Here is a link to the outstanding issues:
https://github.com/ray-project/kuberay/milestone/4

Let's aim for
- **Branch cut: Wednesday November 23**
- **Release: Wednesday November 30**

**Comment by kevin85421** [comment]
Create a google doc to track all compatibility-related PRs that need to be finalized before release 0.4.0. We can discuss this doc on Nov. 8 or Nov. 22 community sync.

https://docs.google.com/document/d/1IG22TXYJKZxozDKSShixeq2t8zPF26qWoSFL-Wx4vR0/edit

**Comment by Jeffwan** [comment]
@DmitriGekhtman @kevin85421 I think you guys work on lots of stories in v0.4.0. Can we have a release manager from your team?  Let's setup the mechanism and formalize the release process. I will also write some docs and release process based on v0.3.0 experiences.  We have a one release manager and 1-2 people shadow the release if necessary /cc @scarlet25151

**Comment by Jeffwan** [comment]
Let's also ask community the most critical features/bug fixes they like to put in the release just in case we miss them in the v0.4.0 milestone

**Comment by kevin85421** [comment]
> @DmitriGekhtman @kevin85421 I think you guys work on lots of stories in v0.4.0. Can we have a release manager from your team? Let's setup the mechanism and formalize the release process. I will also write some docs and release process based on v0.3.0 experiences. We have a one release manager and 1-2 people shadow the release if necessary /cc @scarlet25151

Good idea! It will be very helpful for KubeRay community to formalize the review process. We can discuss it in today's community sync. I have added them to today's agenda.

**Comment by DmitriGekhtman** [comment]
I volunteer @DmitriGekhtman @kevin85421 @sihanwang41 to co-manage the release from the Anyscale side.

**Comment by kevin85421** [comment]
Close this issue because release 0.4.0 is all done.
