### ISSUE TITLE
[Feature] RayJob support retry

### ISSUE THREAD

**Issue by loleek** [ray-project/kuberay#669]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, rayjob cannot be re-submitted if failed. Can we support job retry and user-defined retry times, because maybe unexpected case happened like node crash or pod killed randomly.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
KubeRay has already supported retry.
