### ISSUE TITLE
[Bug] label rayNodeType is useless

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#679]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Label rayNodeType is useless in the whole KubeRay operator. I guess people are trying to add the label `ray.io/node-type`. 

https://github.com/ray-project/kuberay/blob/f3415f44f97102e9046d61b3d8d2e2b8faae5a97/ray-operator/config/samples/ray-cluster.mini.yaml#L36-L42

https://github.com/ray-project/kuberay/blob/fd06b5bcd32d440ddde753986e1a4b8bfab86d82/ray-operator/controllers/ray/common/constant.go#L7

### Reproduction script

You can apply any RayCluster YAML and use `kubectl describe` to check labels. KubeRay operator will set the label `ray.io/node-type` automatically. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
some examples configuration are useless.  "ray.io/node-type"  are reserved by operator actually. We can just remove those unhelpful labels and clean up the examples.

**Comment by Jeffwan** [comment]
I feel we should always give minimum settings for most of the examples. Just leave one example with details setting.
