### ISSUE TITLE
[Bug][Doc] Increase default operator resource requirements, improve docs

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#685]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

We have some indication from users that the default resource limits for the KubeRay operator may be too small when managing many Ray pods.

See the discussion here: https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1667409518664019

- Increase the default resource limits
- Document the fact that users need to observe resource usage and adjust as needed. 

### Reproduction script

See linked Ray Slack discussion thread.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
We did see some OOM issue internally and bump the resources in downstream. I think this would be helpful

**Comment by DmitriGekhtman** [comment]
> We did see some OOM issue internally and bump the resources in downstream. I think this would be helpful

Any data you could share?
(e.g. how many pods managed and what resource limits you're using?)
