### ISSUE TITLE
[Bug] Compatibility tests of FT features are (still) flakey

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#691]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Example:
https://github.com/ray-project/kuberay/actions/runs/3397833204/jobs/5650377940

### Reproduction script

N/A

### Anything else

Would be great to increase the total pass rate.
There aren't that many tests yet.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
cc @kevin85421 @sihanwang41

**Comment by wilsonwang371** [comment]
I will be working on this.

**Comment by kevin85421** [comment]
This is a known issue. The root causes are:

(1) #638 #634 => Both Kubernetes and KubeRay have fault tolerance mechanisms, and we did not integrate them well.

(2) #618 => Compatibility tests misuse the `kubectl wait` commands. => Some functions in #605 can fix this.

Do we still need to track the progress in this issue or track in #618 #634 #638 separately? Thanks!

**Comment by Jeffwan** [comment]
> Do we still need to track the progress in this issue or track in https://github.com/ray-project/kuberay/issues/618 https://github.com/ray-project/kuberay/issues/634 https://github.com/ray-project/kuberay/issues/638 separately? Thanks!

@kevin85421 Let's use this one as an umbrella issue. This issue should be fixed before v0.4.0 release

**Comment by DmitriGekhtman** [comment]
> This issue should be fixed before v0.4.0 release

Sounds good, I updated the milestone.

**Comment by DmitriGekhtman** [comment]
I think the flakiness of these tests may result from fundamental faults in the underlying functionality.
We may not be able to fix this before the release.

**Comment by kevin85421** [comment]
Move to release 0.5.0.
