### ISSUE TITLE
Improve test quality by either improving or removing unreliable test

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#692]
![image](https://user-images.githubusercontent.com/4739316/200102591-e6120b67-1ba2-47e3-ae6e-6961857df333.png)

This actually looks really bad.  We don't even know it's flaky tests or test failures. 
1. Could maintainers make sure tests pass before merging the PR? 
2. Could maintainers rerun the test for post-submit commits?
3. is there a way to open rerun permission for PR author?

**Comment by kevin85421** [comment]
Every PR will pass all tests before merging. There are a lot of questions in the existing compatibility tests. Some of them are fixed, e.g. #620 and #621. We still need more time to fix all of them.

> Is there a way to open rerun permission for PR author?

This is a good idea. We can discuss this in the next community sync.

**Comment by Jeffwan** [comment]
For short term, I think it's better to rerun the tests for merged commits before the compatibility get fixed

**Comment by Jeffwan** [comment]
![image](https://user-images.githubusercontent.com/4739316/200464984-2472283e-45aa-4412-862b-e70d20dabf07.png)

**Comment by DmitriGekhtman** [comment]
> For short term, I think it's better to rerun the tests for merged commits before the compatibility get fixed

Makes sense.

Some other potential actions we considered:
Isolate flaky tests.
Move Fault Tolerance tests to a nightly pipeline.
Consider modifying test timeouts.
