### ISSUE TITLE
Revisit chart release strategy 

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#693]
![image](https://user-images.githubusercontent.com/4739316/200104196-a668ed12-ee73-405b-9f01-35f672d06568.png)

I think we talked about chart release in past issue and I notice chart is released as the part of the release. 

Ideally we want the static website to host the chart as the source. but we are blocked due to website. 
So new added charts are not helping, right? I notice we are still using v0.3.0 asset in the readme.md

**Comment by kevin85421** [comment]
We will use a separate repository to host the server for our charts before releasing 0.4.0. I will work on this near the branch cut. There are some issues related to hosting helm charts in the KubeRay repository.

https://github.com/ray-project/kuberay/pull/545
https://github.com/ray-project/kuberay/issues/561

**Comment by kevin85421** [comment]
The progress is tracked at https://github.com/ray-project/kuberay/issues/553. Do we need to open two issues at the same time or close one of them? Thanks!

**Comment by DmitriGekhtman** [comment]
This issue is indeed a duplicate. There might be some dangling assets from our first attempt at hosting charts.
I think @kevin85421 found it would be most straightforward to host release charts using a separate repo.
