### ISSUE TITLE
use grpc probe to query health status of Ray 2.2 and above 

### ISSUE THREAD

**Issue by wilsonwang371** [ray-project/kuberay#694]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

https://github.com/grpc-ecosystem/grpc-health-probe

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Close this one in favor of #1554.
