### ISSUE TITLE
[Feature] Migrate CI infra from GitHub Actions to Buildkite

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#695]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

KubeRay CI has some resource limitations (especially CPU), and thus most sample YAMLs cannot be tested in KubeRay CI (GitHub Actions). Hence, I open this issue to track the progress of configuration tests on Ray CI. See #678 for more details.

### Related issues

#678 
#642
#731 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
The more appropriate long-term move would be to unify KubeRay's CI infrastructure with the Ray CI's Buildkite infra. That way, we could run tests per-commit in the KubeRay CI.

**Comment by krfricke** [comment]
cc @zhe-thoughts @matthewdeng for visibility. I'm helping set up the KuberRay CI this week

**Comment by kevin85421** [comment]
Thanks @krfricke! This is the most important item for KubeRay v0.5.0.

**Comment by gvspraveen** [comment]
Currently we are targeting every alternate Ray release. So next one will be after Ray 2.4 (some time early April)
