### ISSUE TITLE
[Feature] [Discussion] [Ray Autoscaler] More efficient pod state fetch in autoscaler.

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#700]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

This is basically the same as the Ray issue https://github.com/ray-project/ray/issues/21656
I'm opening a KubeRay issue to solicit fresh discussion.

Currently, the autoscaler sends a "list pods" request to the K8s API server once per autoscaler update -- by default, that's once per 5 seconds.

These list requests are taxing on K8s, particularly since they do not specify a resourceVersion. If there are many Ray clusters running or many Ray pods, one may see performance degradation in the autoscaler or perhaps even in the K8s cluster in general.

The usual approach is to
- Query the API server only from centralized components.
- Use informers to maintain a cache of state in a performant way

The problem is that
- There are could be many Ray autoscalers running in the K8s cluster
- The autoscaler is written in Python. Informers are a golang tool.

# Background discussion

From the K8s docs:
https://kubernetes.io/docs/reference/using-api/api-concepts/#semantics-for-get-and-list

> Unless you have strong consistency requirements, using resourceVersionMatch=NotOlderThan and a known resourceVersion is preferable since it can achieve better performance and scalability of your cluster than leaving resourceVersion and resourceVersionMatch unset, which requires quorum read to be served.

From the GKE docs:
https://cloud.google.com/kubernetes-engine/docs/best-practices/scalability

> You can use periodic LIST calls. However, this is an inefficient and expensive approach for both the caller and the server because all objects must be loaded to the memory, serialized, and transferred each time. The excessive use of LIST requests might overload the control plane or generate heavy throttling of such requests.

# Potential solutions

## 1 (Preferred)
Have the operator add a last modified pod resourceVersion to the status field of the RayCluster CR.
The autoscaler can use that resourceVersion in list requests to avoid forcing a quorum read.
The resourceVersion could be obtained by having the operator make a trivial update to the head pod (update an annotation or something) -- the resourceVersion could then be read from the response.

Pro:
Probably simplest.

Con:
Still potentially have some performance issues with sending many list requests.

## 2 
Have the autoscaler query a gRPC endpoint for pod state.
The operator would run the server and would use an informer to serve the info.

Pro:
Probably the most performant option.

Con:
High maintenance burden. Complex.

## 3 (Maybe ok)
Have the operator write the list of pods in the Ray cluster to RayCluster.status.
The autoscaler reads from the pod list from the status.
To be conservative, the autoscaler would only write a pod list to the status if autoscaling is enabled.

Pro:
Simpler compared to gRPC solution. Doesn't require autoscaler to make any list requests.
Vaguely idiomatic: external entities like the autoscaler derive information on the current state of a system from the status of the K8s object that represents the system. 

Con:
Nonstandard practice for workload controllers. The Ray cluster's pod list could be a lot of data to write to a K8s object for large Ray clusters.

### Use case

Don't tank the K8s cluster when running many Ray clusters.

### Related issues

https://github.com/ray-project/ray/issues/21656

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
cc @akanso @Jeffwan @pcmoritz @sriram-anyscale @wuisawesome for any thoughts

**Comment by wuisawesome** [comment]
Instinctively, some version of option 3 makes the most sense to me. It feels like the autoscaler shouldn't have to list pods, it should just read the status of a ray cluster CR (which shouldn't have to contain the full pod spec for every pod, some smaller subset like just the ip and node type should be sufficient). 

Note an implementation detail to make this race-condition free, is that we should write the CR status _before_ launching the pods if possible to ensure the node provider can guarantee `non_terminated_nodes` displays the node before `create_node` finishes.

**Comment by DmitriGekhtman** [comment]
1000 pods, 64 bytes each: ~100kb of data.

I think the limit of etcd/k8s for storage for a single object is something like 1MB. It's slightly uncomfortable that we're within an order of magnitude.

It's more if we want to separately include the other pieces of data the autoscaler needs (ip, node type, node kind, container status). The autoscaler could get that data with relatively cheaper read requests.

**Comment by DmitriGekhtman** [comment]
Side: I think it would be better if we had the following solution (which I think I've heard both @wuisawesome and @sriram-anyscale suggest)

## 4
Rewrite the autoscaler such that it does not require listing external cluster state.

### Pro
Avoid this entire discussion.

### Con
Significant code change.

**Comment by DmitriGekhtman** [comment]
I'm warming up to option 3 (write some pod data to status for autoscaling clusters).
I might try it out and load test it.

**Comment by wuisawesome** [comment]
> I think the limit of etcd/k8s for storage for a single object is something like 1MB. It's slightly uncomfortable that we're within an order of magnitude.

FWIW for any a reasonable ray config, that cluster is both larger than the ray scalability envelope and also within an order of magnitude of the k8s scalability envelope.

**Comment by DmitriGekhtman** [comment]
Will do some experiments.

> is that we should write the CR status before launching the pods if possible to ensure the node provider can guarantee non_terminated_nodes displays the node before create_node finishes.

I think the best we can do is try to get state that's as up-to-date as possible -- maybe just write it at the beginning and end of the update?

@kevin85421 observed a situation in which the operator's handling of state was not even consistent enough for itself --
there was a double-launch followed by deletion apparently due to staleness of the operator's own pod cache.
(Issue/discussion for that forthcoming...)

**Comment by DmitriGekhtman** [comment]
^ though re: cache staleness, I just took a look at the replicaset controller -- at naive first glance, it doesn't do anything differently -- it just gets a pod list from informer cache, computes a diff, and creates the desired number of pods...so, shrug...

**Comment by kevin85421** [comment]
> Will do some experiments.
> 
> > is that we should write the CR status before launching the pods if possible to ensure the node provider can guarantee non_terminated_nodes displays the node before create_node finishes.
> 
> I think the best we can do is try to get state that's as up-to-date as possible -- maybe write it both at the beginning and end of the update?
> 
> @kevin85421 observed a situation in which the operator's handling of state was not even consistent enough for itself -- there was a double creation followed by deletion apparently due to staleness of the operator's own pod cache. (Issue/discussion for that forthcoming...)

#704

**Comment by DmitriGekhtman** [comment]
I am a little shaky on consistency requirements and on the ramifications for reconciliation of updating the status with a bunch of cached pod data. See also the discussion in https://github.com/ray-project/kuberay/issues/704
If there were a simple way of extracting a new-enough resourceVersion and communicating it to the autoscaler, that would be great.
Will think a bit more, but I'm basically out of my depth regarding K8s internals and controller development.

**Comment by DmitriGekhtman** [comment]
I propose this hack: 
Before obtaining pod data, the autoscaler writes some arbitrary annotation to the head pod, looks at the resource version in the response, and uses that in the list call.

**Comment by DmitriGekhtman** [comment]
The name of the head pod can be supplied to the autoscaler as an env variable.

**Comment by DmitriGekhtman** [comment]
Thanks all, this is solved using the solution I proposed in the last few comments.
This issue was a very helpful rubber duck discussion.
