### ISSUE TITLE
[Feature] [CI] Track flakey KubeRay tests

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#709]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Create a flakey test tracker for KubeRay similar to https://flakey-tests.ray.io/

### Use case

I recently found myself asking "when did x test become flakey?"

### Related issues

https://github.com/ray-project/kuberay/issues/704
https://github.com/ray-project/kuberay/issues/691
https://github.com/ray-project/kuberay/issues/692

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
This is outdated.
