### ISSUE TITLE
[Bug] KubeRay does not show clear error for duplicated `groupName` field

### ISSUE THREAD

**Issue by spolcyn** [ray-project/kuberay#718]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

1. Saw: When a cluster YML specifies 2 worker pod types with the same `groupName`, the cluster goes into a loop of creating and immediately terminating all pods with that `groupName`
2. Expected: The autoscaler or `kuberay-operator` fails with a clear error that "Multiple worker pod types have the same `groupName`"

Running Kuberay 0.3.0 and nightly, Ray v2.0.1

### Reproduction script

Use any cluster YML with two worker pod types, both with the same `groupName`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
Thanks for posting this. There's a general theme here that we need to raise better errors and improve observability of the system.
