### ISSUE TITLE
[Feature] Test sample RayService YAMLs to catch invalid or out of date ones

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#719]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Use https://github.com/ray-project/kuberay/pull/605 to test sample RayService YAMLs.

### Use case

Catch invalid or out of date RayService YAML.

### Related issues

#605 
#642 
#678

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
@jasoonn will work on this issue.

**Comment by jasoonn** [comment]
@kevin85421 Thanks for the opportunity. I will wok on this!
