### ISSUE TITLE
[Feature][Discussion] Interactive development for Ray on Kubernetes

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#725]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

There isn't a clear recommended path for interactive and iterative development for Ray on Kubernetes.

Many companies have discovered workflows that involve accessing deploying ephemeral Ray Clusters from a Jupyter notebook environment and connecting to said clusters using Ray Client. The proposed KubeFlow integration would use this method: 
https://github.com/ray-project/kuberay/issues/502
https://github.com/kubeflow/kubeflow/issues/6680
https://cloud.google.com/blog/products/ai-machine-learning/build-a-ml-platform-with-kubeflow-and-ray-on-gke
This was the original intended pattern for Ray Client usage. However, for various reasons, the Ray team has decided to de-emphasize Ray Client and place it maintenance mode.

This dissonance needs to be resolved.
One idea is to set up a Jupyter notebook pod in the same namespace, then have the pod could connect to Ray via `ray start --address=<head-address>`. For this strategy to work, the Ray team would need to provide a robust way to avoid scheduling tasks and actors on a designated Ray worker node.

Another potential direction is to enrich the Ray Job client to make it more interactive, for example by allowing the Job client to return Python objects.

Another direction is to just go with the flow and endorse Ray Client, doing our best to understand and document its limitations and adding many screaming warnings that Ray Client is not suitable for production job submission. 

### Use case

Provide a clear, documented path for interactive development on Kubernetes.

### Related issues

https://github.com/ray-project/kuberay/issues/502

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
We intend to release KubeRay 0.4.0 before the end of the year.
I think it's a bit too rushed to include in this release, particularly since Anyscale product management leadership will want to discuss.
cc @richardliaw @anabranch

**Comment by DmitriGekhtman** [comment]
It would indeed be great to release in December.
For that to happen, we must make the branch cut soon (ideally next week)

So I think it's better not to add major features to the release right now.

**Comment by DmitriGekhtman** [comment]
@scarlet25151 @Jeffwan you should feel free to open PRs upstreaming workspace support after the 0.4.0 release.
I think it could make sense as a new feature for 0.5.0 release.

**Comment by Jeffwan** [comment]
@DmitriGekhtman We were busy with internal stuff and didn't get chance to make more contribution in last cycle. Now we are good. We will share more progress with the community.
