### ISSUE TITLE
[Feature][Anyscale team] Formal user testing for KubeRay

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#732]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

This issue is aimed for consumption by the Anyscale team. 

Anyscale has established a formal process for user testing of Ray features.
This process should be carried out for various aspects of deployment of Ray on K8s.

For purposes of sequencing work:
This process should be carried out after various already-established issues are resolved.

### Use case

Aim to make KubeRay easy-to-use for non-experts.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
I am not familiar with the definition of user testing. Do you mind explaining it more? Thank you!

**Comment by DmitriGekhtman** [comment]
Will follow up offline!

**Comment by DmitriGekhtman** [comment]
I think the wide range of configuration options (kustomize, Helm, KubeRay API server) may be confusing.

Thus, it would be good to explicitly test if users are able to configure a Ray cluster satisfying x,y,z conditions.

**Comment by Wendi-anyscale** [comment]
DM me when we r ready to kickoff this
