### ISSUE TITLE
[Feature] Better validation for the RayCluster CRD, via validating webhooks

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#736]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

There are many aspects of KubeRay config validation that cannot be handled by CRD schema validation.

We have some limited validation functionality within the operator -- if the operator detects certain misconfigurations, it will refuse to reconcile and will instead write and some sort of error state to the status field.
[Code reference.](https://github.com/ray-project/kuberay/blob/3581b91b71dc0ce1bbf33904b4c0cf817a9767a9/ray-operator/controllers/ray/common/pod.go#L811)

However, it would be a better user experience if the CR simply failed validation up submission.
The standard way to do this would be to take advantage of KubeBuilder's support for validating webhooks.

This would make it easy to resolve UX issues like the one described here:
https://github.com/ray-project/kuberay/issues/718

### Use case

Less painful configuration experience.

### Related issues

https://github.com/ray-project/kuberay/issues/718

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
some insight from @Jeffwan 

> let's try to leverage CRD validation (client side) as much as possible. If that's not enough, then let's introduce webhook and also make it optional (lots of companies do not allow to install webhook by themselves, which makes deployment 
difficult)

**Comment by davidxia** [comment]
@kevin85421 has anyone picked up this issue? Open to contributions here?
