### ISSUE TITLE
[Feature] [Docs] Examples of using the Ray autoscaler

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#743]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Document examples of using autoscaling.
The [current docs](https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/configuring-autoscaling.html) just present the theory.

### Related issues

Replaces https://github.com/ray-project/ray/issues/27803

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
The doc has already been updated.
