### ISSUE TITLE
[Feature] kuberay apiserver need UT for new added apis of rayjobs and rayservice 

### ISSUE THREAD

**Issue by scarlet25151** [ray-project/kuberay#754]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

some bugs happened like #734 because of lacking some UT when adding the logic and maybe some manually e2e check may not find the bugs add effort for further bug fix, we need add more detail UTs in kuberay-apiserver to add stability. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by scarlet25151** [comment]
Here after offline talk with @wilsonwang371 we think we need more precise unit testing to check whether the apiserver generated rayservice and rayjob works well in kubernetes cluster, it may not be ready for both rayservice and rayjob before the release cut this week, we may propose to have it in the next release, WDYT @DmitriGekhtman?

**Comment by DmitriGekhtman** [comment]
That sounds fine to me.
I think the actual action item ahead of the release is to clearly document that RayJobs and RayServices are experimental.

**Comment by kevin85421** [comment]
@blublinsky has identified that this KubeRay API server issue can be closed.
