### ISSUE TITLE
[Feature] E2E Test plan for RayService

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#762]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

We should have a test plan for RayService after #759 is merged.

### Related issues

#759 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Assign to the expert of RayService @shrekris-anyscale. We can schedule a meeting to discuss the plan.

**Comment by gvspraveen** [comment]
We need to test following as first priority to make rayservice ready to onboard

- Autoscaling
- In place updates
- roll outs

**Comment by kevin85421** [comment]
Closed by https://github.com/ray-project/kuberay/pull/1167
