### ISSUE TITLE
[Feature] Replace Docker container and NodePort with Kubernetes Pod

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#764]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, [compatibility-test.py](https://github.com/ray-project/kuberay/blob/49c44bff5a807a680248b30b5563f985a075be9b/tests/compatibility-test.py) uses Docker container with `network_mode='host'` to communicate with Ray Pod via Kubernetes NodePort service. This is weird and may introduces instability. To elaborate, the tests can only be stable when all of the Docker container, your host, KinD, and NodePort work properly. Hence, I proposed to replace the Docker container with a Kubernetes Pod, and thus no need to create Docker container, check host configuration, configure `extraPortMappings` for KinD, and create NodePort service (we can use the existing ClusterIP service instead.).

https://github.com/ray-project/kuberay/blob/49c44bff5a807a680248b30b5563f985a075be9b/tests/compatibility-test.py#L176-L185

In my expectation, the integration tests will become more stable when this issue is fixed. When we execute a Ray script in a Docker container (e.g. `test_detached_actor_1.py`) to communicate with a healthy RayCluster, it sometimes throws the following exception `Ray Client connection timed out. Ensure that the Ray Client port on the head node is reachable from your local machine` ([Link](https://github.com/ray-project/kuberay/actions/runs/3568210619/jobs/5997787073)).

https://github.com/ray-project/kuberay/blob/49c44bff5a807a680248b30b5563f985a075be9b/tests/compatibility-test.py#L222-L231

### Use case
Improve the stability of integration tests.

### Related issues
#759 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
@jasoonn are you interested in taking this issue?

**Comment by DmitriGekhtman** [comment]
I think it would be simpler to just use `kubectl exec` for command execution in the tests.
You don't need a proxy container to submit commands.

**Comment by kevin85421** [comment]
> I think it would be simpler to just use `kubectl exec` to execute commands in the Ray head pod. You don't need a proxy container to submit commands.

Agree, `kubectl exec` is a better solution. We can use `kubectl exec` in most cases, but in some cases (e.g. use `curl` to test RayService) cannot because the head Pod does not have related dependencies.

**Comment by wilsonwang371** [comment]
The original reason we use a docker container is that we want to test a client connecting to ray cluster from outside the k8s cluster. In this case, we can test HA and other features. If we run the task inside a container in k8s cluster, this might not cover all the possible scenarios.

**Comment by DmitriGekhtman** [comment]
> The original reason we use a docker container is that we want to test a client connecting to ray cluster from outside the k8s cluster. In this case, we can test HA and other features. If we run the task inside a container in k8s cluster, this might not cover all the possible scenarios.

In that case, I think there should be a dedicated test for Ray client.

**Comment by wilsonwang371** [comment]
> > The original reason we use a docker container is that we want to test a client connecting to ray cluster from outside the k8s cluster. In this case, we can test HA and other features. If we run the task inside a container in k8s cluster, this might not cover all the possible scenarios.
> 
> In that case, I think there should be a dedicated test for Ray client.

agreed.

**Comment by kevin85421** [comment]
> The original reason we use a docker container is that we want to test a client connecting to ray cluster from outside the k8s cluster. In this case, we can test HA and other features. If we run the task inside a container in k8s cluster, this might not cover all the possible scenarios.

QQ: Would you mind explaining more about "If we run the task inside a container in k8s cluster, this might not cover all the possible scenarios."? Thanks!

We can create a new Pod (not belonging to the RayCluster) and test Ray Client via ClusterIP. Do I miss anything? Thanks!

**Comment by wilsonwang371** [comment]
> > The original reason we use a docker container is that we want to test a client connecting to ray cluster from outside the k8s cluster. In this case, we can test HA and other features. If we run the task inside a container in k8s cluster, this might not cover all the possible scenarios.
> 
> QQ: Would you mind explaining more about "If we run the task inside a container in k8s cluster, this might not cover all the possible scenarios."? Thanks!
> 
> We can create a new Pod (not belonging to the RayCluster) and test Ray Client via ClusterIP. Do I miss anything? Thanks!

the original design is to test the connectivity from outside the k8s cluster. for example, to simulate some user connecting to AWS cluster on his/her laptop.

**Comment by kevin85421** [comment]
> the original design is to test the connectivity from outside the k8s cluster. for example, to simulate some user connecting to AWS cluster on his/her laptop.

Thank you for your reply!

In this case, maybe `ray job` is better than `ray client`? `ray job` can prevent users from installing a lot of dependencies on their laptops. cc @DmitriGekhtman @architkulkarni

**Comment by DmitriGekhtman** [comment]
> the original design is to test the connectivity from outside the k8s cluster.

You'd need to test that internally, as appropriate for your network infrastructure.

The test in the Ray CI technically does test connectivity outside of the K8s cluster -- it simply installs Ray in the test environment (outside of the kind cluster) and uses Ray client from that test environment by port-forwarding the default cluster ip service.

**Comment by DmitriGekhtman** [comment]
> > the original design is to test the connectivity from outside the k8s cluster. for example, to simulate some user connecting to AWS cluster on his/her laptop.
> 
> Thank you for your reply!
> 
> In this case, maybe `ray job` is better than `ray client`? `ray job` can prevent users from installing a lot of dependencies on their laptops. cc @DmitriGekhtman @architkulkarni

Support for Ray Jobs is indeed better -- the Ray maintainers are uncomfortable about Ray Client's existence.

**Comment by wilsonwang371** [comment]
> > the original design is to test the connectivity from outside the k8s cluster.
> 
> You'd need to test that internally, as appropriate for your network infrastructure.
> 
> The test in the Ray CI technically does test connectivity outside of the K8s cluster -- it simply installs Ray in the test environment (outside of the kind cluster) and uses Ray client from that test environment by port-forwarding the default cluster ip service.

This was the case for a user using client connecting from outside the k8s cluster behind a load balancer. The Ray HA test case was designed for this scenario. The assumption is, if it works for this kind of setup, it should be working for other simpler scenarios. But anyway, as just mentioned, the Ray maintainers are uncomfortable about Ray Client's existence.

**Comment by DmitriGekhtman** [comment]
Connecting from within the same K8s cluster would ensure a much more robust (and probably also secure) experience.

**Comment by DmitriGekhtman** [comment]
Definitely no guarantees on Ray Client functionality in various network environments.

**Comment by architkulkarni** [comment]
Agree with everything Dmitri said, we should move towards using Ray Jobs instead of Ray Client.
