### ISSUE TITLE
[Feature] Improve the observability of integration tests

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#766]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

We can reuse the function [show_cluster_info()](https://github.com/ray-project/kuberay/blob/49c44bff5a807a680248b30b5563f985a075be9b/tests/framework/prototype.py#L120) to get more information when CI tests fail. To achieve this goal, we need to:

(1) `show_cluster_info()` needs to support operator installed by Helm. The operator installed by Helm does not have the label `app.kubernetes.io/component`. It has `app.kubernetes.io/instance` instead.

(2) Check if the test passes or not in [tearDown()](https://docs.python.org/3/library/unittest.html#unittest.TestCase.tearDown). Call `show_cluster_info()` if the test fails.

### Use case

Observability improvement can help us debug CI failures. 

### Related issues

#759 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
@jasoonn are you interested in this issue?

**Comment by jasoonn** [comment]
@kevin85421 I am interested in it. I will work on it.

**Comment by jasoonn** [comment]
@kevin85421 It seems like unittest do not support getting result in ```teardown()```. The only way I found to check if the test pass in ```teardown``` is to access the private field ```self._outcome``` in unittest.TestCase object([reference](https://stackoverflow.com/questions/4414234/getting-pythons-unittest-results-in-a-teardown-method)). Do you think I should implement in this way?

**Comment by jasoonn** [comment]
The fields in ```self._outcome``` changes in Python 3.11. It seems like accessing self._outcome in unittest.TestCase is not a robust approach. In this case, I will call ```show_cluster_info``` in [shell_subprocess_run](https://github.com/ray-project/kuberay/blob/49c44bff5a807a680248b30b5563f985a075be9b/tests/framework/prototype.py#L84) when the return code of the execution is not 0.
