### ISSUE TITLE
[Feature] Move some functions from prototype test framework to a new utils file

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#774]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

 > All of the objects that are not directly related to the prototype test framework should probably live in the utils file. The objects that should be moved include `CONST`, `K8S_CLUSTER_MANAGER`, `OperatorManager`, and `shell_subprocess_run`.
_Originally posted by @DmitriGekhtman in https://github.com/ray-project/kuberay/pull/759#discussion_r1036201107_
      

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
This can be handled as part of a future test PR.
