### ISSUE TITLE
[Bug] GCS HA pod event handling emits logs about irrelevant pods

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#785]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

The current GCS HA logic causes the operator to emit events about unrelated pods.
See this discussion https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1670033400902369?thread_ts=1669943575.114289&cid=C01DLHZHRBJ
That should be fixed.

cc some subset of the people who have a stake in GCS HA support @iycheng @sihanwang41 @shrekris-anyscale 

### Reproduction script

Enable GCS HA support while running other workloads.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
The filter for Kubernetes events is improved by https://github.com/ray-project/kuberay/pull/946. It will still receive some unrelated events, but filter all events in the resource event filters requiring two lookup operations for the local cache. See the PR description of https://github.com/ray-project/kuberay/pull/996 for more details. The next step may remove the Kubernetes informer. Close this issue.
