### ISSUE TITLE
[Bug] kuberay/kuberay-operator chart version 0.4.0 installs nightly operator

### ISSUE THREAD

**Issue by tekumara** [ray-project/kuberay#786]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

As per the [docs](https://github.com/ray-project/kuberay/blob/master/docs/deploy/installation.md#stable-version) I expected the stable version to be installed.

### Reproduction script

```
helm repo add kuberay https://ray-project.github.io/kuberay-helm/
...
helm install kuberay-operator kuberay/kuberay-operator --version 0.4.0
...
kubectl get deployment -o "custom-columns=:spec.template.spec.containers[*].image"

kuberay/operator:nightly
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Thank @tekumara for this issue! We did the branch cut for release v0.4.0 yesterday (Dec. 2) and updated the command to `--version 0.4.0` before the actual release of v0.4.0 (next week). Sorry for the inconvenience.

**Comment by kevin85421** [comment]
This issue has already been fixed. Close this issue.

![截圖 2022-12-12 下午11 47 36](https://user-images.githubusercontent.com/20109646/207256648-79eaf3f5-3367-4e65-be3c-e56ddc893072.png)
