### ISSUE TITLE
[Bug] API Server Helm Chart Fails

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#806]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

apiserver

### What happened + What you expected to happen

The default Helm installation fails in master. Specifically, the associated service is not correctly created.

### Reproduction script

```
helm install kuberay-apiserver kuberay-apiserver/
Error: INSTALLATION FAILED: Service "kuberay-apiserver-service" is invalid: spec.ports[0].nodePort: Invalid value: 31888: provided port is already allocated
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
This is a release blocker.

**Comment by scarlet25151** [comment]
Got it, let me double check that.

**Comment by scarlet25151** [comment]
@DmitriGekhtman could you please be more specific more abort the environment you are testing? For example the branch your are using, I've done a quick check in my local kind cluster and using the master branch, seems like I didn't come up with that issue?
![image](https://user-images.githubusercontent.com/38214590/206071050-7e1f5c23-594a-49ad-9ef8-29b797b7e626.png)

**Comment by DmitriGekhtman** [comment]
Sorry about that -- I had a dangling `kuberay-apiserver` service lying around, which conflicted with the chart. After removing the service, things worked!
