### ISSUE TITLE
[HelmChart] No documentation how to use customized image (for development) in HelmChart instruction 

### ISSUE THREAD

**Issue by sihanwang41** [ray-project/kuberay#818]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I have built my own image in my own docker hub, but not able to find instruction where to update the helm chart to use the image.

### Reproduction script

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
I agree that the docs should be better on this point.

You might have already figured this out, but you can edit the image in values.yaml: 
https://github.com/ray-project/kuberay/blob/16fd58be7e3af171aa83cdb3aee111b2b438013f/helm-chart/kuberay-operator/values.yaml#L5-L8

**Comment by kevin85421** [comment]
Thank @sihanwang41 for pointing this out! I will work on this.
