### ISSUE TITLE
[Feature] Add RateLimiters for controllers

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#820]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Increase the KubeRay operator's scalability by reducing network traffic.

### Related issues

https://github.com/ray-project/ray/issues/28652

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
seems related issue is not lated to network traffic? It's the event filtering problem? Do we like to add rate limiters?
