### ISSUE TITLE
[Bug] [CI] CI doesn't have permissions to push to kuberay dockerhub

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#827]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen

All image push jobs in the CI are failing due to a permissions issue.

### Reproduction script

https://github.com/ray-project/kuberay/actions/runs/3654066685/jobs/6174159064

### Anything else

I first noticed this last night (December 8)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
@DmitriGekhtman Seems this job is recently added. https://github.com/ray-project/kuberay/blob/master/.github/workflows/image-release.yaml#L63

What's the secret configured there?

**Comment by Jeffwan** [comment]
This is the latest ci job with docker login https://github.com/ray-project/kuberay/actions/runs/3661359804/jobs/6189495597

**Comment by Jeffwan** [comment]
BTW, we are using free docker account, team size and download quota are very limited. Let's see if we can find sponsorship and we can upgrade to an enterprise account.

**Comment by DmitriGekhtman** [comment]
> Let's see if we can find sponsorship and we can upgrade to an enterprise account.

cc @pcmoritz? :)
