### ISSUE TITLE
[Docs] Review the Ray docs on Kubernetes deployment

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/kuberay#828]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Review the [Ray docs on Kubernetes deployment](https://docs.ray.io/en/latest/cluster/kubernetes/index.html) and ensure they provide a good (or at least painless) user experience.

Development of these docs was rushed during the KubeRay 0.3.0 / Ray 2.0.0 release -- there's much that could be improved. Anyscale employees can refer to the internal document written by @waleedkadous for particular issues that need improvement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
[getting-started.html](https://docs.ray.io/en/latest/cluster/kubernetes/getting-started.html) is out-of-date. The outdated document may cause users to fail to run examples (e.g. https://github.com/ray-project/kuberay/pull/851#issuecomment-1369899522). I will update the documents soon.

**Comment by kevin85421** [comment]
Related discussion: https://github.com/ray-project/ray/issues/31694

**Comment by kevin85421** [comment]
TODO: https://github.com/ray-project/kuberay/issues/441#issuecomment-1344726007
