### ISSUE TITLE
[dockerhub] Upgrade from free account to pro?

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#829]
Follow up of https://github.com/ray-project/kuberay/issues/827. 

I made a mistake this week and carelessly break the CI (pushing images to dockerhub).  Free tier only support limited team and 3 members in an organization. I didn't notice the CI bot user and remove it from the ci team.. 

Since we may have more collaborators who will attend the release process. Does the community think we should have a pro tier instead? It will also provide more quota and we will get lower chance meeting rate limit issue when downloading the images

**Comment by kevin85421** [comment]
Thank you for pointing this out! DockerHub also has other limitations. For example, DockerHub only allows 100 pulls per 6 hours per IP address. We need to think of other solutions (e.g. (1) upgrade DockerHub's plan (2) quay.io (3) others).

Related discussion: https://github.com/ray-project/kuberay/pull/750#issuecomment-1329739242

**Comment by anishasthana** [comment]
I raised #1133, which is somewhat related to this as well.

**Comment by kevin85421** [comment]
Close this issue in favor of #1133.
