### ISSUE TITLE
[Bug] A mini RayService requires more than 90 seconds to converge

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#838]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

See #837 for more details.

**test_sample_rayservice_yamls.py** is very flaky (~20% to fail). Previously, it was very stable. https://github.com/ray-project/kuberay/pull/731 said that "I have run more than ten times on my cluster, and the result is always pass.". 
  * [root cause]: RayServiceAddCREvent fails to converge due to the absence of `rayservice-sample-serve-svc` in 90 seconds. It is too slow.

### Reproduction script

Run the following command several times.
```sh
RAY_IMAGE=rayproject/ray:2.1.0 OPERATOR_IMAGE=kuberay/operator:nightly python3 tests/test_sample_rayservice_yamls.py
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by architkulkarni** [comment]
Just recording the time it took when I ran this test on my laptop:
`--- RayServiceAddCREvent 205.55406618118286 seconds ---`

**Comment by kevin85421** [comment]
It becomes stable after #1000. The RayService test passes 25 times consecutively.

**Comment by kevin85421** [comment]
```sh
RAY_IMAGE=rayproject/ray:2.4.0 OPERATOR_IMAGE=kuberay/operator:nightly python3 tests/test_sample_rayservice_yamls.py
```

The RayServiceAddCREvent converges in 32 seconds. I guessed the root cause of this issue is `RAY_IMAGE`. The current test framework will not replace the RAY_IMAGE automatically, so the Pod will pull the image from DockerHub instead if `RAY_IMAGE` is not the same as the value of `image` in the YAML file.
