### ISSUE TITLE
[Bug] CI fails with the exit code 137 (OOM)

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#852]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen

The following four CI runs (ray:2.0.0) failed with the exit code 137 ([OOMKilled Kubernetes Error](https://komodor.com/learn/how-to-fix-oomkilled-exit-code-137/#:~:text=All%20with%20Komodor-,What%20is%20OOMKilled%20(exit%20code%20137),utilize%20on%20the%20host%20machine.)). Maybe we should increase memory limit.

* https://github.com/ray-project/kuberay/actions/runs/3806898349/jobs/6476278903
* https://github.com/ray-project/kuberay/actions/runs/3804089862/jobs/6471074834
* https://github.com/ray-project/kuberay/actions/runs/3807140668/jobs/6476615596
* https://github.com/ray-project/kuberay/actions/runs/3807140668/jobs/6476615670

### Reproduction script

* https://github.com/ray-project/kuberay/actions/runs/3806898349/jobs/6476278903
* https://github.com/ray-project/kuberay/actions/runs/3804089862/jobs/6471074834
* https://github.com/ray-project/kuberay/actions/runs/3807140668/jobs/6476615596
* https://github.com/ray-project/kuberay/actions/runs/3807140668/jobs/6476615670

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
Interesting. Why just 2.0.0 jobs failed recently? Did we make any changes on the test cases?

**Comment by Jeffwan** [comment]
@kevin85421 Can you help coordinate with the admin team on the test resources if we bump the instances?

**Comment by kevin85421** [comment]
@Jeffwan 

> Interesting. Why just 2.0.0 jobs failed recently? Did we make any changes on the test cases?

It not only happen in 2.0.0. For example, 
https://github.com/ray-project/kuberay/actions/runs/3807140668/jobs/6476615596

> Can you help coordinate with the admin team on the test resources if we bump the instances?

Yes, I plan to move KubeRay CI from GitHub Actions to Buildkite. Will track the progress at #695.

Honestly, this bug is weird for me. I am not sure about the root cause. The only information I knew is the exit code 137 (OOM).

**Comment by kevin85421** [comment]
The current compatibility test for the nightly Ray image fails constantly with exit code 137. Hence, we need to increase the priority of #695 to relieve this issue.

**Comment by Yicheng-Lu-llll** [comment]
In the last few days, Sample YAML Config Test - 2.1.0 also failed frequently with the exit code 137.
Here are some:
- https://github.com/ray-project/kuberay/actions/runs/3980661359/jobs/6823940072
- https://github.com/ray-project/kuberay/actions/runs/3975212288/jobs/6814967577
- https://github.com/ray-project/kuberay/actions/runs/3961701335/jobs/6787557147
- https://github.com/ray-project/kuberay/actions/runs/3961701335/jobs/6787557147

I also test this locally with 16 cores, 12GB VM by running the:
`RAY_IMAGE=rayproject/ray:2.2.0 OPERATOR_IMAGE=kuberay/operator:nightly python3 tests/test_sample_raycluster_yamls.py
`

The result is interesting:

- There is a certain probability that the error can be reproduced, and the probability will increase with the number of web pages I open (less and less available memory) until the error can be stably reproduced.
- If I test each raycluster yaml independently, then there will be no failure.

So, from the above,  it seems that memory usage accumulated as testing  more raycluster yamls when running tests/test_sample_raycluster_yamls.py.

**Comment by kevin85421** [comment]
Exit code 137 is not only for OOM. @Yicheng-Lu-llll would you mind adding more details? In addition, it is relieved by https://github.com/ray-project/kuberay/pull/929.

**Comment by Yicheng-Lu-llll** [comment]
> Exit code 137 is not only for OOM. @Yicheng-Lu-llll would you mind adding more details? In addition, it is relieved by #929.

Sure. Exit code 137 actually Indicates failure as container received SIGKILL

**Comment by Yicheng-Lu-llll** [comment]
> Exit code 137 is not only for OOM. @Yicheng-Lu-llll would you mind adding more details? In addition, it is relieved by #929.

Sure. Exit code 137 actually indicates that the pod(container) received a SIGKILL signal from other processes. 

OOM is not the only reason that caused exit code 137. There are actually many possible situations that may cause the pod/container to receive a SIGKILL signal. 

- situation 1: We can manually send SIGKILL using `kubectl delete {pod} `,  `docker kill {container}`, or `kill -9 {entrypoint's pid}` to kill pod/container. and pod/container will exit with code 137.
We can use `kubectl describe {pod} `to see the real reasons. After manually sending a SIGKILL signal to a ray worker pod, the ray worker pod will crash and restart by kubelet. You can see that The `Reason` is `error` instead of `OOMKilled`.
 ```
 Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Fri, 24 Feb 2023 21:51:24 +0000
      Finished:     Fri, 24 Feb 2023 21:56:13 +0000
```
- situation 2: See https://github.com/ray-project/kuberay/pull/929. This PR fix the Compatibility Test - Nightly issue. Previously this test always fails with exit code 137.

**Comment by kevin85421** [comment]
This issue has not occurred for several months.
