### ISSUE TITLE
Build v0.5.0 Roadmap

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#853]
The community has release v0.4.0 in past few weeks and let's build up release plan for v0.5.0.  
Milestone v0.5.0 has been created and well maintained  https://github.com/ray-project/kuberay/milestone/5,  we need to figure out our concentration and also build a release/roadmap team.

**Comment by DmitriGekhtman** [comment]
We should probably decide on a deadline. Releasing once per two Ray releases could make sense -- so we'd aim to align with the Ray 2.4.0 release.
cc @kevin85421
