### ISSUE TITLE
[Feature] Add headServiceLabels field to RayCluster CR

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#868]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Users want to set custom labels for the KubeRay Head Service. However, currently, KubeRay only supports custom annotations for the Head Service. 

https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1673647485229799

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
@Yicheng-Lu-llll are you interested in this issue? This is a good first issue to understand the workflow of operator development. In addition, the implementation will be very similar to https://github.com/ray-project/kuberay/pull/841.

**Comment by Yicheng-Lu-llll** [comment]
> @Yicheng-Lu-llll are you interested in this issue? This is a good first issue to understand the workflow of operator development. In addition, the implementation will be very similar to #841.

Sure. Thank you!
