### ISSUE TITLE
[Feature]  Enable Grafana Dashboard integration with KubeRay

### ISSUE THREAD

**Issue by peterghaddad** [ray-project/kuberay#871]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, Ray exposes all Grafana files on the head node in the `session_latest` directory. See [docs](https://docs.ray.io/en/latest/ray-observability/ray-metrics.html#grafana).

Enable KubeRay the ability to configure a Grafana Instance and Prometheus instance (which is NOT running in the same container as the Ray Head Node). 

Integrate Ray Dashboard UI to display graphs from Grafana.

Potential solutions: add configuration options through the ray-cluster yaml?

### Use case

Allow the user to integrate external Grafana and Prometheus instances with Ray while utilizing the default dashboards.

### Related issues

NA

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Does https://github.com/ray-project/kuberay/pull/895 resolve this issue? Thanks!

**Comment by peterghaddad** [comment]
@kevin85421 Was reading through the updates, and looks like great changes you've made to enable better implementation with Kuberay! To confirm, do these updates allow us to point to a different Prometheus instance, can a custom URL be used to point? I think the big piece was the integration with the Ray dashboard. Do these updates allow users to view the graphs from the Ray Dashboard while using a Grafana instance hosted, in say, a different namespace?

**Comment by kevin85421** [comment]
> To confirm, do these updates allow us to point to a different Prometheus instance? I think the big piece was the integration with the Ray dashboard. 

Yes, in #895, the Prometheus server is not running in Ray head Pod. In addition, the Prometheus server is created by Step 2, and the Ray head Pod is created by Step 4.

> Do these updates allow users to view the graphs from the Ray Dashboard while using a Grafana instance hosted elsewhere on the cluster?

Yes. Grafana is included in [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) chart. Hence, Grafana will be installed in the `prometheus-system` namespace in Step 2. Next, in Step 8,  we can import Ray Dashboard into Grafana via [dashboard_default.json](https://github.com/ray-project/kuberay/blob/master/config/grafana/dashboard_default.json).

In my understanding, **dashboard_default.json** should be equivalent to Ray Dashboard. cc @scarlet25151 to confirm.

**Comment by peterghaddad** [comment]
Thanks @kevin85421. I think the difference is displaying the Grafana graphs on Grafana vs on Ray i.e integrated into the Ray Dashboard.
