### ISSUE TITLE
[Bug] Pod updates should trigger RayCluster reconciliation

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/kuberay#872]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

See https://github.com/ray-project/kuberay/pull/850#issuecomment-1368534811 and related comments on that PR.

Currently, pod state changes don't trigger cluster reconciliation. This is due to an event filter: https://github.com/ray-project/kuberay/blob/633ff6375099b2737db4c74a51c31028d2e54bc3/ray-operator/controllers/ray/raycluster_controller.go#L803

We should not filter out pod status changes, but continue to filter out RayCluster status changes. We should take care to avoid reconciling in a tight loop, because `instance.Status.LastUpdateTime` is updated at each reconciliation.

### Reproduction script

Same reproduction as in https://github.com/ray-project/kuberay/issues/845.  That issue will soon be closed by https://github.com/ray-project/kuberay/pull/850 using a separate fix (always reconciling every 60 seconds), but the present issue is still valid. This issue will fix the up to 60s delay between the cluster being ready and the Ray Job being submitted (this is triggered by the next periodic reconcile).

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by davidxia** [comment]
@architkulkarni @DmitriGekhtman thanks for noticing this! I just proposed a fix in #882. I don't know how to test it manually though. Lmk if it looks good.
