### ISSUE TITLE
[Feature] Expose loadBalancerIP for head service to users

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#877]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Users may want Ray head to be accessible from outside Kubernetes. One option is to use Kubernetes Service with type `LoadBalancer` and specify `loadBalancerIP`. However, KubeRay currently does not expose `loadBalancerIP` to users. See https://discuss.ray.io/t/specify-ip-adress-for-the-head-as-a-loadbalancer-service-type/9008 for more details.

### Related issues

https://discuss.ray.io/t/specify-ip-adress-for-the-head-as-a-loadbalancer-service-type/9008

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by DmitriGekhtman** [comment]
We should expose as many fields as people ask for.

Probably we should have just exposed the entire service (maybe we did in the initial version)
