### ISSUE TITLE
[Bug] `.status.availableWorkerReplicas` incorrectly counts head Pods

### ISSUE THREAD

**Issue by davidxia** [ray-project/kuberay#885]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

`kubectl get raycluster my-cluster -o yaml` shows `.status.availableWorkerReplicas` as always one more than `.status.desiredWorkerReplicas`. I think the operator is incorrectly including head Pods in `availableWorkerReplicas`.

[see previous comment](https://github.com/ray-project/kuberay/pull/878#issuecomment-1400405806)

### Reproduction script

Create a RayCluster with workers. Run `kubectl get raycluster my-cluster -o yaml` and look at `.status`.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by davidxia** [comment]
@kevin85421 @Jeffwan I'm happy to work on this if the bug report looks good to you. Probably a straight forward fix.

**Comment by kevin85421** [comment]
Thanks, @davidxia!
