### ISSUE TITLE
[Feature] Ray cluster monitor dashboard

### ISSUE THREAD

**Issue by superhaiou** [ray-project/kuberay#89]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

A user friendly dashboard for people not familiar with Ray or K8S to monitor the resource usage (CPU/memory/IO, etc ), the status of the current job (one dynamic Ray cluster per job);

More interactive UI that users can operate on the UI such as start/pause/stop the jobs, filter the jobs per submitter, etc.

### Use case

Ray Search project: the HQ team members are requesting for interactive UIs.

### Related issues

No

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
This is out-of-box supported. You will need to enable dashboard service in ray head and then expose the port from the container. 

https://github.com/ray-project/kuberay/blob/71a238a990754c2d7b91339b2f91f3822a6ebee7/ray-operator/config/samples/ray-cluster.mini.yaml#L29

https://github.com/ray-project/kuberay/blob/71a238a990754c2d7b91339b2f91f3822a6ebee7/ray-operator/config/samples/ray-cluster.mini.yaml#L63-L64

**Comment by Jeffwan** [comment]
Feel free to reopen the issue if this doesn't solve the problem. I will close this issue
