### ISSUE TITLE
[Feature] Add a KubeRay Python Client Library to manage RayCluster using KubeRay

### ISSUE THREAD

**Issue by akanso** [ray-project/kuberay#899]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Today we can create/update/delete _rayclusters_ using `kubectl`, `helm`, etc. with `yaml/JSON` manifests describing the raycluster.

A Python library that can programmatically manage rayclusters (using kuberay) will enable Python applications running on top of Ray and using KubeRay to add/remove/update worker-groups on the fly. 

This library enables the application itself to scale the worker-groups horizontally and vertically.

### Use case

Two main use cases:

1- Enable a Python application to programmatically manage rayclusters (using kuberay) without the need to deal with YAML/JSON files. 

2- We can use this KubeRay Python Client Library in our tests (E2E/Integration) to manage rayclusters without having to run `kubectl` command from our tests that are written in Python

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Close this issue because #901 is merged.
