### ISSUE TITLE
How to enable GPU on KubeRay based local kind?

### ISSUE THREAD

**Issue by allingo** [ray-project/kuberay#900]
I want to test gpu support of kubeRay on my computer, but there is no doc about this.
It seems that kind not support GPU？should I use minikube instead?

**Comment by kevin85421** [comment]
The Kind community may be the best place to answer this question. When you have a Kubernetes cluster with GPU, you can follow the following documents to run Ray workload with GPUs on KubeRay:

* https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/gpu.html
* https://docs.ray.io/en/latest/cluster/kubernetes/examples/gpu-training-example.html

Feel free to reopen this issue if you have questions about the Ray documents. (Note: updated documents will be out when Ray 2.4.0 is officially available.)
