### ISSUE TITLE
[Feature] Can ray be deployed and run on k8s version 1.18

### ISSUE THREAD

**Issue by ChenhanXmu** [ray-project/kuberay#905]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Can ray be deployed and run on k8s version 1.18

### Use case

Can ray be deployed and run on k8s version 1.18

### Related issues

Can ray be deployed and run on k8s version 1.18

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
I am not sure about the answer, but I think most features in KubeRay will work with Kubernetes 1.18.

Other information:
* Some documents will not work with Kubernetes 1.18 (e.g. [pod-security.md](https://github.com/ray-project/kuberay/blob/master/docs/guidance/pod-security.md) only works with Kubernetes 1.22+)
* https://github.com/ray-project/kuberay/issues/466

**Comment by ChenhanXmu** [comment]
I got this error in the ray-operator pod：
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/13248089/219243298-56888cdf-f3c7-4fcf-87da-d510609e80eb.png">

**Comment by kevin85421** [comment]
@ChenhanXmu I opened PR #911 to fix the issue. With the PR, the KubeRay operator will not report the error. However, the RayCluster chart and YAML are still incompatible with Kubernetes 1.18. Will work on the following if #911 is approved by the community.

**Comment by ChenhanXmu** [comment]
Thanks！

**Comment by ChenhanXmu** [comment]
> 

What is the incompatibility between the RayCluster YAML and Kubernetes 1.18？
<img width="359" alt="image" src="https://user-images.githubusercontent.com/13248089/220279550-6132d2f7-6760-4140-b81c-f9e72a6c09cd.png">

**Comment by kevin85421** [comment]
We decide not to support Kubernetes 1.18.
