### ISSUE TITLE
[Bug] unable to connect to GCS when submitting a job

### ISSUE THREAD

**Issue by uxth** [ray-project/kuberay#906]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

I am expecting the job could be submitted

### Reproduction script

start a minikube cluster
deploy kuberay operator and ray-cluster to minikube cluster by using the helm chart in this repo with latest version following the readme instruction
do a kubectl port-forward for port 8265
submit a job to this ray cluster like this 'ray job submit --address localhost:8265 -- python3 test.py' then it returned this error:

WARNING utils.py:1415 -- Unable to connect to GCS at 10.160.66.135:8265. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.

### Anything else

submitting the job used to work, but not with the latest version, same steps performed but different result seen.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by uxth** [comment]
same result seen after disabled the firewall on my host machine.
any other suggestions please?

**Comment by kevin85421** [comment]
This may be related to the version mismatch between `ray job` on your laptop and the version in the Ray Pod.

You can try to reproduce the mismatch error by using `rayproject/ray:1.9.0` image for Ray head and `rayproject/ray:2.2.0` image for Ray worker in [ray-cluster.complete.yaml](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-cluster.complete.yaml). Then, use `kubectl logs` to check the logs in the worker Pod.

<img width="1436" alt="Screen Shot 2023-02-15 at 2 05 27 PM" src="https://user-images.githubusercontent.com/20109646/219183166-f5ba6f83-2d1b-40cd-a2ba-98f17faa746f.png">

**Comment by uxth** [comment]
I just tried it, but with no luck, still the same message

I have even changed both of the head and worker to 1.9.0, but still the same:

kubectl get pod raycluster-complete-head-b785x -o yaml | grep rayproject
    image: rayproject/ray:1.9.0
    image: rayproject/ray:1.9.0
    imageID: docker-pullable://rayproject/ray@sha256:055fd11dd70ac3f403b9356fb48d9dc37217656ae228d4fa395e4c8078e75975

kubectl get pod raycluster-complete-worker-small-group-j2bk5 -o yaml | grep rayproject
    image: rayproject/ray:1.9.0
    image: rayproject/ray:1.9.0
    imageID: docker-pullable://rayproject/ray@sha256:055fd11dd70ac3f403b9356fb48d9dc37217656ae228d4fa395e4c8078e75975

**Comment by kevin85421** [comment]
Where do you run `ray job submit --address localhost:8265 -- python3 test.py`? In the head Pod or outside the Kubernetes cluster? 

If you run the `ray job` command outside the Kubernetes cluster, the version mismatch may be related to your Ray package on your laptop and the version of the head Pod's Docker image.

cc @architkulkarni

**Comment by uxth** [comment]
it is from my dev box, which is the minikube host. basically it is out side of the cluster
I installed my ray package by 'pip install -U "ray[default]"', just as the [document](https://docs.ray.io/en/latest/ray-overview/installation.html) said.

my ray package version is:
ray --version
ray, version 1.12.1

is there a way to upgrade my ray package locally?

**Comment by architkulkarni** [comment]
`pip install -U "ray[default]"` should have upgraded your ray package to the latest version, 2.2.0.  Maybe try uninstalling and reinstalling?

**Comment by uxth** [comment]
just uninstalled and reinstalled it, now it is 1.22.0.

tried the solution with head version 1.9.0 and worker version 1.22.0, using kubectl logs to get worker's log:

`Defaulted container "ray-worker" out of: ray-worker, init (init)
2023-02-15 15:52:34,621 WARNING utils.py:1415 -- Unable to connect to GCS at raycluster-complete-head-svc:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
2023-02-15 15:52:41,709 WARNING utils.py:1415 -- Unable to connect to GCS at raycluster-complete-head-svc:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.`

looks like worker still has the same issue

**Comment by architkulkarni** [comment]
Is it possible to make the head version 2.2.0 as well? The head and worker Ray versions need to match

**Comment by uxth** [comment]
yes, I just did that.
I can confirm that my local ray package, ray head and worker are working on version 2.2.0 now.
![image](https://user-images.githubusercontent.com/76676553/219227362-3b10a991-af12-4ce4-ba12-0cd4bb53e25b.png)

but when submitting the job it still says GCS not connected.
![image](https://user-images.githubusercontent.com/76676553/219227457-cd269753-827e-4469-8241-0d2395a4e266.png)

any suggestions? thanks

**Comment by kevin85421** [comment]
@uxth Would you mind trying with `kind` rather than `minikube`? Could you access Dashboard via `localhost:8265`?

**Comment by uxth** [comment]
yes, I just installed kind and created a cluster to test, the result is the same:
![image](https://user-images.githubusercontent.com/76676553/220719060-69115d79-67d7-4d7a-a627-5e0838138979.png)

more, I have tested it on an EKS cluster, same result seen.

**Comment by architkulkarni** [comment]
Ray issue: https://github.com/ray-project/ray/issues/32736
