### ISSUE TITLE
[Feature] Add support for TPUs in Kuberay operator

### ISSUE THREAD

**Issue by richardsliu** [ray-project/kuberay#908]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

GKE will add support for TPU VMs in early 2023. This feature helps track the work to enable TPU support in Kuberay.

I would be glad to help drive this effort on the GKE side.

### Related issues

https://github.com/ray-project/ray/issues/25223#issuecomment-1364445190

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by brandonroyal** [comment]
@richardsliu Is this issue resolved? I see related merged PRs #37934 and #38588?

**Comment by kevin85421** [comment]
KubeRay v1.1.0 has already solved this issue.
