### ISSUE TITLE
[Bug] gRPC ingress using RayServe with Kuberay fails

### ISSUE THREAD

**Issue by nihal-rao-swi** [ray-project/kuberay#909]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

**What happened**
We are trying to use RayServe with gRPC. We have configured our application as per https://docs.ray.io/en/latest/serve/direct-ingress.html and this works fine when running as standalone ray server.
All requests to this ray-serve application fails with below error when we tried running it with kuberay. Also, for some reason even the port-forwarding to ray-serve k8s service terminates abruptly.

**Expected behavior**
RayServe with gRPC should work with kuberay the same way it works as a standalone ray server

### Reproduction script

Running the gRPC example server with kuberay should end up with the same error
https://docs.ray.io/en/latest/serve/direct-ingress.html

### Anything else

Kuberay operator - 0.4.0
Ray version - 2.2.0

Error on client side -
```
Traceback (most recent call last):
  File "/Users/pranav/Downloads/ray_client/grpc_client.py", line 32, in <module>
    send_request()
  File "/Users/pranav/Downloads/ray_client/grpc_client.py", line 20, in send_request
    response = stub.Train(train_request)
  File "/opt/homebrew/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/homebrew/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:9000: Failed parsing HTTP/2"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:9000: Failed parsing HTTP/2 {created_time:"2023-02-10T17:27:22.916189+05:30", grpc_status:14}"
```
Error with port-forwarding -
```
Forwarding from 127.0.0.1:9000 -> 9000
Forwarding from [::1]:9000 -> 9000
Handling connection for 9000
E0210 17:53:21.290382   57259 portforward.go:400] an error occurred forwarding 9000 -> 9000: error forwarding port 9000 to pod 84c6abb7e46cd049fa3ebdfdc2684fa9261b0cceb76f224c2fd8c72d0dcdd66f, uid : exit status 1: 2023/02/10 12:23:21 socat[30652] E connect(5, AF=2 127.0.0.1:9000, 16): Connection refused 
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nihal-rao-swi** [comment]
FYI @pranav-shankar-swi @karthikmuralidharan

**Comment by richardliaw** [comment]
also cc @sihanwang41 as FYI

**Comment by shrekris-anyscale** [comment]
@nihal-rao-swi are you still running into the issue? @rumeshkrish mentioned that they were able to get around it.
