### ISSUE TITLE
[Feature] Add observedGeneration to the status of CRDs

### ISSUE THREAD

**Issue by gariepyalex** [ray-project/kuberay#916]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

It is considered a [good practice](https://alenkacz.medium.com/kubernetes-operator-best-practices-implementing-observedgeneration-250728868792) for Kubernetes resources to have an `observedGeneration` sub resource in their `status`.  It should be added to `RayService` and `RayCluster`. 

### Use case

I am trying to integrate the `RayService` CRD to [Shopify's Krane](https://github.com/Shopify/krane#deploying-custom-resources). It required CRDs to expose an `observedGeneration` filed in the `status`.

### Related issues

Here is a related `kubernetes-sigs` issue that can add more context:
https://github.com/kubernetes-sigs/cluster-api/issues/3078

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Hi @gariepyalex, would you mind adding a label about the priority (P0, P1, P2, P3) of this issue for your work? Thanks!

**Comment by gariepyalex** [comment]
Hi @kevin85421 , this would be a P1 for us. I don't have the rights to add the label myself.

**Comment by kevin85421** [comment]
I will draft a PR this week.

**Comment by kevin85421** [comment]
Close this one. The following works will be traced by https://github.com/ray-project/kuberay/issues/983.
