### ISSUE TITLE
[Feature] Easier way to build the cluster image

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#92]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

prepare a way to install the dependencies and build a custom image for users. 

### Use case

For a dedicated cluster to run a specific workload, user normally won't use job level runtime. Instead, they expect the cluster have dependencies installed directly  and they are able to kick off the job immediately. 

In that case, we need to create the ray cluster with preinstall dependencies. 
User can definitely run Dockerfile by their own but it's not easy for platform owner to share the images and index the dependencies. 

Let's implement this in a managed way

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by Jeffwan** [comment]
I will drive the design and initial implementation of this feature

**Comment by kevin85421** [comment]
The Ray community currently provides several Docker images with various dependencies. I will now close this issue, but please feel free to reopen it if I have misunderstood the issue.
