### ISSUE TITLE
[Feature] Inject cluster name as an environment variable into head and worker pods

### ISSUE THREAD

**Issue by JoshKarpel** [ray-project/kuberay#928]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

The cluster name should be easily available from inside Kubernetes pods inside the cluster. An env var would be more convenient than e.g. a Ray API call, so that this would be available both from inside Python and from e.g. bash scripts.

### Use case

I'd like to use the cluster name for namespacing extra information I'll be storing in an external Redis.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
@Yicheng-Lu-llll are you interested in this issue?

**Comment by Yicheng-Lu-llll** [comment]
Sure

**Comment by Yicheng-Lu-llll** [comment]
Hi @JoshKarpel.  I would like to double-check if this is what you want.

In the head or worker pod:
<img width="1280" alt="1677622173801" src="https://user-images.githubusercontent.com/51814063/221992786-66acbf1d-bc40-4180-927e-2ebbb01633e9.png">

**Comment by JoshKarpel** [comment]
Oh, I think maybe that isn't what I meant, though that looks useful too. What I was thinking of was the same name that ends up getting used in keys for GCS Fault Tolerance with Redis, which is presumably uniquely generated across different instances of the cluster during e.g. a rolling deploy.

**Comment by Yicheng-Lu-llll** [comment]
> Oh, I think maybe that isn't what I meant, though that looks useful too. What I was thinking of was the same name that ends up getting used in keys for GCS Fault Tolerance with Redis, which is presumably uniquely generated across different instances of the cluster during e.g. a rolling deploy.

So, It is not the ray cluster name defined in ray cluster CR but the Redis's key?

I wonder if you could give me an example so that I can better understand what env var you want.

**Comment by Yicheng-Lu-llll** [comment]
I get your idea, thank you for explaining!  https://github.com/ray-project/kuberay/pull/934 actually meet your need.

In your case, rayservice name is `rayservice-sample`. raycluster name is `rayservice-sample-raycluster-svl4r`.
In my previous example, I use raycluster directly while in your case, you use rayservice.


So, in my PR, After running  `kubectl apply -f config/samples/ray_v1alpha1_rayservice.yaml`:
<img width="1280" alt="1677638568884" src="https://user-images.githubusercontent.com/51814063/222031591-078e09a8-ca80-4606-8394-20967a87c208.png">

You can get the `a unique, cluster-global, cluster-instance-unique string`  from env var `CLUSTER_NAME`

**Comment by JoshKarpel** [comment]
D'oh! I get it! That is indeed exactly what I need. Thanks for bearing with me!
