### ISSUE TITLE
[Bug] No rayVersion in the RayCluster chart

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#931]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

No rayVersion in the RayCluster chart. Write some instructions about how to change Ray versions.

### Reproduction script

TODO

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @Yicheng-Lu-llll

**Comment by Yicheng-Lu-llll** [comment]
Sure
