### ISSUE TITLE
[Feature] Make the head service headless

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#948]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

https://github.com/ray-project/ray/pull/33030#pullrequestreview-1330044213
https://github.com/kubernetes-sigs/kind/issues/3118

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Other use case: Istio 

https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1679595828577909?thread_ts=1678309468.145329&cid=C02GFQ82JPM

**Comment by juliusvonkohout** [comment]
@kevin85421 is this solved now, such that we can continue with istio and ray on kubeflow?

**Comment by kevin85421** [comment]
Other use case: https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1712780988188599?thread_ts=1712333199.632539&cid=C02GFQ82JPM

**Comment by kevin85421** [comment]
@rueian will take this issue.

**Comment by kevin85421** [comment]
Closed by https://github.com/ray-project/kuberay/pull/2117
