### ISSUE TITLE
[Feature] Read Redis password from Kubernetes Secret

### ISSUE THREAD

**Issue by JoshKarpel** [ray-project/kuberay#949]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Slack thread: https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1678307332093999

Users should be able to provide the Redis password to KubeRay for GCS FT via a Kubernetes Secret.

### Use case

In my production environment, the Redis password is available as a Kubernetes Secret. In the example at https://github.com/ray-project/kuberay/blob/8da54d4cbe0894b7af98edec9b0609beaf1189e3/ray-operator/config/samples/ray-cluster.external-redis.yaml#L90 the password is plain text in the resource, which we can't do.

We typically bind-mount the Secret as a file, so it would be convenient for us to just be able to specify the file path that contains the Redis password in the start params, but really any method of getting the password "indirectly" from the Secret would be fine for us.

### Related issues

Maybe sort of related to https://github.com/ray-project/kuberay/issues/203 ?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by scv119** [comment]
@kevin85421 to triage. let's know if it's a pure kuberay change or need changes in Ray core.

**Comment by kevin85421** [comment]
@JoshKarpel Could you try this https://github.com/ray-project/kuberay/pull/950? Thanks!
