### ISSUE TITLE
[Feature] Only submit job when all nodes in the clusters are ready

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/kuberay#962]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

We have some jobs can not successfully run without all resources are ready.  Even with gang-scheduling, it's not working because the time scheduler decide to permit all pods, some may run and some take more time to download image etc. It increases the chance our job get into error.

### Use case

Make sure resources are fully ready before submitting job.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Basasuya** [comment]
through the /nodes API given by dashboard(https://github.com/ray-project/ray/blob/master/dashboard/modules/node/node_head.py#L239), we can get the node status to judge if we should submit the job.
for example, we can wait for ready nodes equal to the cluster nodes define in cluster custom resource.
Or we can set the ready nodes ratio to submit the job

**Comment by kevin85421** [comment]
#1733
