### ISSUE TITLE
Where could I find the release schedule, e.g. for v0.5.0?

### ISSUE THREAD

**Issue by dizhouwu** [ray-project/kuberay#970]
Many thanks.

**Comment by kevin85421** [comment]
[KubeRay Sync Notes](https://docs.google.com/document/d/1TCeBFVUyXVVHpbJegjbykiXArSn11Cm6sfNYkSzsrhY/edit#heading=h.bt362hjxhdwd) is the note for community's bi-weekly sync. In short, v0.5.0 targets on Mar. 30. Thank you for reaching out!

**Comment by dizhouwu** [comment]
Thank you!
