### ISSUE TITLE
[Feature] Remove block: true in configuration YAML files after release 0.5.0

### ISSUE THREAD

**Issue by Yicheng-Lu-llll** [ray-project/kuberay#971]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

We plan to inject the --block option to ray start command automatically(see https://github.com/ray-project/kuberay/pull/932). As a result, it will no longer be necessary to include `block: true` in the` rayStartParams` in the configuration YAML files.

However, To maintain compatibility with both the nightly and the latest release of the KubeRay operator, we should remove `block: true`  from the configuration YAML files after the release of version 0.5.0. 

### Related issues

https://github.com/ray-project/kuberay/pull/932

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Finish some parts of this issue in #1015 to continue with the process. The others can be resolved by other PRs later.

**Comment by kevin85421** [comment]
Close by #1050
