### ISSUE TITLE
[Feature] Upgrade python version from 3.7.16

### ISSUE THREAD

**Issue by romeokienzler** [ray-project/kuberay#981]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

kuberay on master as of a0ee1c886f02433d3aa00d37945099331bda4c29 still installs ray based on python version 3.7.16

### Use case

I can't read ZARR files via XArray using kuberay

### Related issues

causes issues on client libraries as support for 3.7 is slowly vanishing 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
Hi @romeokienzler, thank you for opening this issue! Do you mean the Python version in Ray's image? In that case, you can update the image.

**Comment by kevin85421** [comment]
Feel free to reopen this issue if https://github.com/ray-project/kuberay/issues/981#issuecomment-1483729625 does not answer your question : )
