### ISSUE TITLE
[Service] Multi app support in Kuberay 

### ISSUE THREAD

**Issue by sihanwang41** [ray-project/kuberay#985]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Ray Serve is already supporting multi application in 2.0 API.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by brosand** [comment]
Specifically supporting these uses -- https://docs.ray.io/en/releases-2.4.0/serve/multi-app.html#adding-deleting-and-updating-applications -- would be great

**Comment by kevin85421** [comment]
cc @v4if

**Comment by zcin** [comment]
Done by https://github.com/ray-project/kuberay/pull/1136 and https://github.com/ray-project/kuberay/pull/1156
