### ISSUE TITLE
[Feature] Add a timeout to the init container

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#988]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

In https://github.com/ray-project/kuberay/pull/973, we use `ray health-check` in init container to wait until the GCS is ready. What will happen if the GCS server will not be ready? Do we have a timeout mechanism?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
cc @Yicheng-Lu-llll

**Comment by Yicheng-Lu-llll** [comment]
After further investigation, the current implementation seems appropriate.

- As per the [Kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#understanding-init-containers), if a Pod's init container fails, the kubelet continuously restarts the init container until it succeeds (the restartPolicy cannot be set to Never; if it is, the Pod is treated as failed). Therefore, setting a timeout for the init container does not make changes, as the kubelet will restart it regardless.

- Allowing the init container to run indefinitely is acceptable. Users can easily check the pod's status to determine if the init container is causing a blockage. They can then debug with the head service and GCS server.
