### ISSUE TITLE
[Feature] Deterministic hostname for each Ray worker

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#995]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently, the name of a Ray worker is generated randomly. However, a deterministic hostname for each Ray worker can benefit the following use cases:

1. TLS authentication: Because Ray workers do not have deterministic hostnames, we need to create the certificates whenever a worker restarts. Some users want to create a certificate once and use it multiple times. See this [thread](https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1680026261195009?thread_ts=1679610977.533419&cid=C02GFQ82JPM) for more details.
    * "Currently our cert infra does not even consider IP as a reasonable part of the x509 certificate SAN" ([link](https://ray-distributed.slack.com/archives/C02GFQ82JPM/p1680282474486699?thread_ts=1680024032.365739&cid=C02GFQ82JPM))

3. TPU support: TPU workers in Jax needs to directly communicate with each other using an open port

### Related issues

https://github.com/ray-project/kuberay/issues/908

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by richardsliu** [comment]
Discussed with the Ray team (@richardliaw ) and the Google Cloud TPU team. The current plan for JAX[TPU] support is to include the following code snippet to set the `TPU_WORKER_ID` and `TPU_HOSTNAMES` environment variables on Ray nodes:

```
NUM_TPU_HOSTS = 32

@ray.remote(resources={"google.com/tpu": 4})
def get_hostname():
    import time; time.sleep(1)
    return socket.gethostname()

results = ray.get([get_hostname.remote() for x in range(NUM_TPU_HOSTS)])
id_hostname_map = {
    hostname: worker_id for worker_id, hostname in enumerate(set(results))}

@ray.remote(resources={"google.com/tpu": 4})
class TPUTrainingActor:
    def __init__(self, id_hostname_map):
        self.hostname = socket.gethostname()
        self.worker_id = id_hostname_map[self.hostname]
        os.environ["TPU_WORKER_ID"] = str(self.worker_id)
        os.environ["TPU_HOSTNAMES"] = ",".join(list(id_hostname_map))

    def train(self):
        ...
```

The longer term plan is to add this to the `ray.train` libraries. This is similar to the current pattern used for pytorch training:  https://github.com/ray-project/ray/blob/master/python/ray/train/torch/config.py#L155

**Comment by kevin85421** [comment]
Close this issue because the Ray community will provide a solution for TPU support.
